import type { PersonaProfile } from "./types"

const allEmphasis = {
  earthSim: true,
  itdxLab: true,
  personnelOutcomes: true,
  mindex: true,
  firmsAq: true,
  movement: true,
  restrictedCase: true,
  healthWorkspace: true,
  releaseQueue: true,
  aerosol: true,
  devices: true,
  briefingSynthetic: true,
}

function emphasis(partial: Partial<typeof allEmphasis>): typeof allEmphasis {
  return { ...allEmphasis, ...partial }
}

export const OWNER_PERSONA_ID = "owner_full"

export const PERSONA_PROFILES: PersonaProfile[] = [
  {
    persona_id: OWNER_PERSONA_ID,
    title: "Owner / full console",
    function_cluster: "owner",
    description: "Morgan/owner duty. Every Fusarium surface stays visible. Role lens never hides the app.",
    workflow_ids: [],
    entitlements: {
      defaultItdxView: "lab",
      defaultEarthSimLayers: ["live-data", "firms", "aq", "radar", "movement"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "fieldboard",
      primaryRoutes: ["/fusarium", "/fusarium/earth-simulator", "/fusarium/itdx", "/fusarium/personnel"],
      primaryTools: ["Earth Sim Live Data", "ITDX algorithm lab", "Personnel outcomes", "KO relay"],
      uxEmphasis: allEmphasis,
    },
  },
  {
    persona_id: "analyst",
    title: "All-source analyst",
    function_cluster: "intel",
    description: "Sourced assessment, hypotheses, abstention. Distinct from 350F reviewer.",
    workflow_ids: ["analysis"],
    entitlements: {
      defaultItdxView: "frames",
      defaultEarthSimLayers: ["live-data", "movement"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "evidence",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/mindex", "/fusarium/earth-simulator"],
      primaryTools: ["ITDX NLM/FormSpace", "MINDEX", "SYNTHETIC briefing (live:false)"],
      uxEmphasis: emphasis({ restrictedCase: false, healthWorkspace: false, releaseQueue: false }),
    },
  },
  {
    persona_id: "reviewer",
    title: "Technical / analytic reviewer",
    function_cluster: "intel",
    description: "Approval or return with reasons. Includes Army 350F vs 35F distinction.",
    workflow_ids: ["review"],
    entitlements: {
      defaultItdxView: "ranking",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "review",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/personnel/outcomes"],
      primaryTools: ["Source review & Borda", "Evidence exports", "Outcomes (not measured until survey)"],
      uxEmphasis: emphasis({ devices: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "geo",
    title: "GEOINT / cartography",
    function_cluster: "geo",
    description: "Traceable geometry, CRS, observed vs predicted.",
    workflow_ids: ["geo"],
    entitlements: {
      defaultItdxView: "replay",
      defaultEarthSimLayers: ["live-data", "firms", "movement"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "map",
      primaryRoutes: ["/fusarium/earth-simulator", "/fusarium/crep", "/fusarium/itdx"],
      primaryTools: ["Earth Simulator Live Data", "CREP", "Earth replay"],
      uxEmphasis: emphasis({ healthWorkspace: false, releaseQueue: false, restrictedCase: false }),
    },
  },
  {
    persona_id: "signals",
    title: "Signals / cryptologic",
    function_cluster: "intel",
    description: "Signals workflow. No clearance granted by persona pick.",
    workflow_ids: ["signals"],
    entitlements: {
      defaultItdxView: "sources",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "evidence",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/mindex"],
      primaryTools: ["Documents & citations", "MINDEX"],
      uxEmphasis: emphasis({ aerosol: false, devices: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "human_source",
    title: "CI / HUMINT specialist",
    function_cluster: "intel",
    description: "Restricted case/report workspace emphasis. Commercial surface stays UNCLASSIFIED.",
    workflow_ids: ["humint", "ci"],
    entitlements: {
      defaultItdxView: "sources",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "evidence",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/mindex"],
      primaryTools: ["Restricted case emphasis", "Provenance"],
      uxEmphasis: emphasis({ restrictedCase: true, aerosol: false, firmsAq: false, devices: false }),
    },
  },
  {
    persona_id: "weather_env",
    title: "Weather / METOC / hazard",
    function_cluster: "weather",
    description: "Observations, forecasts, CBRN/environment. Valid times and limits.",
    workflow_ids: ["weather", "hazard"],
    entitlements: {
      defaultItdxView: "lab",
      defaultEarthSimLayers: ["live-data", "aq", "radar", "firms"],
      defaultAerosolFocus: "aq-smoke",
      defaultSaPanel: "environment",
      primaryRoutes: ["/fusarium/earth-simulator", "/fusarium/aerosol", "/fusarium/itdx"],
      primaryTools: ["Earth Sim AQ/radar/FIRMS", "Aerosol map", "ITDX lab"],
      uxEmphasis: emphasis({ restrictedCase: false, releaseQueue: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "health_exposure",
    title: "Health / exposure",
    function_cluster: "medical",
    description: "Restricted health workspace emphasis. Wellbeing responses stay role-scoped, not a public roster.",
    workflow_ids: ["health"],
    entitlements: {
      defaultItdxView: "personnel",
      defaultEarthSimLayers: ["live-data", "aq"],
      defaultAerosolFocus: "aq-smoke",
      defaultSaPanel: "environment",
      primaryRoutes: ["/fusarium/personnel/survey", "/fusarium/aerosol", "/fusarium/personnel/outcomes"],
      primaryTools: ["NASA-TLX / WellBQ capture", "Aerosol", "KO outcomes"],
      uxEmphasis: emphasis({ healthWorkspace: true, restrictedCase: false, movement: false }),
    },
  },
  {
    persona_id: "ops_watch",
    title: "Operations / watch",
    function_cluster: "ops",
    description: "Current status, request tracking, handover. Not a live COP claim.",
    workflow_ids: ["ops"],
    entitlements: {
      defaultItdxView: "apps",
      defaultEarthSimLayers: ["live-data", "movement", "radar"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "fieldboard",
      primaryRoutes: ["/fusarium/situational-awareness", "/fusarium/earth-simulator", "/fusarium/avani"],
      primaryTools: ["Situational Awareness", "Earth Sim", "AVANI / MYCA"],
      uxEmphasis: emphasis({ restrictedCase: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "command",
    title: "Command / mission authority",
    function_cluster: "c2",
    description: "Accountable decisions and briefing. SYNTHETIC briefing stays live:false.",
    workflow_ids: ["command"],
    entitlements: {
      defaultItdxView: "outcomes",
      defaultEarthSimLayers: ["live-data", "movement"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "fieldboard",
      primaryRoutes: ["/fusarium/personnel/outcomes", "/fusarium/command-control", "/fusarium/itdx"],
      primaryTools: ["KO / command relay", "C2", "SYNTHETIC briefing"],
      uxEmphasis: emphasis({ personnelOutcomes: true }),
    },
  },
  {
    persona_id: "sensor_droid",
    title: "Sensor / droid operator",
    function_cluster: "maintainer",
    description: "Calibration, bounded sampling, device receipts.",
    workflow_ids: ["sensor"],
    entitlements: {
      defaultItdxView: "services",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "sensors",
      defaultSaPanel: "sensors",
      primaryRoutes: ["/fusarium/devices", "/fusarium/mycobrain", "/fusarium/sensing"],
      primaryTools: ["DirtNet devices", "MycoBrain", "Sensing tools"],
      uxEmphasis: emphasis({ devices: true, restrictedCase: false, releaseQueue: false }),
    },
  },
  {
    persona_id: "platform",
    title: "Systems / comms integrator",
    function_cluster: "maintainer",
    description: "Service health, identity, transport. Import grants no admin authority.",
    workflow_ids: ["integrator", "comms"],
    entitlements: {
      defaultItdxView: "services",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "services",
      primaryRoutes: ["/fusarium/monitoring", "/fusarium/adapters", "/fusarium/itdx"],
      primaryTools: ["System connections", "Mission assurance", "Adapters"],
      uxEmphasis: emphasis({ restrictedCase: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "cyber_defense",
    title: "Cyber defense",
    function_cluster: "ops",
    description: "Security and audit emphasis. Rank does not grant access.",
    workflow_ids: ["cyber"],
    entitlements: {
      defaultItdxView: "services",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "security",
      primaryRoutes: ["/fusarium/soc", "/fusarium/monitoring"],
      primaryTools: ["SOC", "Mission assurance"],
      uxEmphasis: emphasis({ aerosol: false, healthWorkspace: false }),
    },
  },
  {
    persona_id: "logistics",
    title: "Logistics / maintenance",
    function_cluster: "logistics",
    description: "Asset readiness and resource status.",
    workflow_ids: ["logistics"],
    entitlements: {
      defaultItdxView: "apps",
      defaultEarthSimLayers: ["live-data", "movement"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "logistics",
      primaryRoutes: ["/fusarium/earth-simulator", "/fusarium/devices"],
      primaryTools: ["Earth Sim movement", "NatureOS assets"],
      uxEmphasis: emphasis({ restrictedCase: false, healthWorkspace: false, releaseQueue: false }),
    },
  },
  {
    persona_id: "evaluator",
    title: "Model / test evaluator",
    function_cluster: "science",
    description: "Frozen model, withheld labels, Weka receipts. Receipt ≠ effectiveness study.",
    workflow_ids: ["evaluation"],
    entitlements: {
      defaultItdxView: "tests",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "evidence",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/personnel/outcomes"],
      primaryTools: ["ITDX Run & test", "Weka walkthrough", "Outcomes honesty tiles"],
      uxEmphasis: emphasis({ devices: false, restrictedCase: false }),
    },
  },
  {
    persona_id: "steward_release",
    title: "Data steward / release",
    function_cluster: "science",
    description: "Lineage, retention, destination-specific sharing. Failed release stays failed.",
    workflow_ids: ["steward", "release"],
    entitlements: {
      defaultItdxView: "exports",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "evidence",
      primaryRoutes: ["/fusarium/mindex", "/fusarium/itdx"],
      primaryTools: ["MINDEX", "Evidence exports", "Release queue emphasis"],
      uxEmphasis: emphasis({ releaseQueue: true, devices: false, aerosol: false }),
    },
  },
  {
    persona_id: "instructor",
    title: "Instructor / exercise controller",
    function_cluster: "science",
    description: "Practical results without exposing withheld truth.",
    workflow_ids: ["training"],
    entitlements: {
      defaultItdxView: "walkthrough",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "training",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/personnel/survey"],
      primaryTools: ["Walkthrough", "Survey capture", "SYNTHETIC briefing"],
      uxEmphasis: emphasis({ briefingSynthetic: true }),
    },
  },
  {
    persona_id: "oversight",
    title: "Program / manpower owner",
    function_cluster: "c2",
    description: "Workload and cost evidence. Pay examples are not salaries.",
    workflow_ids: ["oversight"],
    entitlements: {
      defaultItdxView: "outcomes",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "program",
      primaryRoutes: ["/fusarium/personnel", "/fusarium/personnel/outcomes"],
      primaryTools: ["Role catalog", "KO relay", "22 package calc checks (fixtures only)"],
      uxEmphasis: emphasis({ personnelOutcomes: true }),
    },
  },
  {
    persona_id: "liaison_partner",
    title: "Liaison / civil / partner viewer",
    function_cluster: "joint_civilian",
    description: "Authorized shared product only. Partner observer is read-oriented.",
    workflow_ids: ["liaison", "civil", "viewer"],
    entitlements: {
      defaultItdxView: "exports",
      defaultEarthSimLayers: ["live-data"],
      defaultAerosolFocus: "map",
      defaultSaPanel: "civil",
      primaryRoutes: ["/fusarium/itdx", "/fusarium/earth-simulator", "/fusarium/partner-mesh"],
      primaryTools: ["SYNTHETIC briefing", "Earth Sim", "Partner mesh"],
      uxEmphasis: emphasis({ restrictedCase: false, healthWorkspace: false, releaseQueue: false }),
    },
  },
]

export function personaById(id: string): PersonaProfile {
  return PERSONA_PROFILES.find((p) => p.persona_id === id) ?? PERSONA_PROFILES[0]
}
