import type { DevicesSnapshot } from './types';

const days = (n: number) => n * 24 * 60 * 60;
const hours = (n: number) => n * 60 * 60;
const mins = (n: number) => n * 60;

export const mockDevicesSnapshot: DevicesSnapshot = {
  source: 'mock',
  generatedAt: new Date().toISOString(),
  devices: [
    {
      id: 'gw-01',
      name: 'GATEWAY-01',
      type: 'gateway',
      model: 'UniFi Dream Machine',
      ip: '192.168.1.1',
      mac: 'AA:BB:CC:DD:EE:01',
      status: 'online',
      tags: ['core', 'edge'],
      metrics: { latencyMs: 8, uptimeSec: days(42) + hours(6) + mins(12), rxKbps: 2480, txKbps: 1750 },
      location: { x: 0, y: 0 },
    },
    {
      id: 'sw-01',
      name: 'SWITCH-01',
      type: 'switch',
      model: 'UniFi Switch 24 PoE',
      ip: '192.168.1.2',
      status: 'online',
      metrics: { latencyMs: 2, uptimeSec: days(42) + hours(6) + mins(5), rxKbps: 1900, txKbps: 900 },
      parentId: 'gw-01',
      location: { x: -120, y: 120 },
    },
    {
      id: 'sw-02',
      name: 'SWITCH-02',
      type: 'switch',
      model: 'UniFi Switch 8',
      ip: '192.168.1.3',
      status: 'online',
      metrics: { latencyMs: 3, uptimeSec: days(17) + hours(2) + mins(44), rxKbps: 780, txKbps: 420 },
      parentId: 'gw-01',
      location: { x: 140, y: 120 },
    },
    {
      id: 'ap-01',
      name: 'AP-01',
      type: 'access_point',
      model: 'UniFi U6 Lite',
      ip: '192.168.1.21',
      status: 'online',
      metrics: { latencyMs: 12, uptimeSec: days(12) + hours(9) + mins(2), rxKbps: 540, txKbps: 320 },
      parentId: 'sw-01',
      location: { x: -220, y: 240 },
    },
    {
      id: 'ap-02',
      name: 'AP-02',
      type: 'access_point',
      model: 'UniFi U6 Pro',
      ip: '192.168.1.22',
      status: 'warning',
      metrics: { latencyMs: 28, packetLossPct: 1.3, uptimeSec: days(3) + hours(12) + mins(18), rxKbps: 310, txKbps: 180 },
      parentId: 'sw-02',
      location: { x: 250, y: 240 },
    },
    {
      id: 'srv-01',
      name: 'SERVER-01',
      type: 'server',
      model: 'Dell PowerEdge',
      ip: '192.168.1.40',
      status: 'online',
      metrics: { cpuPct: 22, memPct: 61, tempC: 46, rxKbps: 920, txKbps: 640 },
      parentId: 'sw-01',
      location: { x: -60, y: 260 },
    },
    {
      id: 'nas-01',
      name: 'NAS-01',
      type: 'nas',
      model: 'Synology DS',
      ip: '192.168.1.41',
      status: 'online',
      metrics: { cpuPct: 11, memPct: 48, rxKbps: 520, txKbps: 210 },
      parentId: 'sw-01',
      location: { x: 40, y: 260 },
    },
    {
      id: 'myco-001',
      name: 'MYCOBRAIN-001',
      type: 'mycobrain',
      model: 'ESP32 MycoBrain',
      ip: '192.168.1.60',
      status: 'online',
      metrics: { tempC: 23.4, humidityPct: 67, powerV: 3.3, uptimeSec: days(14) + hours(3) + mins(22) },
      parentId: 'sw-02',
      location: { x: 110, y: 300 },
      tags: ['lab', 'biocompute'],
    },
    {
      id: 'pc-01',
      name: 'LAB-PC-01',
      type: 'client',
      model: 'Workstation',
      ip: '192.168.1.80',
      status: 'online',
      metrics: { rxKbps: 210, txKbps: 95, latencyMs: 9 },
      parentId: 'sw-02',
      location: { x: 240, y: 340 },
    },
    {
      id: 'phone-01',
      name: 'PHONE-01',
      type: 'client',
      model: 'Mobile',
      ip: '192.168.1.110',
      status: 'online',
      metrics: { rxKbps: 66, txKbps: 12, latencyMs: 18 },
      parentId: 'ap-01',
      location: { x: -260, y: 360 },
    },
    {
      id: 'laptop-01',
      name: 'LAPTOP-01',
      type: 'client',
      model: 'MacBook',
      ip: '192.168.1.111',
      status: 'offline',
      lastSeenAt: new Date(Date.now() - mins(37) * 1000).toISOString(),
      parentId: 'ap-01',
      location: { x: -160, y: 380 },
    },
  ],
};
