/**
 * Static Infrastructure Loader — PMTiles-first, GeoJSON-fallback (Fix C)
 *
 * Generated PMTiles (public/data/crep/tiles/*.pmtiles) are massively
 * cheaper to load and render than the raw GeoJSON files:
 *   • MapLibre only materialises features in the current viewport tile
 *   • HTTP range-requested — no full 12-16 MB download per layer
 *   • Typical compressed PMTiles archive: ~1-3 MB per layer
 *
 * When a .pmtiles file isn't present (tippecanoe hasn't been run), we
 * fall back to fetching the bundled GeoJSON and setData()-ing it into a
 * GeoJSON source. The dashboard code paths stay the same — only the
 * source type/URL changes.
 */

export interface InfraLayerConfig {
  /** Stable id used for MapLibre source name */
  sourceId: string
  /** Vector tile layer name inside the PMTiles archive (matches --layer= in gen-pmtiles.sh) */
  pmtilesLayerName: string
  /** Relative URL of the .pmtiles file */
  pmtilesUrl: string
  /** Fallback GeoJSON URL (bundled static file) */
  geojsonUrl: string
  /** Human-readable debug label */
  label: string
  /** Skip raw GeoJSON fallback when it would load too much data into the UI thread. */
  maxGeojsonFallbackBytes?: number
  /** Never load the raw GeoJSON fallback in the browser for this source. */
  skipGeojsonFallback?: boolean
}

const MB = 1024 * 1024

export const INFRA_LAYERS: Record<string, InfraLayerConfig> = {
  substations: {
    sourceId: "crep-substations",
    pmtilesLayerName: "substations",
    pmtilesUrl: "/data/crep/tiles/substations-us.pmtiles",
    geojsonUrl: "/data/crep/substations-us.geojson",
    label: "US substations (HIFLD)",
  },
  transmissionLines: {
    // sourceId distinct from the existing "crep-txlines" geojson source
    // used by the renderTxLines path — CREPDashboardClient wires BOTH so
    // world-view paints via PMTiles (pre-clustered by tippecanoe) while
    // the zoom-4+ geojson path keeps voltage-granular routing.
    sourceId: "crep-txlines-global",
    pmtilesLayerName: "transmission_lines",
    // Route through /api/crep/tiles/* for consistency with cell towers
    // and as a safety net against any future Next.js static-handler
    // oddities on large PMTiles files.
    pmtilesUrl: "/api/crep/tiles/transmission-lines-us-major.pmtiles",
    geojsonUrl: "/data/crep/transmission-lines-us-major.geojson",
    label: "US transmission lines (HIFLD ≥345 kV)",
  },
  /**
   * FULL US transmission (Apr 19, 2026, Morgan: "every single asset
   * from opengridworks needs to be hardcoded"). Includes 69/115/138/
   * 230 kV local feeders missing from the ≥345 kV backbone file — e.g.
   * SDG&E Jamacha, Miguel, Suncrest branch lines. Generated by
   * scripts/etl/crep/fetch-transmission-full.mjs from HIFLD + OSM +
   * MINDEX, then tiled via gen-transmission-pmtiles.sh.
   * Loader prefers this over transmissionLines when present.
   */
  transmissionFull: {
    sourceId: "crep-txlines-full",
    pmtilesLayerName: "transmission_lines",
    pmtilesUrl: "/api/crep/tiles/transmission-lines-us-full.pmtiles",
    geojsonUrl: "/data/crep/transmission-lines-us-full.geojson",
    label: "US transmission — ALL voltages (HIFLD + OSM + MINDEX)",
    maxGeojsonFallbackBytes: 24 * MB,
    // If the full PMTiles archive is missing or stubbed, loading the raw
    // all-voltage GeoJSON can freeze Earth Simulator controls during zoom.
    skipGeojsonFallback: true,
  },
  /**
   * Global data centers (Apr 19, 2026, Morgan: "square glowing data
   * centers seen on opengridworks needs to be added to crep in full
   * globally"). OSM man_made=data_center + PeeringDB facilities +
   * MINDEX. Typically 5–7k features globally. Replaces the 44-entry
   * MAJOR_DATACENTERS static bundle as the primary visual source.
   */
  dataCentersGlobal: {
    sourceId: "crep-datacenters-global",
    pmtilesLayerName: "data_centers",
    pmtilesUrl: "/api/crep/tiles/data-centers-global.pmtiles",
    geojsonUrl: "/data/crep/data-centers-global.geojson",
    label: "Global data centers (OSM + PeeringDB + MINDEX)",
  },
  powerPlantsGlobal: {
    sourceId: "crep-plants-global",
    pmtilesLayerName: "power_plants",
    pmtilesUrl: "/data/crep/tiles/power-plants-global.pmtiles",
    geojsonUrl: "/data/crep/power-plants-global.geojson",
    label: "Global power plants (WRI)",
  },
  cellTowersGlobal: {
    sourceId: "crep-celltowers-global",
    pmtilesLayerName: "cell_towers",
    // Apr 19, 2026: the 41 MB cell-towers-global.pmtiles 404s from the
    // default Next.js static handler on prod (other <20 MB pmtiles in the
    // same directory serve fine — exact cause unknown, likely a size
    // threshold in Next.js standalone runtime). Route it through our
    // explicit fs-streaming API route instead. The route still serves
    // the smaller tiles too, so we use it uniformly.
    pmtilesUrl: "/api/crep/tiles/cell-towers-global.pmtiles",
    // Fallback: the full cell-towers-global.geojson (MINDEX+OpenCelliD+OSM)
    // when the PMTiles archive hasn't been generated yet. If THAT file is
    // also missing, CREP falls back to the bundled 192-feature US set.
    geojsonUrl: "/data/crep/cell-towers-global.geojson",
    label: "Global cell towers (MINDEX + OpenCelliD + OSM)",
    maxGeojsonFallbackBytes: 24 * MB,
    skipGeojsonFallback: true,
  },
  /** Taiwan + US + territories — small bundled GeoJSON for instant paint (see fetch-celltowers-global.mjs). */
  cellTowersUsTwInstant: {
    sourceId: "crep-celltowers-us-tw-instant",
    pmtilesLayerName: "cell_towers",
    pmtilesUrl: "/api/crep/tiles/cell-towers-us-tw-instant.pmtiles",
    geojsonUrl: "/data/crep/cell-towers-us-tw-instant.geojson",
    label: "US + Taiwan cell towers (instant bundle)",
  },
}

/**
 * Apr 23, 2026 — Morgan: "scale up fast now with aws compute/gpu/extra vms".
 * When Cursor's AWS MVT tile pipeline is live (see
 * docs/CURSOR_AWS_MVT_TILE_PIPELINE.md), each layer's .pmtiles archive is
 * baked nightly on 249 (or AWS g6.xlarge spot) and parked on Cloudflare R2
 * at https://tiles.mycosoft.com. The CDN has zero egress cost and sits on
 * every Cloudflare edge POP — pulling tiles from there is ~10 ms instead
 * of ~500 ms through our origin `/api/crep/tiles/*` route.
 *
 * Set `NEXT_PUBLIC_TILES_CDN_ENABLED=true` plus
 * `NEXT_PUBLIC_TILES_CDN=https://tiles.mycosoft.com` (or a preview CDN) and
 * we rewrite the PMTiles URLs to the CDN. If CDN use is not explicitly enabled,
 * we use the existing app-served path, which in turn falls back to GeoJSON when
 * the pmtiles archive isn't published yet. This avoids broken CDN probes from
 * adding 404 noise to the live Earth Simulator.
 *
 * Naming convention on the CDN (matches scripts/bake_mvt_tiles.sh output):
 *   substations.pmtiles
 *   transmission-major.pmtiles    (≥345 kV backbone)
 *   transmission-full.pmtiles     (all voltages)
 *   data-centers.pmtiles
 *   power-plants.pmtiles
 *   cell-towers.pmtiles           (global)
 *   cell-towers-us-tw.pmtiles     (instant bundle)
 */
function resolvePmtilesUrl(appPath: string): string {
  const cdnEnabled =
    (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_TILES_CDN_ENABLED)?.trim().toLowerCase() === "true"
  if (!cdnEnabled) return appPath

  const cdn = (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_TILES_CDN)?.trim()
  if (!cdn) return appPath
  // Pull the filename off the app path and serve it from the CDN root.
  // Handles both /data/crep/tiles/foo.pmtiles and /api/crep/tiles/foo.pmtiles.
  const fname = appPath.split("/").pop() || appPath
  // Map old verbose filenames to the canonical CDN names the bake script
  // produces. Unmapped → use the filename as-is (zero-config new layers).
  const canonical: Record<string, string> = {
    "substations-us.pmtiles": "substations.pmtiles",
    "transmission-lines-us-major.pmtiles": "transmission-major.pmtiles",
    "transmission-lines-us-full.pmtiles": "transmission-full.pmtiles",
    "data-centers-global.pmtiles": "data-centers.pmtiles",
    "power-plants-global.pmtiles": "power-plants.pmtiles",
    "cell-towers-global.pmtiles": "cell-towers.pmtiles",
    "cell-towers-us-tw-instant.pmtiles": "cell-towers-us-tw.pmtiles",
  }
  const mapped = canonical[fname] || fname
  return `${cdn.replace(/\/$/, "")}/${mapped}`
}

/**
 * Probe whether a .pmtiles file is reachable (HEAD request).
 * 15-second in-memory memoization so we don't re-probe on every source add.
 */
const pmtilesProbeCache = new Map<string, { ts: number; available: boolean }>()
const PROBE_TTL_MS = 15_000

export async function isPMTilesAvailable(url: string): Promise<boolean> {
  const cached = pmtilesProbeCache.get(url)
  if (cached && Date.now() - cached.ts < PROBE_TTL_MS) return cached.available
  let controller: AbortController | null = null
  try {
    controller = typeof AbortController === "function" ? new AbortController() : null
  } catch {
    controller = null
  }
  const timeout = controller
    ? globalThis.setTimeout(() => controller.abort(), 10_000)
    : null
  try {
    // Apr 21, 2026 (Morgan OOM audit): HEAD on the Next.js dev static
    // handler returns 200 but omits `content-type` for .pmtiles files,
    // so the old `content-type.length > 0` guard always failed locally
    // → we'd fall back to the 78 MB raw GeoJSON every single time. Fix:
    // accept any 200/206 (partial) response. Also use a small Range
    // GET to verify the file has bytes (protects against the rare case
    // where the handler 200s an empty stream).
    const res = await fetch(url, {
      method: "GET",
      headers: { Range: "bytes=0-1023" },
      ...(controller ? { signal: controller.signal } : {}),
    })
    const totalBytes = parseContentTotalBytes(res.headers)
    const ok =
      (res.ok || res.status === 206) &&
      (res.headers.get("content-length") !== "0") &&
      // A real infra PMTiles archive is never a tiny JSON/error stub. Live
      // once served transmission-lines-us-full.pmtiles as 134 bytes with a
      // 206 status; MapLibre accepted the source and then rendered nothing.
      (totalBytes == null || totalBytes >= 4096)
    pmtilesProbeCache.set(url, { ts: Date.now(), available: ok })
    return ok
  } catch {
    pmtilesProbeCache.set(url, { ts: Date.now(), available: false })
    return false
  } finally {
    if (timeout != null) globalThis.clearTimeout(timeout)
  }
}

function parseContentTotalBytes(headers: Headers): number | null {
  const contentRange = headers.get("content-range")
  const totalFromRange = contentRange?.match(/\/(\d+)$/)?.[1]
  if (totalFromRange) {
    const parsed = Number(totalFromRange)
    if (Number.isFinite(parsed)) return parsed
  }
  const length = Number(headers.get("content-length") || "")
  return Number.isFinite(length) && length > 0 ? length : null
}

async function isGeojsonFallbackAllowed(cfg: InfraLayerConfig): Promise<boolean> {
  if (cfg.skipGeojsonFallback) {
    console.warn(`[CREP/Infra] ${cfg.label}: GeoJSON fallback disabled to protect map controls`)
    return false
  }
  if (!cfg.maxGeojsonFallbackBytes) return true
  try {
    const res = await fetch(cfg.geojsonUrl, {
      method: "GET",
      headers: { Range: "bytes=0-0" },
      cache: "force-cache",
    })
    const totalBytes = parseContentTotalBytes(res.headers)
    if (totalBytes == null || totalBytes <= 1) {
      console.warn(`[CREP/Infra] ${cfg.label}: GeoJSON fallback size unknown; skipping capped fallback`)
      return false
    }
    if (totalBytes != null && totalBytes > cfg.maxGeojsonFallbackBytes) {
      console.warn(
        `[CREP/Infra] ${cfg.label}: GeoJSON fallback skipped (${Math.round(totalBytes / MB)}MB exceeds ${Math.round(cfg.maxGeojsonFallbackBytes / MB)}MB UI-thread budget)`,
      )
      return false
    }
  } catch {
    console.warn(`[CREP/Infra] ${cfg.label}: GeoJSON fallback size probe failed; skipping capped fallback`)
    return false
  }
  return true
}

/**
 * Add the given layer to a MapLibre map using PMTiles if available, or
 * GeoJSON as fallback. Returns metadata including which path was used.
 */
export async function addInfraSourceWithFallback(
  map: any,
  cfg: InfraLayerConfig,
  opts?: { forceGeoJSON?: boolean },
): Promise<{ mode: "pmtiles" | "geojson" | "skipped"; sourceId: string }> {
  if (!map || typeof map.getSource !== "function") {
    return { mode: "skipped", sourceId: cfg.sourceId }
  }
  // Already present?
  if (map.getSource(cfg.sourceId)) {
    return { mode: "skipped", sourceId: cfg.sourceId }
  }

  // Prefer PMTiles when the archive is published. If the
  // NEXT_PUBLIC_TILES_CDN env is set (Cloudflare R2 edge), fetch directly
  // from the CDN — zero origin cost and ~10 ms edge latency vs ~500 ms
  // through /api/crep/tiles/*. The client pmtiles library handles HTTP
  // range requests natively.
  const pmtilesUrl = resolvePmtilesUrl(cfg.pmtilesUrl)
  if (!opts?.forceGeoJSON) {
    const absoluteUrl = /^https?:\/\//.test(pmtilesUrl)
      ? pmtilesUrl
      : new URL(pmtilesUrl, window.location.origin).toString()
    try {
      if (await isPMTilesAvailable(absoluteUrl)) {
        try {
          map.addSource(cfg.sourceId, {
            type: "vector",
            url: `pmtiles://${absoluteUrl}`,
          })
        } catch (e: any) {
          if (String(e?.message || e).includes("already exists")) {
            return { mode: "skipped", sourceId: cfg.sourceId }
          }
          throw e
        }
        console.log(`[CREP/Infra] ${cfg.label}: PMTiles source added (${/^https?:\/\//.test(pmtilesUrl) ? "CDN" : "origin"})`)
        return { mode: "pmtiles", sourceId: cfg.sourceId }
      }
      console.warn(`[CREP/Infra] ${cfg.label}: PMTiles probe failed, trying GeoJSON fallback`)
    } catch (e: any) {
      console.warn(`[CREP/Infra] ${cfg.label}: PMTiles source add failed, trying GeoJSON fallback:`, e?.message)
    }
  }

  // Fallback: fetch the GeoJSON and register as a geojson source
  try {
    if (!(await isGeojsonFallbackAllowed(cfg))) {
      return { mode: "skipped", sourceId: cfg.sourceId }
    }
    const res = await fetch(cfg.geojsonUrl, { cache: "force-cache" })
    if (!res.ok) throw new Error(`${cfg.geojsonUrl} → HTTP ${res.status}`)
    const fc = await res.json()
    try {
      map.addSource(cfg.sourceId, { type: "geojson", data: fc })
    } catch (e: any) {
      if (String(e?.message || e).includes("already exists")) {
        return { mode: "skipped", sourceId: cfg.sourceId }
      }
      throw e
    }
    console.log(`[CREP/Infra] ${cfg.label}: GeoJSON fallback added (${fc?.features?.length ?? 0} features)`)
    return { mode: "geojson", sourceId: cfg.sourceId }
  } catch (e: any) {
    console.warn(`[CREP/Infra] ${cfg.label}: source add failed:`, e?.message)
    return { mode: "skipped", sourceId: cfg.sourceId }
  }
}

/**
 * Extract the right `source-layer` property name given the mode. Callers
 * use this when adding the render layer — PMTiles needs `source-layer`,
 * GeoJSON does not.
 */
export function layerSpecForMode(
  mode: "pmtiles" | "geojson" | "skipped",
  cfg: InfraLayerConfig,
): { sourceLayer?: string } {
  if (mode === "pmtiles") return { sourceLayer: cfg.pmtilesLayerName }
  return {}
}
