/**
 * Static Infrastructure Loader — PMTiles-first, GeoJSON-fallback (Fix C)
 *
 * Generated PMTiles (public/data/crep/tiles/*.pmtiles) are massively
 * cheaper to load and render than the raw GeoJSON files:
 *   • MapLibre only materialises features in the current viewport tile
 *   • HTTP range-requested — no full 12-16 MB download per layer
 *   • Typical compressed PMTiles archive: ~1-3 MB per layer
 *
 * When a .pmtiles file isn't present (tippecanoe hasn't been run), we
 * fall back to fetching the bundled GeoJSON and setData()-ing it into a
 * GeoJSON source. The dashboard code paths stay the same — only the
 * source type/URL changes.
 */

export interface InfraLayerConfig {
  /** Stable id used for MapLibre source name */
  sourceId: string
  /** Vector tile layer name inside the PMTiles archive (matches --layer= in gen-pmtiles.sh) */
  pmtilesLayerName: string
  /** Relative URL of the .pmtiles file */
  pmtilesUrl: string
  /** Fallback GeoJSON URL (bundled static file) */
  geojsonUrl: string
  /** Human-readable debug label */
  label: string
}

export const INFRA_LAYERS: Record<string, InfraLayerConfig> = {
  substations: {
    sourceId: "crep-substations",
    pmtilesLayerName: "substations",
    pmtilesUrl: "/data/crep/tiles/substations-us.pmtiles",
    geojsonUrl: "/data/crep/substations-us.geojson",
    label: "US substations (HIFLD)",
  },
  transmissionLines: {
    // sourceId distinct from the existing "crep-txlines" geojson source
    // used by the renderTxLines path — CREPDashboardClient wires BOTH so
    // world-view paints via PMTiles (pre-clustered by tippecanoe) while
    // the zoom-4+ geojson path keeps voltage-granular routing.
    sourceId: "crep-txlines-global",
    pmtilesLayerName: "transmission_lines",
    // Route through /api/crep/tiles/* for consistency with cell towers
    // and as a safety net against any future Next.js static-handler
    // oddities on large PMTiles files.
    pmtilesUrl: "/api/crep/tiles/transmission-lines-us-major.pmtiles",
    geojsonUrl: "/data/crep/transmission-lines-us-major.geojson",
    label: "US transmission lines (HIFLD ≥345 kV)",
  },
  /**
   * FULL US transmission (Apr 19, 2026, Morgan: "every single asset
   * from opengridworks needs to be hardcoded"). Includes 69/115/138/
   * 230 kV local feeders missing from the ≥345 kV backbone file — e.g.
   * SDG&E Jamacha, Miguel, Suncrest branch lines. Generated by
   * scripts/etl/crep/fetch-transmission-full.mjs from HIFLD + OSM +
   * MINDEX, then tiled via gen-transmission-pmtiles.sh.
   * Loader prefers this over transmissionLines when present.
   */
  transmissionFull: {
    sourceId: "crep-txlines-full",
    pmtilesLayerName: "transmission_lines",
    pmtilesUrl: "/api/crep/tiles/transmission-lines-us-full.pmtiles",
    geojsonUrl: "/data/crep/transmission-lines-us-full.geojson",
    label: "US transmission — ALL voltages (HIFLD + OSM + MINDEX)",
  },
  /**
   * Global data centers (Apr 19, 2026, Morgan: "square glowing data
   * centers seen on opengridworks needs to be added to crep in full
   * globally"). OSM man_made=data_center + PeeringDB facilities +
   * MINDEX. Typically 5–7k features globally. Replaces the 44-entry
   * MAJOR_DATACENTERS static bundle as the primary visual source.
   */
  dataCentersGlobal: {
    sourceId: "crep-datacenters-global",
    pmtilesLayerName: "data_centers",
    pmtilesUrl: "/api/crep/tiles/data-centers-global.pmtiles",
    geojsonUrl: "/data/crep/data-centers-global.geojson",
    label: "Global data centers (OSM + PeeringDB + MINDEX)",
  },
  powerPlantsGlobal: {
    sourceId: "crep-plants-global",
    pmtilesLayerName: "power_plants",
    pmtilesUrl: "/data/crep/tiles/power-plants-global.pmtiles",
    geojsonUrl: "/data/crep/power-plants-global.geojson",
    label: "Global power plants (WRI)",
  },
  cellTowersGlobal: {
    sourceId: "crep-celltowers-global",
    pmtilesLayerName: "cell_towers",
    // Apr 19, 2026: the 41 MB cell-towers-global.pmtiles 404s from the
    // default Next.js static handler on prod (other <20 MB pmtiles in the
    // same directory serve fine — exact cause unknown, likely a size
    // threshold in Next.js standalone runtime). Route it through our
    // explicit fs-streaming API route instead. The route still serves
    // the smaller tiles too, so we use it uniformly.
    pmtilesUrl: "/api/crep/tiles/cell-towers-global.pmtiles",
    // Fallback: the full cell-towers-global.geojson (MINDEX+OpenCelliD+OSM)
    // when the PMTiles archive hasn't been generated yet. If THAT file is
    // also missing, CREP falls back to the bundled 192-feature US set.
    geojsonUrl: "/data/crep/cell-towers-global.geojson",
    label: "Global cell towers (MINDEX + OpenCelliD + OSM)",
  },
  /** Taiwan + US + territories — small bundled GeoJSON for instant paint (see fetch-celltowers-global.mjs). */
  cellTowersUsTwInstant: {
    sourceId: "crep-celltowers-us-tw-instant",
    pmtilesLayerName: "cell_towers",
    pmtilesUrl: "/api/crep/tiles/cell-towers-us-tw-instant.pmtiles",
    geojsonUrl: "/data/crep/cell-towers-us-tw-instant.geojson",
    label: "US + Taiwan cell towers (instant bundle)",
  },
}

/**
 * Probe whether a .pmtiles file is reachable (HEAD request).
 * 15-second in-memory memoization so we don't re-probe on every source add.
 */
const pmtilesProbeCache = new Map<string, { ts: number; available: boolean }>()
const PROBE_TTL_MS = 15_000

export async function isPMTilesAvailable(url: string): Promise<boolean> {
  const cached = pmtilesProbeCache.get(url)
  if (cached && Date.now() - cached.ts < PROBE_TTL_MS) return cached.available
  try {
    // Apr 21, 2026 (Morgan OOM audit): HEAD on the Next.js dev static
    // handler returns 200 but omits `content-type` for .pmtiles files,
    // so the old `content-type.length > 0` guard always failed locally
    // → we'd fall back to the 78 MB raw GeoJSON every single time. Fix:
    // accept any 200/206 (partial) response. Also use a small Range
    // GET to verify the file has bytes (protects against the rare case
    // where the handler 200s an empty stream).
    const res = await fetch(url, { method: "GET", headers: { Range: "bytes=0-1023" }, signal: AbortSignal.timeout(3000) })
    const ok = (res.ok || res.status === 206) && (res.headers.get("content-length") !== "0")
    pmtilesProbeCache.set(url, { ts: Date.now(), available: ok })
    return ok
  } catch {
    pmtilesProbeCache.set(url, { ts: Date.now(), available: false })
    return false
  }
}

/**
 * Add the given layer to a MapLibre map using PMTiles if available, or
 * GeoJSON as fallback. Returns metadata including which path was used.
 */
export async function addInfraSourceWithFallback(
  map: any,
  cfg: InfraLayerConfig,
  opts?: { forceGeoJSON?: boolean },
): Promise<{ mode: "pmtiles" | "geojson" | "skipped"; sourceId: string }> {
  if (!map || typeof map.getSource !== "function") {
    return { mode: "skipped", sourceId: cfg.sourceId }
  }
  // Already present?
  if (map.getSource(cfg.sourceId)) {
    return { mode: "skipped", sourceId: cfg.sourceId }
  }

  // Prefer PMTiles when the archive is published
  if (!opts?.forceGeoJSON && (await isPMTilesAvailable(cfg.pmtilesUrl))) {
    map.addSource(cfg.sourceId, {
      type: "vector",
      url: `pmtiles://${new URL(cfg.pmtilesUrl, window.location.origin).toString()}`,
    })
    console.log(`[CREP/Infra] ${cfg.label}: PMTiles source added`)
    return { mode: "pmtiles", sourceId: cfg.sourceId }
  }

  // Fallback: fetch the GeoJSON and register as a geojson source
  try {
    const res = await fetch(cfg.geojsonUrl, { cache: "force-cache" })
    if (!res.ok) throw new Error(`${cfg.geojsonUrl} → HTTP ${res.status}`)
    const fc = await res.json()
    map.addSource(cfg.sourceId, { type: "geojson", data: fc })
    console.log(`[CREP/Infra] ${cfg.label}: GeoJSON fallback added (${fc?.features?.length ?? 0} features)`)
    return { mode: "geojson", sourceId: cfg.sourceId }
  } catch (e: any) {
    console.warn(`[CREP/Infra] ${cfg.label}: source add failed:`, e?.message)
    return { mode: "skipped", sourceId: cfg.sourceId }
  }
}

/**
 * Extract the right `source-layer` property name given the mode. Callers
 * use this when adding the render layer — PMTiles needs `source-layer`,
 * GeoJSON does not.
 */
export function layerSpecForMode(
  mode: "pmtiles" | "geojson" | "skipped",
  cfg: InfraLayerConfig,
): { sourceLayer?: string } {
  if (mode === "pmtiles") return { sourceLayer: cfg.pmtilesLayerName }
  return {}
}
