import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const route = await readFile(new URL("../../../../app/api/fusarium/sensing-telemetry/route.ts", import.meta.url), "utf8")
const mycoBrainSensorsRoute = await readFile(new URL("../../../../app/api/mycobrain/[port]/sensors/route.ts", import.meta.url), "utf8")
const mycoBrainInventoryRoute = await readFile(new URL("../../../../app/api/mycobrain/route.ts", import.meta.url), "utf8")
const mycoBrainDeviceListRoute = await readFile(new URL("../../../../app/api/mycobrain/devices/route.ts", import.meta.url), "utf8")
const mindexSamplesRoute = await readFile(new URL("../../../../app/api/mindex/telemetry/samples/route.ts", import.meta.url), "utf8")
const deviceCapabilitiesRoute = await readFile(new URL("../../../../app/api/fusarium/device-capabilities/route.ts", import.meta.url), "utf8")
const networkInventoryRoute = await readFile(new URL("../../../../app/api/devices/network/route.ts", import.meta.url), "utf8")

test("route is GET-only, bounded, same-origin, no-store, and owner-gates all aggregation", () => {
  assert.match(route, /export async function GET/)
  assert.doesNotMatch(route, /export async function (?:POST|PUT|PATCH|DELETE)/)
  assert.match(route, /new URL\(sourceRef, origin\)/)
  assert.match(route, /method: "GET"/)
  assert.match(route, /AbortSignal\.timeout\(timeoutMs\)/)
  assert.match(route, /passiveReadTimeoutMs/)
  assert.match(route, /\/api\/mycobrain\/devices["']\) return 8_000/)
  assert.match(route, /startsWith\(["']\/api\/mycobrain\?["']\)\) return 18_000/)
  assert.match(route, /cache_only=1\$.*return 6_000/s)
  assert.match(route, /live_selected=1\$.*return 18_000/s)
  assert.match(route, /\/api\/mindex\/telemetry\/samples\?.*return 16_000/s)
  assert.match(route, /network.*telemetry.*test\(sourceRef\)\) return 22_000/s)
  assert.match(route, /isSharedMdpIdentityToken\(selectedDeviceId\)/)
  assert.match(route, /deploymentByCatalogId\(selectedDeviceId\).*deploymentByRegistryId\(selectedDeviceId\)/s)
  assert.match(route, /readDeviceIds\.push\(deployment\.registry_id\)/)
  assert.match(route, /mdpIsUnique.*readDeviceIds\.push\(deployment\.mdp_device_id\)/s)
  assert.match(route, /liveReadDeviceIds\.push\(mdpIsUnique \? deployment\.mdp_device_id : deployment\.registry_id\)/)
  const unknownIdentityBranch = route.slice(route.indexOf("if (!deployment)"), route.indexOf("continue", route.indexOf("if (!deployment)")))
  assert.doesNotMatch(unknownIdentityBranch, /liveReadDeviceIds/)
  assert.match(route, /searchParams\.get\("live"\) === "1"/)
  const ownerGate = route.indexOf("const auth = await requireOwner()")
  const fanout = route.lastIndexOf("collectSameOriginSensingTelemetry(")
  assert.ok(ownerGate > -1 && fanout > ownerGate)
  assert.match(route, /const auth = await requireOwner\(\)[\s\S]*if \(auth\.error\) return auth\.error[\s\S]*const origin = request\.nextUrl\.origin/)
  assert.match(route, /liveReadDeviceIds: liveSelectedRead \? identityEvidence\.liveReadDeviceIds : \[\]/)
  assert.match(route, /Cache-Control.*no-store/s)
  assert.match(route, /request\.headers\.get\("cookie"\)/)
  assert.match(route, /request\.headers\.get\("authorization"\)/)
  assert.doesNotMatch(route, /ownerContextSources/)
  assert.doesNotMatch(route, /process\.env|X-API-Key|command|stimulate|write/)
  assert.doesNotMatch(route, /searchParams\.get\([^)]*(?:url|source|endpoint)/i)
  assert.doesNotMatch(route, /response\.status === 404 \? "empty"/)
  assert.match(route, /if \(!response\.ok\) return \{ sourceRef, state: "unavailable"/)
})

test("MycoBrain cache-only read exits before any discovery or hardware command and exposes no raw serial response", () => {
  const cacheFlag = mycoBrainSensorsRoute.indexOf('searchParams.get("cache_only") === "1"')
  const cacheBranch = mycoBrainSensorsRoute.indexOf("\n  if (cacheOnlyRead) {", cacheFlag)
  const deviceDiscovery = mycoBrainSensorsRoute.indexOf('fetch(`${MYCOBRAIN_SERVICE_URL}/devices`')
  const commandPath = mycoBrainSensorsRoute.indexOf('cmd: "read_sensors"')
  assert.ok(cacheFlag > -1 && cacheBranch > cacheFlag)
  assert.ok(deviceDiscovery > cacheBranch)
  assert.ok(commandPath > cacheBranch)
  const branchSource = mycoBrainSensorsRoute.slice(cacheBranch, mycoBrainSensorsRoute.indexOf("\n\n  try {", cacheBranch))
  assert.match(branchSource, /reason: "not_cached"/)
  assert.doesNotMatch(branchSource, /fetch\(|read_sensors|cmd: "status"|raw_response/)
  assert.match(mycoBrainSensorsRoute, /error: "Failed to fetch sensor data"[\s\S]*\{ status: 503 \}/)
})

test("every MycoBrain sensor response requires owner auth and live-selected reads reuse a fifteen-second device cooldown", () => {
  assert.match(mycoBrainSensorsRoute, /const cacheOnlyRead = request\.nextUrl\.searchParams\.get\("cache_only"\) === "1"/)
  assert.match(mycoBrainSensorsRoute, /searchParams\.get\("live_selected"\) === "1"/)
  assert.match(mycoBrainSensorsRoute, /const auth = await requireOwner\(\)[\s\S]*if \(auth\.error\) return auth\.error[\s\S]*const \{ port \} = await params/)
  assert.match(mycoBrainSensorsRoute, /FUSARIUM_LIVE_READ_COOLDOWN_MS = 15_000/)
  assert.match(mycoBrainSensorsRoute, /cacheTtlMs = liveSelectedRead \? FUSARIUM_LIVE_READ_COOLDOWN_MS : SENSOR_CACHE_TTL_MS/)
  assert.match(mycoBrainSensorsRoute, /const existing = inFlight\.get\(cacheKey\)/)
})

test("Device Manager MINDEX history uses the implemented read namespace, credential retry, and bounded rows", () => {
  assert.match(mindexSamplesRoute, /\/api\/mindex\/telemetry\/samples\?device_slug=/)
  assert.doesNotMatch(mindexSamplesRoute, /\/api\/telemetry\/samples\?device_slug=/)
  assert.match(mindexSamplesRoute, /fetchMindexWithAuthRetry/)
  assert.match(mindexSamplesRoute, /mindexUpstreamHeaders/)
  assert.match(mindexSamplesRoute, /Math\.min\(512, Math\.max\(1, requestedLimit\)\)/)
  assert.match(mindexSamplesRoute, /const auth = await requireOwner\(\)[\s\S]*if \(auth\.error\) return auth\.error/)
  assert.doesNotMatch(mindexSamplesRoute, /details:\s*text|await res\.text\(\)/)
  assert.doesNotMatch(mindexSamplesRoute, /export async function (?:POST|PUT|PATCH|DELETE)/)
})

test("device capability aggregation is owner-only and forwards only the current same-origin session", () => {
  assert.match(deviceCapabilitiesRoute, /const auth = await requireOwner\(\)[\s\S]*if \(auth\.error\) return auth\.error/)
  assert.match(deviceCapabilitiesRoute, /request\.headers\.get\("cookie"\)/)
  assert.match(deviceCapabilitiesRoute, /request\.headers\.get\("authorization"\)/)
  assert.doesNotMatch(deviceCapabilitiesRoute, /process\.env|export async function (?:POST|PUT|PATCH|DELETE)/)
})

test("MycoBrain inventory owner-gates before probes and verifies fixed-host identity only against the expected physical board id", () => {
  const ownerGate = mycoBrainInventoryRoute.indexOf("const auth = await requireOwner()")
  const firstProbe = mycoBrainInventoryRoute.indexOf("await fetch(`${MYCOBRAIN_SERVICE_URL}/health`")
  assert.ok(ownerGate >= 0 && firstProbe > ownerGate)
  assert.match(mycoBrainInventoryRoute, /reportedDeviceId === deployment\.mdp_device_id/)
  assert.match(mycoBrainInventoryRoute, /fetchOperatorDevices\(selectedRegistryId\)/)
  assert.match(mycoBrainInventoryRoute, /deploymentByRegistryId\(selectedRegistryId\)/)
  assert.match(mycoBrainInventoryRoute, /verified:\s*d\.verified === true/)
  assert.match(mycoBrainInventoryRoute, /deploymentByHost\(host\)/)
  assert.match(mycoBrainInventoryRoute, /deviceId = deployment\?\.registry_id/)
  assert.match(mycoBrainInventoryRoute, /reported_device_id: reportedDeviceId/)
})

test("passive MycoBrain device list owner-gates before cache or service access and withholds topology", () => {
  const ownerGate = mycoBrainDeviceListRoute.indexOf("const auth = await requireOwner()")
  const cacheRead = mycoBrainDeviceListRoute.indexOf("if (!forceRefresh && deviceCache")
  const serviceRead = mycoBrainDeviceListRoute.indexOf("await fetch(`${MYCOBRAIN_SERVICE_URL}/devices`")
  assert.ok(ownerGate >= 0 && cacheRead > ownerGate && serviceRead > ownerGate)
  assert.doesNotMatch(mycoBrainDeviceListRoute, /serviceUrl:/)
})

test("network inventory is declaration-only unless an owner explicitly requests live probes", () => {
  assert.match(networkInventoryRoute, /searchParams\.get\("probe_live"\) === "true"/)
  assert.match(networkInventoryRoute, /if \(probeLive\)[\s\S]*requireOwner\(\)/)
  assert.match(networkInventoryRoute, /probeLive \? await probeAllOperatorAgents\(\) : \[\]/)
  assert.match(networkInventoryRoute, /buildFieldAndOperatorDevices\(probeLive \? undefined : \[\]\)/)
  assert.match(networkInventoryRoute, /probeLive \? "field-config\+operator-http" : "field-config"/)
  assert.match(networkInventoryRoute, /showing declared field deployments without LAN probes/)
})
