// ═══════════════════════════════════════════════════════════════════════════
// NIST SP 800-171 / CMMC L2 — Mycosoft posture (authoritative overlay)
// ═══════════════════════════════════════════════════════════════════════════
//
// Source of truth: `mycosoft-posture-overlay-v1.json`, generated by Perplexity
// from the CMMC contracting workspace (return handoff 2026-07-10). Each of the
// 110 controls carries BOTH a `current_state` and a `target_state`:
//
//   • current_state (as of 2026-07-10): 108 `planned`, 2 `partial`. SPRS -234.
//     Nothing is implemented yet — PreVeil not purchased, zero evidence. This is
//     the HONEST posture and the default the UI shows.
//   • target_state (as of 2026-07-17, end of the 5-day self-assessment sprint):
//     109 `implemented`, 1 `planned` (AU.L2-3.3.4, on POA&M, close 2026-08-31).
//     SPRS +109. This is a PROJECTION and must always be labeled as such.
//
// IMPORTANT — never present target_state as achieved posture. The public Trust
// Center is gated behind `NEXT_PUBLIC_COMPLIANCE_PUBLIC_MODE` (default
// `in_progress`) and must not publish a numeric SPRS score until it is actually
// posted on 2026-07-17.

import overlayJson from './mycosoft-posture-overlay-v1.json';

export type ImplementationState = 'implemented' | 'partial' | 'planned' | 'not_applicable';
export type PostureStatus = 'compliant' | 'partial' | 'non_compliant' | 'not_applicable';
export type PostureMode = 'current' | 'target';
/** Public Trust Center display mode. */
export type CompliancePublicMode = 'hidden' | 'in_progress' | 'posted';

export interface OverlayControlState {
  as_of: string;
  implementation_state: ImplementationState;
  evidence_uri: string | null;
  notes: string;
  sprint_day?: number;
}

export interface OverlayControl {
  control_id: string; // CMMC form, e.g. "AC.L2-3.1.1"
  framework: string;
  cmmc_level: string;
  family: string;
  family_name: string;
  weight: number;
  poam_eligible: boolean;
  title: string;
  current_state: OverlayControlState;
  target_state: OverlayControlState;
  poam_open_after_sprint: boolean;
}

export interface PostureOverlay {
  generated_at: string;
  framework: string;
  cmmc_level: string;
  assessment_type: string;
  entity: Record<string, unknown>;
  sprint: {
    kickoff_date: string;
    sprint_days: number;
    target_sprs_submission_date: string;
    phase_1_cutoff: string;
    c3pao_assessment_target: string;
  };
  score: {
    current_as_of_2026_07_10: number;
    target_after_sprint_2026_07_17: number;
    max_possible: number;
    conditional_threshold: number;
  };
  poam_items_open_after_sprint: string[];
  poam_close_deadline: string;
  controls: OverlayControl[];
}

export const POSTURE_OVERLAY = overlayJson as unknown as PostureOverlay;

/** Map the overlay implementation_state enum to a UI compliance status. */
export function mapImplStateToStatus(s: ImplementationState): PostureStatus {
  switch (s) {
    case 'implemented':
      return 'compliant';
    case 'partial':
      return 'partial';
    case 'not_applicable':
      return 'not_applicable';
    case 'planned':
    default:
      // "planned" = not yet implemented → counts as non-compliant so the tile
      // reflects the honest low posture, never a projected one.
      return 'non_compliant';
  }
}

/** NIST 800-171 id ("3.1.1") from a CMMC control id ("AC.L2-3.1.1"). */
export function nistIdFromControlId(controlId: string): string {
  const m = controlId.split('L2-');
  return m.length > 1 ? m[1] : controlId;
}

/** The state object for a control in the requested mode. */
export function stateFor(c: OverlayControl, mode: PostureMode): OverlayControlState {
  return mode === 'target' ? c.target_state : c.current_state;
}

export interface PostureSummary {
  mode: PostureMode;
  asOf: string;
  total: number;
  met: number;
  partial: number;
  notMet: number;
  na: number;
  /** SPRS score for the mode (current can be negative). */
  sprsScore: number;
  maxScore: number;
  conditionalThreshold: number;
  openPoamItems: string[];
  poamCloseDeadline: string;
}

export function postureSummary(mode: PostureMode = 'current'): PostureSummary {
  const controls = POSTURE_OVERLAY.controls;
  let met = 0,
    partial = 0,
    notMet = 0,
    na = 0;
  for (const c of controls) {
    switch (stateFor(c, mode).implementation_state) {
      case 'implemented':
        met++;
        break;
      case 'partial':
        partial++;
        break;
      case 'not_applicable':
        na++;
        break;
      default:
        notMet++;
    }
  }
  return {
    mode,
    asOf: mode === 'target' ? POSTURE_OVERLAY.sprint.target_sprs_submission_date : POSTURE_OVERLAY.generated_at,
    total: controls.length,
    met,
    partial,
    notMet,
    na,
    sprsScore:
      mode === 'target'
        ? POSTURE_OVERLAY.score.target_after_sprint_2026_07_17
        : POSTURE_OVERLAY.score.current_as_of_2026_07_10,
    maxScore: POSTURE_OVERLAY.score.max_possible,
    conditionalThreshold: POSTURE_OVERLAY.score.conditional_threshold,
    openPoamItems: POSTURE_OVERLAY.poam_items_open_after_sprint,
    poamCloseDeadline: POSTURE_OVERLAY.poam_close_deadline,
  };
}

/**
 * Resolve the public Trust Center display mode from env. Defaults to
 * `in_progress` so no numeric SPRS score is published until 2026-07-17.
 */
export function resolvePublicMode(): CompliancePublicMode {
  const v = (process.env.NEXT_PUBLIC_COMPLIANCE_PUBLIC_MODE || '').toLowerCase();
  if (v === 'hidden' || v === 'posted') return v;
  return 'in_progress';
}
