'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,atlas=null,token='',tab='atlas',job=null,dataset=null;
const num=v=>v==null?'not measured':Number(v).toLocaleString(undefined,{maximumSignificantDigits:5});
const dump=v=>`<pre>${esc(JSON.stringify(v,null,2))}</pre>`;
const table=(heads,rows)=>`<div class="scroll"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-ITDX-Token':token},body:JSON.stringify(body)}:{});const v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v;}
const result=()=>state?.result;
function metrics(task){const m=result()[task].metrics,c=m.classifier;return `<div class="grid">${[['Evaluated rows',m.rows],['F1',c.f1],['Brier score',c.brier],['Capture set coverage',m.prediction_sets.capture_coverage]].map(([k,v])=>`<div class="card"><small>${esc(k)}</small><strong class="big">${num(v)}</strong></div>`).join('')}</div><p class="muted">Synthetic held-out captures · ${m.abstentions} abstentions · Probability of the declared class under this model. Source truth and position accuracy are separate.</p>`;}
function tracePlot(traces){const colors=['#78d6a4','#e9c275','#dd8e82'];const paths=Object.values(traces).map((rows,i)=>`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${rows.map(r=>`${30+r.t*9},${260-r.state*80}`).join(' ')}"/>`).join('');return `<svg role="img" aria-label="Toy process state over 80 steps for feedback, memory-reset and disabled-feedback conditions" viewBox="0 0 780 330"><line x1="300" y1="20" x2="300" y2="290" stroke="#9a946d" stroke-dasharray="4 4"/><text x="310" y="26" fill="#b5c9ba" font-size="12">Perturbation at step 30</text>${paths}<text x="30" y="315" fill="#78d6a4" font-size="11">Feedback + memory</text><text x="250" y="315" fill="#e9c275" font-size="11">Memory reset</text><text x="470" y="315" fill="#dd8e82" font-size="11">Feedback disabled</text></svg>`;}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const r=result();let html='';
if(tab==='atlas')html=atlasPage();
else if(tab==='overview')html=`<h2>An atlas of mathematical form and behavior</h2><div class="grid"><article class="card"><h3>Form and dynamics</h3><p>Typed, versioned charts describe states, targets, transitions and candidate invariants. Learned coordinates have a declared context and metric.</p></article><article class="card"><h3>Behavioral evidence</h3><p>Protocols measure goal pursuit, memory, persistence and recovery under perturbation. Controlled comparisons test the value of a behavioral interpretation.</p></article><article class="card"><h3>Cognitive goal scope</h3><p>Levin’s cognitive light cone concerns goals a system can represent and pursue. Sensor reach is an independent property.</p></article></div><h3>Engineering responsibilities</h3>${table(['Component','Role','This reference'],[['NLM','Learn states and dynamics','Two native selective SSM blocks; typed evidence graph'],['FormSpace','Mathematical and behavioral atlas','General forms, symbolic/numeric states, relationships, observations and claims'],['MYCA + AVANI','Navigate goals and govern proposals','Three environmental advisory templates; native AVANI gate; Borda preferences'],['MINDEX','Store atlas, observations and evidence','Local domain-general atlas; production migration pending'],['CREP / Earth Simulator','Render geography and evidence','Native CREP GeoJSON output; local spatial preview'],['Fusarium','Integrated analyst workspace','Local ITDX tab; deployed service binding pending']].map(row=>row.map(esc)))}<div class="notice">Platonic space is the motivating research hypothesis. The registered atlas is extensible; its populated regions and measured capabilities remain explicitly identified.</div>`;
else if(!r)html='<p>No recorded run is available. Run the reference to create evidence.</p>';
else if(tab==='patterns'){html=`<h2>12 · Pattern analysis</h2>${metrics('task12')}<p>Select an observation to inspect the native sensor vector, mathematical coordinates, forecast, target error and evidence references.</p><select id="record">${r.task12.predictions.map((p,i)=>`<option value="${i}">${esc(p.id)}</option>`).join('')}</select><div id="record-detail"></div>`;}
else if(tab==='links')html=`<h2>13 · Typed evidence links</h2>${metrics('task13')}<p>Learned same-environmental-event relations. Displaying the first 80 pairs; all pairs are exported.</p>${table(['Pair','Probability','Prediction set','Status'],r.task13.pairs.slice(0,80).map(p=>[esc(p.a)+'<br>'+esc(p.b),num(p.probability),esc(JSON.stringify(p.prediction_set)),esc(p.status)]))}`;
else if(tab==='options')html=`<h2>8 · Governed environmental advisory options</h2><p>PASS / REVIEW / DENY / PAUSE applies to the declared evidence and action envelope. Borda ranks preferences among passing options; its score is not a success probability.</p>${table(['Option','Gate','Evidence','Execution'],r.task8.options.map(o=>[esc(o.title),esc(o.formspace_gate),esc(o.evidence_refs.length),esc(o.execution)]))}<details><summary>Inspect envelopes, native AVANI decisions and Borda ballots</summary>${dump(r.task8)}</details>`;
else if(tab==='map'){const features=r.task14.geojson.features;const groups=[...new Set(features.map(f=>r.task12.predictions.find(p=>p.id===f.properties.id)?.group).filter(Boolean))];html=`<h2>14 · Evidence on a map</h2><p>Recorded synthetic environmental positions from CREP GeoJSON. This is an offline coordinate preview; Earth Simulator consumes the exported layer.</p><label>Capture <select id="capture">${groups.map(g=>`<option>${esc(g)}</option>`).join('')}</select></label><div id="spatial"></div><p class="notice">Position uncertainty is not estimated. Class probability is not a geographic accuracy radius. Historical captures are not a live feed.</p><details><summary>Projection metrics</summary>${dump(r.task14.metrics)}</details>`;}
else if(tab==='behavior'){const b=state.behavior;html=b?`<h2>Persistent behavior under perturbation</h2><p>A fixed 80-step protocol compares proportional feedback with two paired controls. The controller explicitly stores its target; this is an engineered fixture for the observatory.</p>${tracePlot(b.sample_traces)}${table(['Condition','Successful trials','95% Wilson interval'],Object.entries(b.outcomes).map(([k,v])=>[esc(k),`${v.successes} / ${v.replicates}`,v.wilson_95_interval.map(num).join(' – ')]))}<h3>Cognitive-cone task profile</h3>${dump(b.cognitive_cone)}<details><summary>Protocol, controls and capability claim</summary>${dump({protocol:b.protocol,controls:b.paired_controls,claim:b.capability_claim,limits:b.limitations})}</details>`:'<p>No behavior report exists for this run.</p>';}
else if(tab==='validation'){const v=state.validation;html=`<h2>Validation and failure evidence</h2><div class="notice">Perfect scores on separable synthetic observations are an execution check. They do not establish field calibration, Army acceptance, or generalization to new sensors.</div>${v?table(['Frozen-model condition','Pattern F1','Pattern Brier','Link F1','Capture set coverage (links)'],Object.entries(v.cases).map(([k,c])=>[esc(k),num(c.task12.classifier.f1),num(c.task12.classifier.brier),num(c.task13.classifier.f1),num(c.task13.prediction_sets.capture_coverage)])):'<p>Stress and Weka validation have not been run for this new model. Use the documented validation commands; results from another model are not substituted.</p>'}<h3>Weka evaluation</h3>${state.weka?dump(state.weka):'<p>No Weka report exists for this run.</p>'}`;}
else if(tab==='export')html=`<h2>Reproduce and inspect</h2><p>Frozen predictions are outputs for Weka Evaluation. Do not train a classifier using the predicted probabilities as input features.</p><div class="actions">${[['zip','Complete run'],['result','Full result JSON'],['task12','Task 12 ARFF'],['task13','Task 13 ARFF'],['geojson','CREP GeoJSON'],['behavior','Behavior JSON']].map(([k,l])=>`<a class="file" href="/api/formspace/export?format=${k}">${l} ↓</a>`).join('')}</div><h3>Evidence proof</h3>${dump(r.proof)}<p class="muted">A matching hash proves consistency of the recorded bytes. It does not authenticate a sensor or establish the truth of an observation.</p>`;
$('#content').innerHTML=html;
if(tab==='atlas')bindAtlas();
if(tab==='patterns'&&r){const show=()=>$('#record-detail').innerHTML=dump(r.task12.predictions[Number($('#record').value)]);$('#record').onchange=show;show();}
if(tab==='map'&&r){const show=()=>{const ids=new Set(r.task12.predictions.filter(p=>p.group===$('#capture').value).map(p=>p.id));const fs=r.task14.geojson.features.filter(f=>ids.has(f.properties.id)&&f.geometry?.type==='Point');if(!fs.length){$('#spatial').textContent='No supported coordinates in this capture.';return;}const xs=fs.map(f=>f.geometry.coordinates[0]),ys=fs.map(f=>f.geometry.coordinates[1]),xmin=Math.min(...xs),ymin=Math.min(...ys),dx=Math.max(...xs)-xmin||.001,dy=Math.max(...ys)-ymin||.001;$('#spatial').innerHTML=`<p>${fs.length} observations · longitude ${num(xmin)} to ${num(xmin+dx)} · latitude ${num(ymin)} to ${num(ymin+dy)}</p><svg viewBox="0 0 800 380" role="img" aria-label="Synthetic environmental observations in geographic coordinates">${fs.map(f=>`<circle cx="${40+(f.geometry.coordinates[0]-xmin)/dx*720}" cy="${330-(f.geometry.coordinates[1]-ymin)/dy*290}" r="4" fill="#78d6a4" opacity=".45"><title>${esc(f.properties.id)}</title></circle>`).join('')}</svg>`;};$('#capture').onchange=show;show();}
}
async function refresh(){[state,atlas]=await Promise.all([api('/api/formspace'),api('/api/form-atlas')]);$('#status').textContent=`${state.origin==='BUNDLED_RECORDED_RUN'?'Bundled recorded result':'Local completed run'} · ${state.result?.model_sha256?.slice(0,16)||'no model'} · ${dataset?'supplied dataset selected':'controlled synthetic dataset selected'}`;render();}
async function poll(){if(!job)return;try{const j=await api('/api/jobs/'+job);$('#status').textContent=j.events?.at(-1)?.message||j.status;if(['ERROR','CANCELLED','COMPLETED'].includes(j.status)){job=null;$('#run').disabled=false;$('#cancel').hidden=true;if(j.status==='COMPLETED')await refresh();else throw Error(j.error||'Run cancelled');}else setTimeout(poll,700);}catch(e){$('#status').textContent=e.message;$('#run').disabled=false;$('#cancel').hidden=true;job=null;}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});
$('#run').onclick=async()=>{try{$('#run').disabled=true;const j=await api('/api/formspace/run',{seed:Number($('#seed').value),...(dataset?{dataset}:{})});job=j.id;$('#cancel').hidden=false;poll();}catch(e){$('#status').textContent=e.message;$('#run').disabled=false;}};
$('#cancel').onclick=async()=>{if(job)await api('/api/cancel',{job_id:job});};
$('#dataset').onchange=async e=>{try{const f=e.target.files[0];if(!f){dataset=null;return;}if(f.size>16000000)throw Error('Dataset limit is 16 MB');const d=JSON.parse(await f.text());if(!Array.isArray(d.records))throw Error('A records array and explicit evaluation roles are required');dataset=d;$('#status').textContent=`Selected ${f.name}: ${d.records.length} records. Run to validate and train.`;}catch(e){dataset=null;$('#status').textContent=e.message;}};
(async()=>{try{const b=await api('/api/bootstrap');token=b.csrf_token;await refresh();const running=b.active_jobs.find(j=>j.kind==='formspace');if(running){job=running.id;$('#run').disabled=true;$('#cancel').hidden=false;poll();}}catch(e){$('#status').textContent=e.message;}})();

function atlasPage(){
 if(!atlas)return '<p>Loading the mathematical and behavioral atlas…</p>';
 return `<h2>Forms, systems, behaviors and what NLM observes</h2><p>The subject of a state can be a mathematical structure, species, algorithm, behavioral system or phenomenon. Instruments contribute observations. Symbolic forms do not require invented numerical coordinates.</p><div class="grid">${Object.entries(atlas.counts).map(([k,v])=>`<div class="card"><small>${esc(k.replaceAll('_',' '))}</small><strong class="big">${num(v)}</strong></div>`).join('')}</div><div class="actions"><label>Domain <select id="atlas-domain"><option value="">All domains</option>${atlas.domains.map(d=>`<option value="${esc(d.domain)}">${esc(d.domain)} (${d.forms})</option>`).join('')}</select></label><label>Kind <select id="atlas-kind"><option value="">All kinds</option>${atlas.kinds.map(d=>`<option value="${esc(d.kind)}">${esc(d.kind)}</option>`).join('')}</select></label><input id="atlas-search" aria-label="Search registered forms" placeholder="Find a form or behavior"><button id="atlas-filter">Explore</button><a class="file" href="/api/form-atlas/export">Export atlas ↓</a><label class="file">Import attributed forms <input id="atlas-import" type="file" accept=".json,application/json"></label></div><p class="muted">${esc(atlas.coverage)}. Definitions, literature, hypotheses and local measurements are distinct. Domain placement below is a navigation layout, not a universal distance metric.</p><div id="atlas-map"></div><div id="atlas-subject"></div>`;
}
function paintAtlasMap(data){
 const domains=[...new Set(data.forms.map(f=>f.domain))];
 $('#atlas-map').innerHTML=`<div class="grid">${domains.map(d=>`<section class="card"><p class="eyebrow">${esc(d)}</p>${data.forms.filter(f=>f.domain===d).map(f=>`<p><button class="form-select" data-id="${esc(f.id)}">${esc(f.label)}</button><br><small>${esc(f.kind)} · ${esc(f.epistemic_status)}</small></p>`).join('')}</section>`).join('')}</div>`;
 document.querySelectorAll('.form-select').forEach(button=>button.onclick=async()=>{
  try{const item=await api('/api/form-atlas/subject?id='+encodeURIComponent(button.dataset.id));const measured=item.form_states.filter(s=>s.state_kind!=='definition_record');
   $('#atlas-subject').innerHTML=`<h2>${esc(item.form.label)}</h2><p>${esc(item.form.description||'Registered form')}</p><p><span class="tag">${esc(item.form.epistemic_status)}</span> · ${item.form_states_total} states · ${item.form_observations_total} observations · ${item.form_claims_total} claims</p><h3>Relationships</h3>${table(['From','Relationship','To','Evidence status'],item.relations.map(x=>[esc(x.source_id),esc(x.relation),esc(x.target_id),esc(x.epistemic_status)]))}<h3>States of this subject</h3><p class="muted">Showing up to 200 records. A definition record describes a form; it is not an empirical measurement.</p>${dump(measured.length?measured:item.form_states)}<details><summary>Raw observations and their instruments</summary>${dump(item.form_observations)}</details><details><summary>Capability claims and evidence</summary>${dump(item.form_claims)}</details><details><summary>Complete form definition</summary>${dump(item.form)}</details>`;
   $('#atlas-subject').scrollIntoView({behavior:'smooth',block:'start'});
  }catch(e){$('#status').textContent=e.message;}
 });
}
function bindAtlas(){
 if(!atlas)return;paintAtlasMap(atlas);
 $('#atlas-filter').onclick=async()=>{try{const q=new URLSearchParams({domain:$('#atlas-domain').value,kind:$('#atlas-kind').value,q:$('#atlas-search').value});paintAtlasMap(await api('/api/form-atlas?'+q));}catch(e){$('#status').textContent=e.message;}};
 $('#atlas-import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>16000000)throw Error('Import limit is 16 MB');const response=await api('/api/form-atlas/import',JSON.parse(await f.text()));await refresh();$('#status').textContent='Atlas import completed: '+JSON.stringify(response.counts);}catch(e){$('#status').textContent=e.message;}};
}
