import {snapshot, allMeasurements, ASSETS, SAMPLE_COUNT} from './replay-core.mjs';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let boot,ws,docId,page=1,currentPage=null,imageMode=false,index=0,selectedAsset=ASSETS[0].id,timer=null,readSequence=0;
function notice(message,error=false){$('#status').textContent=message;$('#status').className=error?'error':'';}
async function api(path,body){const r=await fetch(path,{cache:'no-store',headers:body?{'Content-Type':'application/json','X-ITDX-Token':boot.csrf_token}:{},method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function guarded(fn){return async e=>{try{await fn(e);}catch(error){notice(error.message,true);}};}
function setTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));for(const id of ['sources','tasks','replay','checks'])$('#'+id).hidden=id!==tab;if(tab==='replay')drawReplay();}
function selectedDocuments(){return ws.documents.filter(d=>$('#pack').value==='all'||d.pack_id);}
function refreshLists(){
 $('#metrics').innerHTML=`<div class="metric"><b>${ws.documents.length}</b><span>Preserved source documents</span></div><div class="metric"><b>${ws.documents.filter(d=>d.pack_id).reduce((n,d)=>n+d.page_count,0)}</b><span>Exercise PDF pages</span></div><div class="metric"><b>16</b><span>Objectives with explicit status</span></div><div class="metric"><b>${ws.notes.length}</b><span>Saved, cited reviewer notes</span></div>`;
 $('#document-list').innerHTML=selectedDocuments().map(d=>`<button class="doc-button ${d.id===docId?'selected':''}" data-doc="${esc(d.id)}">${esc(d.name.replace('DRAFT 3ID OPORD 14-06 ',''))}<small>${d.page_count} pages · ${esc(d.data_origin)}</small></button>`).join('')||'<p class="muted">No exercise pack installed. Select All documents or import files.</p>';
 const previousTask=$('#task').value;$('#task').innerHTML=ws.tasks.map(t=>`<option value="${t.task_id}">${t.task_id}. ${esc(t.title)}</option>`).join('');if(previousTask)$('#task').value=previousTask;
 $('#task-rows').innerHTML=ws.tasks.map(t=>`<tr><td>${t.task_id}</td><td>${esc(t.title)}</td><td>${esc(t.implementation_status)}</td><td>${t.reference_ids.length?t.reference_ids.map(id=>`<button data-doc="${id}">${esc(ws.documents.find(d=>d.id===id)?.name||id)}</button>`).join(''):'<span class="muted">No linked reference</span>'}</td></tr>`).join('');
 renderNotes();renderChecks();
}
async function openPage(id,n=1){
 const seq=++readSequence;const d=ws.documents.find(x=>x.id===id);if(!d)return;
 const data=await api(`/api/workspace/page?id=${encodeURIComponent(id)}&page=${n}`);if(seq!==readSequence)return;
 docId=id;page=n;currentPage=data;if(window.parent!==window)window.parent.postMessage({type:'itdx:selection',context:{documentId:id,dataOrigin:data.data_origin}},window.location.origin);imageMode=imageMode&&data.preview_available;
 refreshLists();$('#document-heading').innerHTML=`<h2>${esc(d.name)}</h2><div class="marking">${esc(d.markings.join(' • ')||'Source document; handling as supplied')}</div><p class="muted">${esc(data.source_date||'Source date not normalized')} · ${esc(d.extraction)}</p>`;
 $('#page').innerHTML=Array.from({length:d.page_count},(_,i)=>`<option value="${i+1}" ${i+1===n?'selected':''}>${i+1} / ${d.page_count}</option>`).join('');$('#previous').disabled=n<=1;$('#next').disabled=n>=d.page_count;
 $('#original').href='/api/document/download?id='+encodeURIComponent(id);$('#citation').textContent=data.citation;$('#view-mode').disabled=!data.preview_available;renderPage();
}
function renderPage(){if(!currentPage)return;$('#view-mode').textContent=imageMode?'View extracted text':'View page image';$('#page-content').innerHTML=imageMode?`<img src="/api/workspace/preview?id=${encodeURIComponent(docId)}&page=${page}" alt="Original document page ${page}">`:`<pre id="source-text">${esc(currentPage.text)||'No embedded text. Open the original document.'}</pre>`;}
function renderNotes(){$('#notes').innerHTML=ws.notes.filter(n=>n.document_id===docId).slice(0,20).map(n=>`<div class="note-card"><strong>Task ${n.task_id} · ${esc(n.review_status)}</strong><p>“${esc(n.quote)}”</p><p>${esc(n.note)}</p><small class="muted">${esc(n.reviewer)} · page ${n.page} · ${esc(n.created_at)}</small></div>`).join('');}
function renderChecks(){const c=ws.checks[0];$('#check-results').innerHTML=c?`<h2>${c.hash_matches} / ${c.documents} originals match their recorded hashes</h2><p class="muted">${esc(c.created_at)} · Source-truth probability: not established</p><div class="table-wrap"><table><thead><tr><th>Document</th><th>Original</th><th>SHA-256</th><th>Text pages</th></tr></thead><tbody>${c.rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.original_present?'Present':'Missing'}</td><td class="${r.hash_matches?'good':'warn'}">${r.hash_matches?'Match':'Mismatch'}</td><td>${r.nonempty_text_pages}/${r.page_count}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No check run saved yet.</p>';}
async function search(){const q=$('#search').value.trim();if(!q){$('#search-results').innerHTML='';return;}const r=await api('/api/workspace/search?q='+encodeURIComponent(q)+'&scope='+encodeURIComponent($('#pack').value));const allowed=new Set(selectedDocuments().map(d=>d.id));const hits=r.hits.filter(h=>allowed.has(h.id));$('#search-results').innerHTML=hits.map(h=>`<button data-doc="${h.id}" data-source-page="${h.page}"><strong>${esc(h.name)} · page ${h.page}</strong><p class="muted">${esc(h.snippet)}</p></button>`).join('')||'<p>No matching pages in the selected source set.</p>';}
function download(name,value){const b=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const project=([lng,lat])=>[40+(lng+.024)/.048*880,620-(lat+.022)/.044*580];
function svgPath(coords){return coords.map((p,i)=>(i?'L':'M')+project(p).map(x=>x.toFixed(2)).join(',')).join(' ');}
function drawReplay(){
 if(!$('#replay').hidden&&window.parent!==window)window.parent.postMessage({type:'itdx:replay',index,assetId:selectedAsset},window.location.origin);
 const s=snapshot(index);$('#replay-time').textContent=s.replay_time.slice(11,19)+'Z · 20× playback';$('#time').value=index;
 let svg='<rect width="960" height="660" fill="#0a1822"/>';
 for(let i=0;i<=8;i++){const x=40+i*110,y=40+i*72.5;svg+=`<path d="M${x},40 V620 M40,${y} H920" class="map-grid"/>`;}
 svg+='<text x="45" y="25" class="map-label">FICTIONAL EXERCISE GRID · EPSG:4326 · 0°N, 0°E</text>';
 for(const f of s.geojson.features){const p=f.properties,c=p.color||'#6be0b6';if(f.geometry.type==='Polygon'){svg+=`<path d="${svgPath(f.geometry.coordinates[0])} Z" fill="${p.kind==='uncertainty'?c:'none'}" fill-opacity=".15" stroke="${c}" stroke-width="${p.kind==='boundary'?2:1}" stroke-dasharray="${p.kind==='corridor'?'8 6':'0'}"/>`;}else if(f.geometry.type==='LineString'){svg+=`<path d="${svgPath(f.geometry.coordinates)}" fill="none" stroke="${c}" stroke-opacity=".6" stroke-width="2" stroke-dasharray="5 5"/>`;}else{const [x,y]=project(f.geometry.coordinates);svg+=`<g data-asset="${esc(p.asset_id)}" role="button" tabindex="0" aria-label="Select ${esc(p.label)}" style="cursor:pointer"><circle cx="${x}" cy="${y}" r="${p.asset_id===selectedAsset?9:7}" fill="${c}" stroke="white" stroke-width="2"/><text x="${x+13}" y="${y-10}" class="asset-label">${esc(p.label)}</text></g>`;}}
 $('#map').innerHTML=svg;$('#asset-picker').innerHTML=ASSETS.map(a=>`<button class="pick-asset" data-asset="${a.id}">${esc(a.label)}</button>`).join('');
 const a=s.assets.find(a=>a.id===selectedAsset);$('#asset-heading').textContent=a.label;
 const rows=[['Position',a.position?a.position.map(n=>n.toFixed(6)).join(', '):'Not received'],['Observation age',a.age_seconds===null?'Unknown':a.age_seconds+' s'],['Observed-time error',a.latest_error_at_observation_m===null?'Unmeasured':a.latest_error_at_observation_m.toFixed(1)+' m'],['Nominal 95% radius',a.nominal_radius_m.toFixed(1)+' m'],['Measured coverage',a.empirical_coverage===null?'Unmeasured':`${(100*a.empirical_coverage).toFixed(1)}% (${a.coverage_count}/${a.valid_reports})`],['Position RMSE',a.rmse_m===null?'Unmeasured':a.rmse_m.toFixed(1)+' m'],['Missing reports',a.missing_reports],['Accuracy/deception probability','Not inferred']];
 $('#asset-detail').innerHTML=`<p class="muted">${esc(a.kind)} · ${esc(a.fault)}</p><p class="${a.age_seconds>30||a.assumption_status.startsWith('DECLARED')?'warn':'good'}">${esc(a.current_position_status)}</p>${rows.map(([k,v])=>`<div class="asset-kv"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}<p class="muted">${esc(a.assumption_status)}</p>`;
}
document.addEventListener('click',guarded(async e=>{const tab=e.target.closest('[data-tab]');if(tab)return setTab(tab.dataset.tab);const d=e.target.closest('[data-doc]');if(d){setTab('sources');if(!selectedDocuments().some(x=>x.id===d.dataset.doc))$('#pack').value='all';await openPage(d.dataset.doc,Number(d.dataset.sourcePage||1));return;}const a=e.target.closest('[data-asset]');if(a){selectedAsset=a.dataset.asset;drawReplay();}}));
$('#map').addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.dataset.asset){e.preventDefault();selectedAsset=e.target.dataset.asset;drawReplay();}});
$('#previous').onclick=guarded(()=>openPage(docId,page-1));$('#next').onclick=guarded(()=>openPage(docId,page+1));$('#page').onchange=guarded(e=>openPage(docId,Number(e.target.value)));$('#view-mode').onclick=()=>{imageMode=!imageMode;renderPage();};
$('#pack').onchange=guarded(async()=>{refreshLists();const d=selectedDocuments()[0];if(d)await openPage(d.id);});$('#search-button').onclick=guarded(search);$('#search').onkeydown=guarded(e=>e.key==='Enter'?search():null);
$('#use-selection').onclick=()=>{const text=window.getSelection()?.toString()||'';if(!currentPage?.text.includes(text)||!text)return notice('Select an exact quotation in the extracted source text.',true);$('#quote').value=text;};
$('#note-form').onsubmit=guarded(async e=>{e.preventDefault();await api('/api/workspace/notes',{document_id:docId,page,quote:$('#quote').value,note:$('#note').value,reviewer:$('#reviewer').value,task_id:Number($('#task').value),review_status:$('#review-state').value});ws=await api('/api/workspace');refreshLists();notice('Cited note saved. Source text remains unchanged.');});
$('#run-checks').onclick=guarded(async()=>{notice('Checking originals…');await api('/api/workspace/check',{});ws=await api('/api/workspace');refreshLists();notice('Document integrity checks saved.');});
$('#import').onchange=guarded(async e=>{for(const file of e.target.files){if(file.size>16000000)throw Error('Import limit is 16 MB per document');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await api('/api/import',{name:file.name,kind:'document',data_base64:btoa(binary)});}ws=await api('/api/workspace');$('#pack').value='all';refreshLists();notice('Documents imported with their original bytes.');});
function stop(){clearInterval(timer);timer=null;$('#play').textContent='Play replay';}
$('#play').onclick=()=>{if(timer)return stop();if(index===SAMPLE_COUNT-1)index=0;$('#play').textContent='Pause replay';timer=setInterval(()=>{index++;drawReplay();if(index>=SAMPLE_COUNT-1)stop();},500);};$('#reset').onclick=()=>{stop();index=0;drawReplay();};$('#time').oninput=e=>{stop();index=Number(e.target.value);drawReplay();};$('#export-replay').onclick=()=>download('itdx-fictional-frame-'+index+'.geojson',snapshot(index).geojson);$('#export-measurements').onclick=()=>download('itdx-fictional-measurements.json',allMeasurements());
try{boot=await api('/api/bootstrap');ws=await api('/api/workspace');if(!ws.documents.some(d=>d.pack_id))$('#pack').value='all';refreshLists();const first=selectedDocuments()[0];if(first)await openPage(first.id);drawReplay();notice('Ready. Source review and synthetic replay use separate data.');}catch(e){notice(e.message,true);}
