"use client"

import Link from "next/link"
import { useCallback, useEffect, useState } from "react"
import { Bot, Network, RefreshCw, ShieldCheck, Workflow } from "lucide-react"
import { getOperationalDefinition, type OperationalSurface } from "@/lib/fusarium/ai-readiness/operational"

type Row = Record<string, any>
type Result = { ok: boolean; status: number | null; data?: Row; error?: string }
const ICONS = { "ai-studio": Bot, workflows: Workflow, mas: Network, avani: ShieldCheck } as const
const tone = (good: boolean) => good ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : "border-amber-400/30 bg-amber-400/10 text-amber-100"

function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) {
  return <article className="rounded-2xl border border-white/10 bg-black/35 p-4 backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-zinc-500">{label}</p><p className="mt-2 break-words text-2xl font-black">{value}</p>{note ? <p className="mt-1 text-xs leading-5 text-zinc-500">{note}</p> : null}</article>
}

function AiStudio({ data }: { data: Row }) {
  const sources = Array.isArray(data.sources) ? data.sources : []; const systems = data.systems || {}
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Verified sources" value={`${sources.filter((s: Row) => s.ok).length}/${sources.length}`}/><Metric label="Agents" value={systems.agents?.total ?? 0} note={`${systems.agents?.active ?? 0} reported active`}/><Metric label="Services" value={systems.services?.total ?? 0} note={`${systems.services?.online ?? 0} reported online`}/><Metric label="Devices" value={systems.devices?.total ?? 0} note={`${systems.devices?.online ?? 0} reported online`}/></div><div className="mt-3 grid gap-3 lg:grid-cols-2">{sources.map((source: Row) => <article key={source.key} className="rounded-2xl border border-white/10 bg-black/30 p-3"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">{source.label}</h2><span className={`rounded-full border px-2 py-1 text-[9px] font-black uppercase ${tone(Boolean(source.ok))}`}>{source.ok ? "read ok" : "unavailable"}</span></div><p className="mt-2 text-xs text-zinc-500">{source.endpoint} · {source.latencyMs ?? 0} ms</p>{source.error ? <p className="mt-2 text-xs text-amber-200">{source.error}</p> : null}</article>)}</div></>
}

function Workflows({ runtime, inventory }: { runtime: Row; inventory: Row }) {
  const exports = Array.isArray(inventory.workflows) ? inventory.workflows : []
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Runtime workflows" value={runtime.total ?? 0} note={runtime.hasRealData ? "Observed from n8n" : "No live workflow data"}/><Metric label="Active runtime" value={runtime.activeCount ?? 0}/><Metric label="Recent executions" value={Array.isArray(runtime.executions) ? runtime.executions.length : 0}/><Metric label="Known exports" value={inventory.total ?? exports.length} note="Definitions, not runtime evidence"/></div><div className="mt-3 grid gap-3 lg:grid-cols-[1fr_1.4fr]"><article className="rounded-2xl border border-white/10 bg-black/30 p-4"><h2 className="font-bold">Runtime sources</h2>{Object.entries(runtime.sources || {}).map(([key, value]: [string, any]) => <div key={key} className="mt-3 flex justify-between gap-3 border-t border-white/[0.07] pt-3"><span className="capitalize">{key} n8n</span><span className={`rounded-full border px-2 py-1 text-[9px] font-black uppercase ${tone(Boolean(value.connected))}`}>{value.connected ? `${value.count} observed` : "disconnected"}</span></div>)}</article><article className="rounded-2xl border border-white/10 bg-black/30 p-4"><h2 className="font-bold">Repository export inventory</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{exports.slice(0, 12).map((item: Row) => <div key={`${item.id}-${item.file}`} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-zinc-500">{item.category} · {item.file}</p></div>)}</div>{exports.length > 12 ? <p className="mt-3 text-xs text-zinc-500">Showing 12 of {exports.length} known exports.</p> : null}</article></div></>
}

function Mas({ health, registry }: { health: Row; registry: Row }) {
  const agents = Array.isArray(registry.agents) ? registry.agents : []; const categories = new Set(agents.map((a: Row) => a.category))
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Orchestrator" value={health.status || "unknown"} note={health.reachable ? "Endpoint reachable" : "No reachability evidence"}/><Metric label="Latency" value={health.latency_ms != null ? `${health.latency_ms} ms` : "—"}/><Metric label="Registry entries" value={agents.length} note="Declared agents, not process proof"/><Metric label="Categories" value={categories.size}/></div><article className="mt-3 rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">Declared agent registry</h2><span className="rounded-full border border-amber-400/25 bg-amber-400/10 px-2 py-1 text-[9px] font-black uppercase text-amber-100">not execution proof</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{agents.slice(0, 18).map((agent: Row) => <div key={agent.agent_id || agent.id} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><div className="flex justify-between gap-2"><p className="font-semibold">{agent.name}</p><span className={`h-fit rounded-full border px-2 py-1 text-[9px] uppercase ${tone(["active","online"].includes(agent.status))}`}>{agent.status || "unknown"}</span></div><p className="mt-1 text-xs text-zinc-500">{agent.category} · {agent.type}</p></div>)}</div>{agents.length > 18 ? <p className="mt-3 text-xs text-zinc-500">Showing 18 of {agents.length} registry entries.</p> : null}</article></>
}

function Avani({ status, inventory }: { status: Row; inventory: Row }) {
  const rules = Array.isArray(inventory.rules) ? inventory.rules : []
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Embedded engine" value={status.active ? "active" : "inactive"} note={status.mode}/><Metric label="Rules loaded" value={status.rules_loaded ?? rules.length}/><Metric label="Authoritative backend" value={status.backend_connected ? "connected" : "disconnected"} note="Embedded policy cannot replace authority"/><Metric label="Constitution" value={status.constitution_version || inventory.constitution_version || "unknown"}/></div><div className="mt-3 grid gap-3 lg:grid-cols-2">{rules.map((rule: Row) => <article key={rule.id} className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-emerald-300">{rule.category}</p><h2 className="mt-1 font-bold">{rule.name}</h2></div><span className={`h-fit rounded-full border px-2 py-1 text-[9px] font-black uppercase ${tone(Boolean(rule.active))}`}>{rule.active ? "embedded" : "inactive"}</span></div><p className="mt-2 text-sm leading-5 text-zinc-400">{rule.description}</p><p className="mt-2 text-xs text-zinc-600">Rule {rule.id} · weight {rule.weight}</p></article>)}</div></>
}

export function AiOperationalWorkspace({ surface }: { surface: OperationalSurface }) {
  const definition = getOperationalDefinition(surface); const Icon = ICONS[surface]; const [results, setResults] = useState<Result[]>([]); const [loading, setLoading] = useState(true); const [observed, setObserved] = useState<string>()
  const refresh = useCallback(async () => { setLoading(true); const next = await Promise.all(definition.sources.map(async source => { try { const response = await fetch(source.endpoint, { cache: "no-store", headers: { Accept: "application/json" } }); const data = await response.json().catch(() => undefined); return { ok: response.ok, status: response.status, data, error: response.ok ? undefined : `HTTP ${response.status}` } } catch (error) { return { ok: false, status: null, error: error instanceof Error ? error.message : "Read failed" } } })); setResults(next); setObserved(new Date().toISOString()); setLoading(false) }, [definition.sources])
  useEffect(() => { void refresh() }, [refresh]); const available = results.filter(r => r.ok).length
  return <main className="min-h-full w-full bg-[radial-gradient(circle_at_top_left,rgba(34,197,94,0.09),transparent_34%),linear-gradient(145deg,#040605,#0a0f0c_55%,#030504)] p-3 text-zinc-100 md:p-5" data-ai-operational={surface}><header className="rounded-2xl border border-white/10 bg-black/50 p-4 shadow-2xl backdrop-blur-xl md:p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-emerald-300/20 bg-emerald-400/10 text-emerald-300"><Icon className="h-6 w-6"/></span><div><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-emerald-300">Fusarium · {definition.eyebrow}</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{definition.title}</h1><p className="mt-2 max-w-4xl text-sm text-zinc-400">{definition.summary}</p></div></div><div className="flex gap-2"><button type="button" onClick={() => void refresh()} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`}/>Refresh</button><Link href="/fusarium" className="inline-flex min-h-11 items-center rounded-xl border border-emerald-400/25 bg-emerald-400/10 px-4 text-sm font-semibold text-emerald-200">Back to Fusarium</Link></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className={`rounded-full border px-2 py-1 font-bold uppercase ${tone(available === definition.sources.length && available > 0)}`}>{loading ? "reading" : `${available}/${definition.sources.length} sources available`}</span>{observed ? <span className="py-1 text-zinc-600">Observed {new Date(observed).toLocaleTimeString()}</span> : null}</div></header><aside className="mt-3 rounded-2xl border border-amber-400/15 bg-amber-400/[0.05] p-3 text-xs leading-5 text-amber-100/80"><strong>Operational boundary:</strong> {definition.boundary}</aside><section className="mt-3">{surface === "ai-studio" ? <AiStudio data={results[0]?.data || {}}/> : surface === "workflows" ? <Workflows runtime={results[0]?.data || {}} inventory={results[1]?.data || {}}/> : surface === "mas" ? <Mas health={results[0]?.data || {}} registry={results[1]?.data || {}}/> : <Avani status={results[0]?.data || {}} inventory={results[1]?.data || {}}/>}</section>{!loading && available === 0 ? <p className="mt-3 rounded-2xl border border-amber-400/20 bg-black/40 p-8 text-center text-sm text-zinc-500">No operational source answered. The surface remains fail-closed; no placeholder activity was generated.</p> : null}</main>
}
