'use client';

import { useCallback, useEffect, useState } from 'react';
import { BookOpen, Download, FileText, History, Info, Loader2, ScrollText } from 'lucide-react';
import { GlassButton } from '@/components/ui/glass-button';
import { PageHeader, Card, StateBadge, type Tone } from '@/components/launchpad/ui';
import { FeatureGate, TierTag } from '@/components/launchpad/entitlements';

/**
 * Readiness reports — deterministic DRAFT assembly from recorded tenant data.
 *
 * No LLM anywhere on this screen: reports are pure assembly from what the
 * customer recorded (the AI document factory is a separate tool under
 * /documents). Two groups: 'Generated from your data' (control states, score
 * snapshots, POA&M, BOM) and 'Educational skeletons' (structure + profile +
 * [CUSTOMER INPUT REQUIRED] placeholders). Nothing here certifies anything.
 */

interface CatalogEntry {
  key: string;
  title: string;
  group: 'generated' | 'skeleton';
  description: string;
  sources: string[];
}

interface HistoryRow {
  id: string;
  title: string;
  status: string;
  rule_pack_version: string | null;
  created_at: string;
  report_key: string | null;
}

const STATUS_TONE: Record<string, Tone> = {
  draft: 'amber',
  customer_review: 'sky',
  approved: 'emerald',
  superseded: 'slate',
};

function downloadMarkdown(filename: string, markdown: string) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ReadinessReportsPage() {
  const [catalog, setCatalog] = useState<CatalogEntry[]>([]);
  const [history, setHistory] = useState<HistoryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [generating, setGenerating] = useState<string | null>(null);
  const [downloading, setDownloading] = useState<string | null>(null);

  const load = useCallback(async () => {
    try {
      const r = await fetch('/api/fusarium/launchpad/readiness/reports', { cache: 'no-store' });
      const d = await r.json();
      if (r.ok) { setCatalog(d.catalog ?? []); setHistory(d.history ?? []); setErr(null); }
      else setErr(d?.error || `HTTP ${r.status}`);
    } catch { setErr('Could not load the report catalog'); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { load(); }, [load]);

  const generate = async (key: string) => {
    setGenerating(key); setErr(null);
    try {
      const r = await fetch('/api/fusarium/launchpad/readiness/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report: key }),
      });
      const d = await r.json().catch(() => ({}));
      if (!r.ok) { setErr(d?.error || 'Generation failed'); return; }
      if (typeof d.markdown === 'string') {
        downloadMarkdown(`${key}-DRAFT-${new Date().toISOString().slice(0, 10)}.md`, d.markdown);
      }
      await load();
    } catch { setErr('Generation failed'); }
    finally { setGenerating(null); }
  };

  const downloadPast = async (row: HistoryRow) => {
    setDownloading(row.id); setErr(null);
    try {
      const r = await fetch(`/api/fusarium/launchpad/readiness/reports?id=${row.id}`, { cache: 'no-store' });
      const d = await r.json().catch(() => ({}));
      if (!r.ok) { setErr(d?.error || 'Could not load that report'); return; }
      const md = d?.document?.markdown;
      if (typeof md !== 'string' || !md) {
        setErr('That report was generated by a different tool and has no markdown to download here.');
        return;
      }
      downloadMarkdown(`${row.report_key ?? 'report'}-DRAFT-${String(row.created_at).slice(0, 10)}.md`, md);
    } catch { setErr('Could not load that report'); }
    finally { setDownloading(null); }
  };

  if (loading) {
    return <div className="min-h-[50vh] flex items-center justify-center gap-2 text-muted-foreground">
      <Loader2 className="h-5 w-5 animate-spin text-current" /> Loading report catalog…
    </div>;
  }

  const generated = catalog.filter((c) => c.group === 'generated');
  const skeletons = catalog.filter((c) => c.group === 'skeleton');

  const renderCard = (entry: CatalogEntry) => (
    <Card key={entry.key} tone={entry.group === 'generated' ? 'emerald' : 'sky'} className="p-4 flex flex-col">
      <div className="pl-1.5 flex-1">
        <div className="flex items-start gap-2 mb-1.5">
          {entry.group === 'generated'
            ? <FileText className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
            : <BookOpen className="h-4 w-4 text-sky-500 shrink-0 mt-0.5" />}
          <span className="text-sm font-semibold leading-snug">{entry.title}</span>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed mb-2">{entry.description}</p>
        <div className="flex flex-wrap gap-1.5 mb-3">
          {entry.sources.map((s) => (
            <code key={s} className="text-[10px] px-1.5 py-0.5 rounded bg-muted text-muted-foreground">{s}</code>
          ))}
        </div>
      </div>
      <div className="pl-1.5">
        <GlassButton onClick={() => generate(entry.key)} disabled={generating !== null}>
          {generating === entry.key
            ? <Loader2 className="h-4 w-4 animate-spin text-current mr-2" />
            : <Download className="h-4 w-4 text-current mr-2" />}
          {generating === entry.key ? 'Assembling…' : 'Generate + download DRAFT'}
        </GlassButton>
      </div>
    </Card>
  );

  return (
    <div className="container max-w-5xl mx-auto px-4 sm:px-6 py-8">
      <PageHeader
        title="Readiness reports"
        icon={ScrollText}
        description={<>Deterministic DRAFT reports assembled from the data you recorded — no AI writes these (the AI document factory lives separately under Documents). <strong>No report here certifies, accredits, or approves anything</strong>; every download is headed DRAFT — CUSTOMER REVIEW REQUIRED.</>}
        actions={<TierTag feature="documentFactory" />}
      />

      {/* Education-first intro */}
      <Card className="p-5 mb-6">
        <div className="pl-1.5 grid sm:grid-cols-3 gap-4 text-sm">
          <div>
            <div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground mb-1">What is this</div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Pre-structured report drafts built from your workspace records: your requirement states,
              score snapshots, POA&amp;M (Plan of Action &amp; Milestones — the dated to-do list for gaps),
              and bill of materials. Assembly is pure code — the same inputs always produce the same report.
            </p>
          </div>
          <div>
            <div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground mb-1">Why it matters</div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Primes, contracting officers, and assessors ask for these artifacts — a self-assessment
              report, an SPRS (Supplier Performance Risk System) score record, a POA&amp;M. Having honest
              drafts ready, with every unknown marked [CUSTOMER INPUT REQUIRED], beats inventing them
              under deadline.
            </p>
          </div>
          <div>
            <div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground mb-1">Your next step</div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Record requirement states in the register and compute a score snapshot first — reports
              only reflect what you recorded. Then generate a draft below, review every line, and have
              your responsible official approve it before any external use.
            </p>
          </div>
        </div>
      </Card>

      {err && <Card tone="red" className="p-4 mb-5"><p className="text-sm pl-1.5">{err}</p></Card>}

      <FeatureGate feature="documentFactory">
        <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2">
          Generated from your data
          <span className="font-normal normal-case tracking-normal text-[11px] text-muted-foreground/70 ml-2">
            honest empties when nothing is recorded — never fabricated numbers
          </span>
        </h2>
        <div className="grid sm:grid-cols-2 gap-3 mb-8">
          {generated.map(renderCard)}
        </div>

        <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2">
          Educational skeletons
          <span className="font-normal normal-case tracking-normal text-[11px] text-muted-foreground/70 ml-2">
            structure + your profile + [CUSTOMER INPUT REQUIRED] — no data-driven builder yet
          </span>
        </h2>
        <div className="grid sm:grid-cols-2 gap-3 mb-8">
          {skeletons.map(renderCard)}
        </div>

        <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2 flex items-center gap-2">
          <History className="h-3.5 w-3.5" /> Generation history
          <span className="font-normal normal-case tracking-normal text-[11px] text-muted-foreground/70">
            every generation is audited
          </span>
        </h2>
        {history.length === 0 ? (
          <Card className="p-8 text-center">
            <ScrollText className="h-7 w-7 text-muted-foreground/40 mx-auto mb-3" />
            <p className="text-sm font-medium">No reports generated yet</p>
            <p className="text-xs text-muted-foreground mt-1 max-w-md mx-auto">
              Generate your first DRAFT above. Each generation is stored here as a draft document and
              appended to your workspace audit trail.
            </p>
          </Card>
        ) : (
          <Card className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/40 text-left">
                <tr>
                  {['Report', 'Status', 'Rule pack', 'Generated', ''].map((h, i) => (
                    <th key={i} className="px-3 py-2 font-medium whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {history.map((h) => (
                  <tr key={h.id} className="border-t border-border/40">
                    <td className="px-3 py-2">
                      <span className="font-medium">{h.title}</span>
                      {h.report_key && <code className="text-[10px] text-muted-foreground ml-2">{h.report_key}</code>}
                    </td>
                    <td className="px-3 py-2 whitespace-nowrap">
                      <StateBadge tone={STATUS_TONE[h.status] ?? 'slate'}>{h.status.replace(/_/g, ' ')}</StateBadge>
                    </td>
                    <td className="px-3 py-2"><code className="text-[10px]">{h.rule_pack_version ?? '—'}</code></td>
                    <td className="px-3 py-2 whitespace-nowrap tabular-nums">{new Date(h.created_at).toLocaleString()}</td>
                    <td className="px-3 py-2 text-right">
                      <GlassButton onClick={() => downloadPast(h)} disabled={downloading !== null}>
                        {downloading === h.id
                          ? <Loader2 className="h-3.5 w-3.5 animate-spin text-current mr-1.5" />
                          : <Download className="h-3.5 w-3.5 text-current mr-1.5" />}
                        DRAFT .md
                      </GlassButton>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Card>
        )}

        <div className="flex items-start gap-2 text-[11px] text-muted-foreground mt-4">
          <Info className="h-3.5 w-3.5 shrink-0 mt-0.5" />
          <span>
            Reports are drafts assembled from customer-recorded data under rule pack versioning.
            &ldquo;Customer-marked implemented&rdquo; is a count you recorded — not a status determination.
            Launchpad never states that your company holds any CMMC status; a human at your company
            reviews, approves, and files everything.
          </span>
        </div>
      </FeatureGate>
    </div>
  );
}
