// ═══════════════════════════════════════════════════════════════════════════
// Compliance remediation engine — classify + auto-fix what can be automated
// ═══════════════════════════════════════════════════════════════════════════
//
// Walks all 110 CMMC L2 controls and classifies each control's remediation into:
//   • MYCA (auto)      — the DOCUMENTATION half (SSP narrative + family policy).
//                        Fully automatable; generated by the reports agent.
//   • CURSOR (tech)    — a system configuration change (MFA, audit logging,
//                        encryption, firewall, monitoring). Cursor has the
//                        credentials/network to execute it.
//   • MORGAN (human)   — procurement, physical, training, screening. Only Morgan.
//
// HONESTY: this never marks a control Met. Implementation + evidence are required
// before status changes. It automates the paperwork and hands the rest off with
// precise, owner-tagged instructions.

import { CMMC_L2_CONTROLS, isPoamExcluded, type ControlReference } from '@/lib/security/reference/cmmc-l2-reference';
import { getRemediationPlan } from '@/lib/security/remediation/remediation-library';
import { renderReportHtml, renderTable, renderProse, type ReportDocument } from './report-doc';
import { generateNarrative, activeReportProvider } from './llm';

export type RemediationOwner = 'myca' | 'cursor' | 'morgan';

export interface ControlRemediation {
  controlId: string;
  nistId: string;
  family: string;
  title: string;
  weightMax: number | null;
  poamEligible: boolean;
  excluded: boolean; // must be met before assessment
  owner: RemediationOwner; // owner of the IMPLEMENTATION (doc is always MYCA)
  action: string; // the concrete implementation action
  system: string; // where it's done
}

// Default implementation owner per family (for a 2-user PreVeil-enclave shop).
const FAMILY_OWNER: Record<string, RemediationOwner> = {
  AC: 'cursor', // access config (Google Workspace / PreVeil / Intune)
  AT: 'morgan', // training must be taken by people
  AU: 'cursor', // Wazuh / audit logs
  CM: 'cursor', // Intune/GPO baselines, allowlisting
  IA: 'cursor', // MFA, password policy
  IR: 'morgan', // IR plan review, tabletop, DIBNet registration
  MA: 'cursor', // patching / maintenance controls
  MP: 'morgan', // media marking/sanitization/physical (BitLocker part = cursor)
  PS: 'morgan', // background screening, offboarding
  PE: 'morgan', // physical locks, cameras, visitor log, alt-site
  RA: 'cursor', // vulnerability scanning
  CA: 'myca', // SSP / POA&M / assessment — documentation
  SC: 'cursor', // firewall / TLS / FIPS crypto (PreVeil) / boundary
  SI: 'cursor', // Wazuh monitoring, Defender, patching
};

// Control-specific owner overrides + concrete actions (the high-signal ones).
const OVERRIDE: Record<string, { owner: RemediationOwner; action: string; system: string }> = {
  'IA.L2-3.5.3': { owner: 'cursor', action: 'Enforce MFA for all users (Google 2SV enforcement + YubiKey/FIDO2 on privileged accounts). 5-point control — highest single impact.', system: 'Google Workspace + YubiKey' },
  'SI.L2-3.14.6': { owner: 'cursor', action: 'Deploy Wazuh SIEM monitoring inbound/outbound traffic. 5-point, NOT POA&M-eligible — hard gate for Conditional status.', system: 'Wazuh' },
  'AU.L2-3.3.4': { owner: 'cursor', action: 'Configure Wazuh audit-logging-failure alert rule. The single planned POA&M item (close 2026-08-31).', system: 'Wazuh' },
  'PS.L2-3.9.1': { owner: 'morgan', action: 'Order background check on RJ (Sterling/HireRight, ~$30–100, 24–48h). 3-point, NOT POA&M-eligible — must be met.', system: 'Sterling / HireRight' },
  'IR.L2-3.6.3': { owner: 'morgan', action: 'Run a 90-minute IR tabletop exercise. NOT POA&M-eligible — must be met.', system: 'Tabletop' },
  'IR.L2-3.6.2': { owner: 'morgan', action: 'Register for DIBNet + establish the 72-hour cyber-incident reporting path (DFARS 252.204-7012).', system: 'DIBNet (dibnet.dod.mil)' },
  'SC.L2-3.13.11': { owner: 'morgan', action: 'Confirm PreVeil FIPS 140-3 (CMVP #5145) covers all CUI crypto; retain the FedRAMP-equivalency 3PAO evidence. Purchase PreVeil Gov if not yet done.', system: 'PreVeil Gov' },
  'MP.L2-3.8.3': { owner: 'morgan', action: 'Establish NIST SP 800-88 media sanitization + a cross-cut shredder for CUI media. 5-point, not POA&M-eligible.', system: 'Physical / NIST 800-88' },
  'CA.L2-3.12.4': { owner: 'myca', action: 'System Security Plan — MYCA generates the SSP; Morgan reviews/signs. Blocking control (NA weight).', system: 'MYCA reports agent' },
  'CA.L2-3.12.2': { owner: 'myca', action: 'POA&M — MYCA maintains the live plan of action from the compliance dashboard.', system: 'This dashboard' },
};

export function classifyControl(ref: ControlReference): ControlRemediation {
  const o = OVERRIDE[ref.controlId];
  const owner = o?.owner ?? FAMILY_OWNER[ref.family] ?? 'cursor';
  const plan = getRemediationPlan(ref.controlId, ref.family);
  const action = o?.action ?? plan.objective;
  const system = o?.system ?? plan.tools[0] ?? '—';
  return {
    controlId: ref.controlId, nistId: ref.nistId, family: ref.family, title: ref.title,
    weightMax: ref.weightMax, poamEligible: ref.poamEligible, excluded: isPoamExcluded(ref.controlId),
    owner, action, system,
  };
}

export function classifyAll(): ControlRemediation[] {
  return CMMC_L2_CONTROLS.map(classifyControl);
}

/** Priority: not-POA&M-eligible + high weight first (must-be-met, biggest impact). */
function priority(c: ControlRemediation): number {
  let p = 0;
  if (c.excluded || !c.poamEligible) p += 100; // must be met before assessment
  p += (c.weightMax ?? 1) * 5; // heavier weight = higher SPRS impact
  return -p; // sort ascending → highest priority first
}

export async function buildRemediationPlan(): Promise<{ html: string; meta: Record<string, unknown> }> {
  const all = classifyAll();
  const byca = all.filter((c) => c.owner === 'myca');
  const cursor = all.filter((c) => c.owner === 'cursor').sort((a, b) => priority(a) - priority(b));
  const morgan = all.filter((c) => c.owner === 'morgan').sort((a, b) => priority(a) - priority(b));
  const provider = activeReportProvider();
  const now = new Date();

  // Fastest high-value wins: not-POA&M-eligible + 5-point, across all owners.
  const criticalPath = all
    .filter((c) => (c.excluded || !c.poamEligible))
    .sort((a, b) => priority(a) - priority(b));

  const facts =
    `110 CMMC L2 controls. MYCA can auto-generate the documentation (SSP narrative + policy) for ALL 110. ` +
    `Implementation ownership: ${cursor.length} controls are technical configuration (Cursor executes), ` +
    `${morgan.length} require procurement/physical/training (Morgan), ${byca.length} are documentation-only (MYCA). ` +
    `${criticalPath.length} controls are NOT POA&M-eligible and must be fully met before assessment — these are the critical path.`;

  const gen = await generateNarrative({
    system: 'You are a DoD compliance program manager writing the executive summary of a remediation plan for a small defense contractor pursuing CMMC Level 2. Precise, factual, government-standard. Use only the provided facts; never invent numbers. 2 short paragraphs.',
    user: `Summarize this remediation plan using ONLY these facts:\n\n${facts}`,
    maxTokens: 500,
  });
  const execHtml = gen ? renderProse(gen.text) : renderProse(
    `This plan classifies all 110 CMMC Level 2 controls by remediation owner. The documentation for every control — the System Security Plan narrative and the governing policy — is automatable and generated by the MYCA reports agent. ${cursor.length} controls require a technical configuration change executable with system credentials (routed to Cursor), ${morgan.length} require procurement, physical, or human action (routed to Morgan), and ${byca.length} are satisfied by documentation alone.\n\n${criticalPath.length} controls are not POA&M-eligible and must be fully met before an assessment can proceed — these form the critical path and are listed first in each owner's section.`);

  const remRows = (list: ControlRemediation[]) =>
    list.map((c) => [
      c.controlId,
      c.title.length > 70 ? c.title.slice(0, 70) + '…' : c.title,
      c.weightMax === null ? 'NA' : `${c.weightMax}pt`,
      c.excluded || !c.poamEligible ? 'MUST-MEET' : 'POA&M-ok',
      c.action,
    ] as (string | number)[]);

  const sections: ReportDocument['sections'] = [
    { id: 'exec', heading: 'Executive Summary', bodyHtml: execHtml },
    {
      id: 'critical', heading: `Critical path — must be met before assessment (${criticalPath.length})`,
      bodyHtml:
        `<div class="callout">These controls are not POA&amp;M-eligible under 32 CFR §170.21 — they must be fully implemented and evidenced before a Conditional status can be claimed. Ordered by SPRS impact.</div>` +
        renderTable(['Control', 'Title', 'Wt', 'Status', 'Action / owner'],
          criticalPath.map((c) => [c.controlId, c.title.length > 60 ? c.title.slice(0, 60) + '…' : c.title, c.weightMax === null ? 'NA' : `${c.weightMax}pt`, c.owner.toUpperCase(), c.action])),
    },
    {
      id: 'myca', heading: `MYCA — automated documentation (all 110 controls + ${byca.length} doc-only)`,
      bodyHtml:
        `<p>The MYCA reports agent auto-generates, for <strong>every</strong> control, the SSP implementation narrative and the governing family policy — the documentation half of CMMC, satisfied without human effort. Generate per-control from the compliance workbook ("Generate policy document"), or the full set below.</p>` +
        `<p><strong>Family policies (14) to auto-generate:</strong> Access Control, Awareness &amp; Training, Audit &amp; Accountability, Configuration Management, Identification &amp; Authentication, Incident Response, Maintenance, Media Protection, Personnel Security, Physical Protection, Risk Assessment, Security Assessment, System &amp; Communications Protection, System &amp; Information Integrity. Plus the master SSP and POA&amp;M.</p>` +
        (byca.length ? `<p><strong>Documentation-only controls (Met on document delivery):</strong></p>` + renderTable(['Control', 'Title', 'Deliverable'], byca.map((c) => [c.controlId, c.title, c.action])) : ''),
    },
    {
      id: 'cursor', heading: `Cursor — technical configuration (${cursor.length})`,
      bodyHtml:
        `<p>Controls whose remaining work is a system configuration change, executable with credential/network access. Route to Cursor. MYCA supplies the accompanying documentation.</p>` +
        renderTable(['Control', 'Title', 'Wt', 'Status', 'Configuration action'], remRows(cursor)),
    },
    {
      id: 'morgan', heading: `Morgan — procurement / physical / human (${morgan.length})`,
      bodyHtml:
        `<p>Controls requiring a purchase, a physical action, training, or a human decision. Only Morgan can complete these. MYCA supplies the documentation; Morgan performs the action and provides evidence.</p>` +
        renderTable(['Control', 'Title', 'Wt', 'Status', 'Action'], remRows(morgan)),
    },
  ];

  const doc: ReportDocument = {
    classification: 'CUI',
    title: 'CMMC Level 2 — Remediation Plan (owner-classified)',
    subtitle: 'Automated documentation + technical & human punch-lists · NIST SP 800-171 Rev. 2',
    org: { legalName: 'Mycosoft, LLC', uei: 'YK3ARVKJ77S9', cage: '9KR60', sao: 'Morgan Rockcoons', site: '451 Acero Pl, Chula Vista, CA 91910' },
    docControl: {
      number: `MYC-SEC-REMED-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`,
      date: now.toISOString().slice(0, 10), version: '1.0',
      distribution: 'Internal — Mycosoft compliance. Handle as CUI.', preparedBy: 'MYCA Reports Agent',
    },
    sections,
    generatedBy: provider ? `MYCA Reports Agent · ${provider.provider} ${provider.model}` : 'MYCA Reports Agent · data-only',
  };

  return {
    html: renderReportHtml(doc),
    meta: {
      reportType: 'remediation-plan',
      total: all.length, myca: byca.length, cursor: cursor.length, morgan: morgan.length,
      criticalPath: criticalPath.length,
      provider: provider?.provider ?? null, model: provider?.model ?? null,
      generatedAt: now.toISOString(),
    },
  };
}

/** Per-control remediation packet: LLM-generated SSP narrative + policy + evidence checklist. */
export async function buildControlPacket(controlId: string): Promise<{ html: string; meta: Record<string, unknown> } | null> {
  const ref = CMMC_L2_CONTROLS.find((c) => c.controlId === controlId || c.nistId === controlId);
  if (!ref) return null;
  const cls = classifyControl(ref);
  const plan = getRemediationPlan(ref.controlId, ref.family);
  const provider = activeReportProvider();
  const now = new Date();

  const facts =
    `Control: ${ref.controlId} — ${ref.title}\nFamily: ${ref.familyName}\nWeight: ${ref.weightMax ?? 'NA'}\nPOA&M-eligible: ${ref.poamEligible}\n` +
    `Objective: ${plan.objective}\nWhy it matters: ${plan.whyItMatters}\nTools/systems: ${plan.tools.join(', ')}\n` +
    `Implementation guidance: ${ref.guidance}\n` +
    (ref.assessmentObjectives?.length ? `Assessment objectives:\n${ref.assessmentObjectives.join('\n')}\n` : '') +
    `Mycosoft context: 2-user shop (Morgan, RJ); CUI enclave = PreVeil Gov Community (AWS GovCloud, FedRAMP Moderate Equivalent, FIPS 140-3); Google Workspace out of CUI boundary; Wazuh SIEM.`;

  const gen = await generateNarrative({
    system: 'You are a DoD compliance officer drafting the System Security Plan (SSP) implementation statement AND the governing policy for a single NIST SP 800-171 / CMMC L2 control, for a 2-person defense contractor using a PreVeil CUI enclave. Write two clearly-labeled sections: "SSP Implementation Statement" (how the control is implemented, present tense, specific to the described stack) and "Policy" (the organizational policy language). Government-standard, precise, factual. Do not invent evidence that does not exist; where implementation is pending, state the planned approach. Use only the provided facts.',
    user: `Draft the SSP implementation statement and policy for this control using ONLY these facts:\n\n${facts}`,
    maxTokens: 1400,
  });

  const bodyHtml = gen
    ? renderProse(gen.text)
    : renderProse(`**SSP Implementation Statement.** ${plan.objective}\n\n${ref.guidance}\n\n**Policy.** Mycosoft implements this control per the ${ref.familyName} policy using ${plan.tools.join(', ')}.\n\n*(No LLM configured — set PERPLEXITY_API_KEY for a fully-authored draft.)*`);

  const doc: ReportDocument = {
    classification: 'CUI',
    title: `${ref.controlId} — SSP & Policy`,
    subtitle: `${ref.title} · ${ref.familyName} · weight ${ref.weightMax ?? 'NA'}`,
    org: { legalName: 'Mycosoft, LLC', uei: 'YK3ARVKJ77S9', cage: '9KR60', sao: 'Morgan Rockcoons' },
    docControl: {
      number: `MYC-SEC-${ref.controlId}-${now.toISOString().slice(0, 10)}`,
      date: now.toISOString().slice(0, 10), version: '1.0', preparedBy: 'MYCA Reports Agent',
      distribution: 'Internal — CUI',
    },
    sections: [
      { id: 'doc', heading: 'SSP Implementation Statement & Policy', bodyHtml },
      { id: 'evidence', heading: 'Evidence required', bodyHtml: renderProse(plan.evidenceRequired.map((e) => `- ${e}`).join('\n')) },
      { id: 'accept', heading: 'Met when (acceptance criteria)', bodyHtml: renderProse(plan.acceptanceCriteria.map((a) => `- ${a}`).join('\n')) },
      { id: 'action', heading: 'Implementation action', bodyHtml: renderProse(`Owner: **${cls.owner.toUpperCase()}** · System: ${cls.system}\n\n${cls.action}`) },
    ],
    generatedBy: provider ? `MYCA Reports Agent · ${provider.provider} ${provider.model}` : 'MYCA Reports Agent · data-only',
  };

  return { html: renderReportHtml(doc), meta: { controlId: ref.controlId, owner: cls.owner, llmUsed: Boolean(gen), provider: provider?.provider ?? null } };
}
