import {
  THREAT_ASSESSMENT_SCHEMA,
  rankEnvironmentalAssessments,
  type CausalRelationship,
  type EnvironmentalAssessment,
  type ThreatAssessmentContext,
  type ThreatAssessmentSnapshot,
  type ThreatEvidence,
} from "./contracts"

export const THREAT_SCENARIO_ID = "scenario:harbor-glass-v1"
export const THREAT_SCENARIO_CLOCK = "2026-09-01T20:00:00.000Z"

const scenarioConfidence = (score: number, basis: string) => ({
  score,
  label: score >= 0.8 ? ("high" as const) : score >= 0.55 ? ("moderate" as const) : ("low" as const),
  basis,
})

const evidence: ThreatEvidence[] = [
  {
    id: "scenario:evidence-intake-optical",
    title: "SIMULATED intake optical series",
    summary: "Sanitized optical backscatter series shows a short pulse above the scenario baseline.",
    sourceId: "scenario:source-optical",
    sourceLabel: "SIMULATED optical probe",
    sourceRef: "scenario://harbor-glass/intake-optical",
    objectIds: ["scenario:object-intake-pulse"],
    observedAt: "2026-09-01T19:24:00.000Z",
    receivedAt: "2026-09-01T19:25:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.78, "Deterministic scenario sensor-quality rule."),
    integrityState: "verified",
    verificationState: "verified",
    lineage: ["Sanitized fixture", "Scenario transform v1", "Threat Assessment adapter"],
    conflictNote: "A simulated grab result is lower than the optical estimate; fouling remains a competing explanation.",
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-intake-grab",
    title: "SIMULATED intake grab result",
    summary: "Sanitized laboratory proxy confirms suspended material, at a lower magnitude than the optical estimate.",
    sourceId: "scenario:source-lab",
    sourceLabel: "SIMULATED field laboratory",
    sourceRef: "scenario://harbor-glass/intake-grab",
    objectIds: ["scenario:object-intake-pulse"],
    observedAt: "2026-09-01T18:52:00.000Z",
    receivedAt: "2026-09-01T19:41:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.86, "Deterministic scenario custody and method checks."),
    integrityState: "verified",
    verificationState: "verified",
    lineage: ["Sanitized sample fixture", "Scenario laboratory transform", "Threat Assessment adapter"],
    conflictNote: "Magnitude differs from the simulated optical series; timing and probe fouling require review.",
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-rain-window",
    title: "SIMULATED rainfall window",
    summary: "Sanitized rainfall sequence precedes the runoff and intake observations in the exercise clock.",
    sourceId: "scenario:source-weather",
    sourceLabel: "SIMULATED weather gauge",
    sourceRef: "scenario://harbor-glass/rain-window",
    objectIds: ["scenario:object-intake-pulse", "scenario:object-soil-saturation"],
    observedAt: "2026-09-01T17:35:00.000Z",
    receivedAt: "2026-09-01T17:36:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.93, "Deterministic fixture timing."),
    integrityState: "verified",
    verificationState: "verified",
    lineage: ["Sanitized weather fixture", "Scenario clock"],
    conflictNote: null,
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-soil-transect",
    title: "SIMULATED soil transect",
    summary: "Sanitized transect shows localized saturation near a maintenance corridor, with sparse spatial coverage.",
    sourceId: "scenario:source-soil",
    sourceLabel: "SIMULATED soil nodes",
    sourceRef: "scenario://harbor-glass/soil-transect",
    objectIds: ["scenario:object-soil-saturation", "scenario:object-drainage-route"],
    observedAt: "2026-09-01T19:05:00.000Z",
    receivedAt: "2026-09-01T19:07:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.61, "Scenario coverage penalty applied to a deterministic transect."),
    integrityState: "verified",
    verificationState: "pending",
    lineage: ["Sanitized soil fixture", "Scenario coverage transform"],
    conflictNote: null,
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-air-counter",
    title: "SIMULATED bioaerosol counter event",
    summary: "Sanitized counter signal rises briefly; the fixture does not assign taxonomy or hazard identity.",
    sourceId: "scenario:source-air",
    sourceLabel: "SIMULATED air sampler",
    sourceRef: "scenario://harbor-glass/air-counter",
    objectIds: ["scenario:object-bioaerosol-signal"],
    observedAt: "2026-09-01T19:12:00.000Z",
    receivedAt: "2026-09-01T19:13:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.42, "Scenario classifier intentionally lacks corroboration."),
    integrityState: "verified",
    verificationState: "pending",
    lineage: ["Sanitized counter fixture", "Scenario threshold transform"],
    conflictNote: "The simulated microscopy check does not corroborate the counter classification.",
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-air-microscopy",
    title: "SIMULATED microscopy check",
    summary: "Sanitized image review is inconclusive and does not corroborate the counter classification.",
    sourceId: "scenario:source-lab",
    sourceLabel: "SIMULATED field laboratory",
    sourceRef: "scenario://harbor-glass/air-microscopy",
    objectIds: ["scenario:object-bioaerosol-signal"],
    observedAt: "2026-09-01T19:38:00.000Z",
    receivedAt: "2026-09-01T19:50:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.35, "Scenario image quality is intentionally limited."),
    integrityState: "verified",
    verificationState: "pending",
    lineage: ["Sanitized image fixture", "Human-review scenario step"],
    conflictNote: "No corroborating morphology is present in the sanitized fixture.",
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:evidence-drainage-survey",
    title: "SIMULATED drainage survey",
    summary: "Sanitized survey documents a passive transport route between the upland corridor and receiving water.",
    sourceId: "scenario:source-survey",
    sourceLabel: "SIMULATED field survey",
    sourceRef: "scenario://harbor-glass/drainage-survey",
    objectIds: ["scenario:object-drainage-route", "scenario:object-intake-pulse"],
    observedAt: "2026-08-31T22:00:00.000Z",
    receivedAt: "2026-08-31T22:40:00.000Z",
    freshness: "simulated",
    confidence: scenarioConfidence(0.91, "Deterministic scenario survey record."),
    integrityState: "verified",
    verificationState: "verified",
    lineage: ["Sanitized survey fixture", "Scenario map transform"],
    conflictNote: null,
    dataMode: "simulated",
    synthetic: true,
  },
]

const relationships: CausalRelationship[] = [
  {
    id: "scenario:relationship-soil-runoff",
    fromObjectId: "scenario:object-soil-saturation",
    toObjectId: "scenario:object-intake-pulse",
    relationshipType: "may_contribute_to",
    label: "Saturated corridor may contribute sediment to receiving water",
    confidence: scenarioConfidence(0.64, "Scenario timing and spatial adjacency only."),
    evidenceIds: ["scenario:evidence-rain-window", "scenario:evidence-soil-transect"],
    explicitlyCausal: true,
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:relationship-drainage-transport",
    fromObjectId: "scenario:object-drainage-route",
    toObjectId: "scenario:object-intake-pulse",
    relationshipType: "supports_transport_path",
    label: "Surveyed drainage route supports a possible transport path",
    confidence: scenarioConfidence(0.72, "Scenario survey plus timing alignment."),
    evidenceIds: ["scenario:evidence-drainage-survey", "scenario:evidence-rain-window"],
    explicitlyCausal: false,
    dataMode: "simulated",
    synthetic: true,
  },
  {
    id: "scenario:relationship-air-independent",
    fromObjectId: "scenario:object-bioaerosol-signal",
    toObjectId: "scenario:object-soil-saturation",
    relationshipType: "no_supported_link",
    label: "No supported link in the sanitized evidence set",
    confidence: scenarioConfidence(0.29, "Purposefully weak scenario association."),
    evidenceIds: ["scenario:evidence-air-counter", "scenario:evidence-soil-transect"],
    explicitlyCausal: false,
    dataMode: "simulated",
    synthetic: true,
  },
]

const assessments: EnvironmentalAssessment[] = [
  {
    id: "scenario:assessment-intake-pulse",
    objectId: "scenario:object-intake-pulse",
    name: "Intake turbidity pulse",
    domain: "water",
    summary: "A short simulated suspended-material pulse is under review at a sanitized intake.",
    severity: "material",
    urgency: "within_6h",
    confidence: scenarioConfidence(0.74, "Scenario evidence synthesis; competing magnitude estimates remain."),
    uncertainty: "Magnitude and transport contribution remain uncertain because the optical and grab fixtures differ.",
    forecastHorizon: "6 scenario hours · widening uncertainty after 3 hours",
    affectedObjectIds: ["scenario:object-intake-pulse", "scenario:object-drainage-route"],
    affectedSystems: ["water", "infrastructure", "process"],
    missionConsequence: "Sampling access and intake verification may require a revised sequence in the exercise.",
    evidenceIds: [
      "scenario:evidence-intake-optical",
      "scenario:evidence-intake-grab",
      "scenario:evidence-rain-window",
      "scenario:evidence-drainage-survey",
    ],
    evidenceCompleteness: {
      state: "complete",
      declared: 4,
      resolved: 4,
      note: "All four evidence references in this scenario package resolve; agreement is still incomplete.",
    },
    freshness: "simulated",
    observedAt: "2026-09-01T19:24:00.000Z",
    sourceIds: ["scenario:source-optical", "scenario:source-lab", "scenario:source-weather"],
    relationshipIds: ["scenario:relationship-soil-runoff", "scenario:relationship-drainage-transport"],
    explanations: [
      {
        id: "scenario:explanation-runoff",
        label: "Rainfall-driven runoff pulse",
        kind: "causal",
        confidence: scenarioConfidence(0.64, "Scenario timing and transect evidence."),
        evidenceIds: ["scenario:evidence-rain-window", "scenario:evidence-soil-transect"],
        note: "Supported but not proven by the sanitized fixture.",
      },
      {
        id: "scenario:explanation-fouling",
        label: "Optical probe fouling",
        kind: "competing",
        confidence: scenarioConfidence(0.46, "Difference between simulated optical and grab magnitudes."),
        evidenceIds: ["scenario:evidence-intake-optical", "scenario:evidence-intake-grab"],
        note: "Remains viable until the scenario maintenance check is completed.",
      },
    ],
    review: {
      disposition: "Human review",
      backendState: "in_review",
      updatedAt: "2026-09-01T18:00:00.000Z",
      judgment: "Compare timing and probe condition before packaging the exercise conclusion.",
      mappingNote: "Scenario workflow state; no backend review record is created.",
    },
    changedSinceReview: true,
    changedSinceReviewNote: "The 19:24 scenario observation is later than the 18:00 scenario review.",
    evidenceConflict: "detected",
    evidenceConflictNote: "Optical and grab magnitude estimates differ in the sanitized fixture.",
    dataMode: "simulated",
    synthetic: true,
    rankBasis: ["Material condition", "Review within 6h", "Evidence conflict", "Changed since review"],
    contractGaps: [],
  },
  {
    id: "scenario:assessment-soil-saturation",
    objectId: "scenario:object-soil-saturation",
    name: "Localized soil saturation",
    domain: "land",
    summary: "A simulated wet-soil pocket overlaps a sanitized maintenance corridor.",
    severity: "watch",
    urgency: "within_24h",
    confidence: scenarioConfidence(0.61, "Sparse scenario transect with timing support."),
    uncertainty: "Spatial extent is unresolved outside the simulated transect.",
    forecastHorizon: "24 scenario hours · precipitation-dependent",
    affectedObjectIds: ["scenario:object-soil-saturation", "scenario:object-drainage-route"],
    affectedSystems: ["land", "infrastructure", "process"],
    missionConsequence: "Ground access may need field confirmation before the next exercise sampling window.",
    evidenceIds: ["scenario:evidence-soil-transect", "scenario:evidence-rain-window"],
    evidenceCompleteness: {
      state: "partial",
      declared: 3,
      resolved: 2,
      note: "A planned downstream transect is intentionally absent from the scenario package.",
    },
    freshness: "simulated",
    observedAt: "2026-09-01T19:05:00.000Z",
    sourceIds: ["scenario:source-soil", "scenario:source-weather"],
    relationshipIds: ["scenario:relationship-soil-runoff"],
    explanations: [
      {
        id: "scenario:explanation-infiltration",
        label: "Localized infiltration after rainfall",
        kind: "causal",
        confidence: scenarioConfidence(0.68, "Scenario rainfall timing and soil response."),
        evidenceIds: ["scenario:evidence-rain-window", "scenario:evidence-soil-transect"],
        note: "Scenario-supported explanation with incomplete spatial coverage.",
      },
    ],
    review: {
      disposition: "Evidence check",
      backendState: "pending",
      updatedAt: "2026-09-01T19:10:00.000Z",
      judgment: "Await the missing downstream transect in the exercise package.",
      mappingNote: "Scenario workflow state; no backend review record is created.",
    },
    changedSinceReview: false,
    changedSinceReviewNote: "No later scenario change exists after the 19:10 scenario review.",
    evidenceConflict: "unknown",
    evidenceConflictNote: "The scenario has no explicit conflict marker for this condition.",
    dataMode: "simulated",
    synthetic: true,
    rankBasis: ["Watch condition", "Review within 24h", "Partial evidence package"],
    contractGaps: [],
  },
  {
    id: "scenario:assessment-bioaerosol",
    objectId: "scenario:object-bioaerosol-signal",
    name: "Uncorroborated bioaerosol signal",
    domain: "atmosphere",
    summary: "A simulated counter event lacks corroborating morphology and remains unidentified.",
    severity: "unknown",
    urgency: "monitor",
    confidence: scenarioConfidence(0.38, "Two low-information scenario sources disagree."),
    uncertainty: "Identity, source, environmental relevance, and persistence are unresolved.",
    forecastHorizon: "Not assessed · scenario evidence is insufficient",
    affectedObjectIds: ["scenario:object-bioaerosol-signal"],
    affectedSystems: ["atmosphere", "living"],
    missionConsequence: null,
    evidenceIds: ["scenario:evidence-air-counter", "scenario:evidence-air-microscopy"],
    evidenceCompleteness: {
      state: "complete",
      declared: 2,
      resolved: 2,
      note: "Both scenario references resolve; they do not establish agreement or identity.",
    },
    freshness: "simulated",
    observedAt: "2026-09-01T19:12:00.000Z",
    sourceIds: ["scenario:source-air", "scenario:source-lab"],
    relationshipIds: ["scenario:relationship-air-independent"],
    explanations: [
      {
        id: "scenario:explanation-background",
        label: "Transient background particle event",
        kind: "competing",
        confidence: scenarioConfidence(0.44, "Inconclusive sanitized imagery."),
        evidenceIds: ["scenario:evidence-air-counter", "scenario:evidence-air-microscopy"],
        note: "One of several possible explanations; no identity is asserted.",
      },
    ],
    review: {
      disposition: "Draft",
      backendState: null,
      updatedAt: null,
      judgment: null,
      mappingNote: "No scenario review exists.",
    },
    changedSinceReview: null,
    changedSinceReviewNote: "No earlier scenario review exists for comparison.",
    evidenceConflict: "detected",
    evidenceConflictNote: "Counter classification is not corroborated by the simulated microscopy check.",
    dataMode: "simulated",
    synthetic: true,
    rankBasis: ["Severity unknown", "Evidence conflict", "Confidence low"],
    contractGaps: [],
  },
  {
    id: "scenario:assessment-drainage-route",
    objectId: "scenario:object-drainage-route",
    name: "Drainage transport pathway",
    domain: "process",
    summary: "A sanitized survey documents a passive pathway that could connect upland runoff to receiving water.",
    severity: "baseline",
    urgency: "monitor",
    confidence: scenarioConfidence(0.91, "Deterministic scenario survey record."),
    uncertainty: "Current flow contribution is not directly measured in the scenario.",
    forecastHorizon: "72 scenario hours · conditional on additional rainfall",
    affectedObjectIds: ["scenario:object-drainage-route", "scenario:object-intake-pulse"],
    affectedSystems: ["process", "water", "infrastructure"],
    missionConsequence: "Maintain the pathway in the approved exercise package as context, not as a confirmed cause.",
    evidenceIds: ["scenario:evidence-drainage-survey"],
    evidenceCompleteness: {
      state: "complete",
      declared: 1,
      resolved: 1,
      note: "The scenario package contains its declared survey record.",
    },
    freshness: "simulated",
    observedAt: "2026-08-31T22:00:00.000Z",
    sourceIds: ["scenario:source-survey"],
    relationshipIds: ["scenario:relationship-drainage-transport"],
    explanations: [
      {
        id: "scenario:explanation-pathway",
        label: "Passive transport pathway",
        kind: "context",
        confidence: scenarioConfidence(0.91, "Sanitized survey geometry."),
        evidenceIds: ["scenario:evidence-drainage-survey"],
        note: "Pathway presence is supported; contribution to the current pulse is not established.",
      },
    ],
    review: {
      disposition: "Approved package",
      backendState: "accepted",
      updatedAt: "2026-09-01T16:00:00.000Z",
      judgment: "Approved as contextual pathway evidence, not a confirmed causal conclusion.",
      mappingNote: "Scenario workflow state; no backend review record is created.",
    },
    changedSinceReview: false,
    changedSinceReviewNote: "No scenario change is later than the approved package review.",
    evidenceConflict: "unknown",
    evidenceConflictNote: "The scenario has no explicit conflict marker for this pathway record.",
    dataMode: "simulated",
    synthetic: true,
    rankBasis: ["Baseline context", "Approved package", "High-confidence pathway record"],
    contractGaps: [],
  },
]

export function buildSanitizedThreatScenario(
  suppliedContext: ThreatAssessmentContext,
): ThreatAssessmentSnapshot {
  const context: ThreatAssessmentContext = {
    ...suppliedContext,
    missionId: "scenario:mission-harbor-glass",
    missionLabel: "SANITIZED · Harbor Glass exercise",
    missionAreaId: "scenario:area-harbor-glass",
    missionAreaLabel: "SANITIZED · Estuary / upland interface",
    mode: "simulated",
    selectedAssessmentId: suppliedContext.selectedAssessmentId?.startsWith("scenario:")
      ? suppliedContext.selectedAssessmentId
      : null,
    selectedObjectId: suppliedContext.selectedObjectId?.startsWith("scenario:")
      ? suppliedContext.selectedObjectId
      : null,
    selectedEvidenceId: suppliedContext.selectedEvidenceId?.startsWith("scenario:")
      ? suppliedContext.selectedEvidenceId
      : null,
    selectedSourceId: suppliedContext.selectedSourceId?.startsWith("scenario:")
      ? suppliedContext.selectedSourceId
      : null,
  }

  return {
    schema: THREAT_ASSESSMENT_SCHEMA,
    context,
    generatedAt: THREAT_SCENARIO_CLOCK,
    condition: "simulated",
    classification: "UNCLASSIFIED",
    identityMode: "scenario_fixture_no_identity",
    identityVerified: null,
    assessments: rankEnvironmentalAssessments(assessments),
    evidence: evidence.map((item) => ({ ...item })),
    relationships: relationships.map((item) => ({ ...item })),
    history: [
      {
        id: "scenario:activity-optical",
        occurredAt: "2026-09-01T19:25:00.000Z",
        label: "SIMULATED evidence received",
        detail: "Optical series entered the sanitized exercise workspace.",
        objectIds: ["scenario:object-intake-pulse"],
        evidenceIds: ["scenario:evidence-intake-optical"],
        mode: "simulated",
        synthetic: true,
      },
      {
        id: "scenario:activity-conflict",
        occurredAt: "2026-09-01T19:50:00.000Z",
        label: "SIMULATED evidence conflict marked",
        detail: "The sanitized microscopy check did not corroborate the counter classification.",
        objectIds: ["scenario:object-bioaerosol-signal"],
        evidenceIds: ["scenario:evidence-air-counter", "scenario:evidence-air-microscopy"],
        mode: "simulated",
        synthetic: true,
      },
      {
        id: "scenario:activity-package",
        occurredAt: "2026-09-01T16:00:00.000Z",
        label: "SIMULATED package approved",
        detail: "Drainage pathway accepted as context only; causality was not asserted.",
        objectIds: ["scenario:object-drainage-route"],
        evidenceIds: ["scenario:evidence-drainage-survey"],
        mode: "simulated",
        synthetic: true,
      },
    ],
    sourceTruth: [
      {
        id: "scenario:fixture",
        label: "Sanitized Harbor Glass fixture",
        endpoint: `local://${THREAT_SCENARIO_ID}`,
        method: "LOCAL",
        reachability: "reached",
        identity: "not_required",
        schema: "valid",
        freshness: "simulated",
        provenance: "complete",
        coverage: "complete",
        dataPresence: "present",
        httpStatus: null,
        recordCount: assessments.length,
        receivedAt: THREAT_SCENARIO_CLOCK,
        note: "SIMULATED only. The fixture is deterministic, sanitized, and never merged with operational collections.",
        synthetic: true,
      },
    ],
    gaps: [
      "Scenario values are workflow fixtures, not operational measurements or forecasts.",
      "No records, reviews, messages, or handoffs are written by this scenario.",
      "The runtime demo endpoint is intentionally not queried so scenario and operational state cannot mix.",
    ],
    note: "SIMULATED · sanitized environmental-hazard investigation exercise.",
  }
}
