import {
  OEI_NARRATIVE_SCHEMA,
  type OeiClaim,
  type OeiContext,
  type OeiNarrativeSnapshot,
  type OeiNarrativeVersion,
  type OeiPublicationRecord,
  type OeiSourceAssessment,
  type V1ActivityRecord,
  type V1Confidence,
  type V1EnvironmentalObject,
  type V1EnvironmentalRelationship,
  type V1EvidenceRecord,
  type V1Mission,
  type V1MissionArea,
  type V1MissionContext,
  type V1ReviewItem,
} from "./contracts"

const SCENARIO_TIME = "2026-09-01T18:00:00.000Z"
const SCENARIO_RECEIVED = "2026-09-01T18:04:00.000Z"

const confidence = (score: number | null, basis: string): V1Confidence => ({
  score,
  label: score === null ? "not_assessed" : score >= 0.8 ? "high" : score >= 0.55 ? "moderate" : "low",
  basis,
})

function demoObject(
  value: Omit<
    V1EnvironmentalObject,
    "namespace" | "missionId" | "missionAreaId" | "temporalBounds" | "freshness" | "dataMode" | "synthetic" | "revision" | "classification"
  >,
): V1EnvironmentalObject {
  return {
    ...value,
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    missionAreaId: "demo.area.alpha-7",
    temporalBounds: { start: SCENARIO_TIME, end: null },
    freshness: {
      observedAt: SCENARIO_TIME,
      receivedAt: SCENARIO_RECEIVED,
      staleAfterSeconds: null,
      state: "simulated",
      basis: "scenario_clock",
    },
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    classification: "UNCLASSIFIED",
  }
}

function demoEvidence(
  value: Omit<
    V1EvidenceRecord,
    "namespace" | "missionId" | "missionAreaId" | "observedAt" | "receivedAt" | "dataMode" | "synthetic" | "revision" | "classification"
  >,
): V1EvidenceRecord {
  return {
    ...value,
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    missionAreaId: "demo.area.alpha-7",
    observedAt: SCENARIO_TIME,
    receivedAt: SCENARIO_RECEIVED,
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    classification: "UNCLASSIFIED",
  }
}

const objects: V1EnvironmentalObject[] = [
  demoObject({
    id: "demo.object.water-conductivity",
    objectType: "change",
    domain: "water",
    name: "Drainage conductivity change",
    summary: "The sanitized exercise record reports a localized conductivity departure during two scenario observation cycles.",
    spatialBounds: { label: "Sanitized grid A7-D02", boundingBox: { west: -0.62, south: -0.38, east: -0.42, north: -0.18 } },
    status: "material",
    relationshipIds: ["demo.relationship.transport"],
    changes: [
      {
        id: "demo.change.conductivity",
        field: "conductivity",
        direction: "rising",
        previousValue: "scenario baseline band",
        currentValue: "above scenario baseline band",
        unit: null,
        observedAt: SCENARIO_TIME,
        evidenceIds: ["demo.evidence.water-01", "demo.evidence.water-02"],
        classification: "UNCLASSIFIED",
      },
    ],
    trend: "rising",
    missionConsequence: "The exercise briefing should preserve the localized water-path uncertainty until a confirmatory observation resolves it.",
    confidence: confidence(0.78, "Two synthetic observation records agree inside the deterministic scenario; this is not operational confidence."),
    sourceIds: ["demo.source.water-01", "demo.source.water-02"],
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.water-02"],
    provenanceRef: "scenario://oei-alpha-7/water-conductivity",
  }),
  demoObject({
    id: "demo.object.soil-moisture",
    objectType: "change",
    domain: "land",
    name: "Soil-moisture co-change",
    summary: "The sanitized exercise record reports a concurrent soil-moisture change in the adjacent scenario grid cell.",
    spatialBounds: { label: "Sanitized grid A7-C04", boundingBox: { west: -0.36, south: -0.04, east: -0.16, north: 0.16 } },
    status: "watch",
    relationshipIds: ["demo.relationship.transport", "demo.relationship.infrastructure"],
    changes: [
      {
        id: "demo.change.soil-moisture",
        field: "soil moisture",
        direction: "rising",
        previousValue: "scenario reference band",
        currentValue: "above scenario reference band",
        unit: null,
        observedAt: SCENARIO_TIME,
        evidenceIds: ["demo.evidence.soil-01"],
        classification: "UNCLASSIFIED",
      },
    ],
    trend: "rising",
    missionConsequence: "The co-change supports a transport hypothesis but does not establish cause or source identity.",
    confidence: confidence(0.69, "One synthetic soil record plus spatial concurrence; causal evidence is intentionally incomplete."),
    sourceIds: ["demo.source.soil-01"],
    evidenceIds: ["demo.evidence.soil-01"],
    provenanceRef: "scenario://oei-alpha-7/soil-moisture",
  }),
  demoObject({
    id: "demo.object.culvert-c",
    objectType: "area",
    domain: "infrastructure",
    name: "Service culvert C",
    summary: "The sanitized exercise geometry places drainage infrastructure between the two reported environmental changes.",
    spatialBounds: { label: "Sanitized corridor C", boundingBox: { west: -0.12, south: -0.22, east: 0.08, north: -0.02 } },
    status: "unknown",
    relationshipIds: ["demo.relationship.infrastructure"],
    changes: [],
    trend: "not_assessed",
    missionConsequence: "Infrastructure involvement remains a competing explanation, not an accepted finding.",
    confidence: confidence(null, "No inference score is assigned to exercise geometry."),
    sourceIds: ["demo.source.area-plan"],
    evidenceIds: ["demo.evidence.area-plan"],
    provenanceRef: "scenario://oei-alpha-7/area-plan",
  }),
  demoObject({
    id: "demo.object.living-systems-gap",
    objectType: "area",
    domain: "living",
    name: "Living-systems coverage gap",
    summary: "No sanitized living-systems observation is supplied for the scenario interval.",
    spatialBounds: null,
    status: "unavailable",
    relationshipIds: [],
    changes: [],
    trend: "not_assessed",
    missionConsequence: "The briefing cannot characterize biological effect or ecological consequence from this scenario evidence set.",
    confidence: confidence(null, "No evidence or scored inference is available."),
    sourceIds: [],
    evidenceIds: [],
    provenanceRef: "scenario://oei-alpha-7/declared-gap",
  }),
]

const relationships: V1EnvironmentalRelationship[] = [
  {
    id: "demo.relationship.transport",
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    fromObjectId: "demo.object.soil-moisture",
    toObjectId: "demo.object.water-conductivity",
    relationshipType: "spatial_temporal_cochange",
    label: "Co-located change may share a transport process",
    confidence: confidence(0.63, "Synthetic co-location and timing only; no causal proof."),
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.soil-01"],
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    classification: "UNCLASSIFIED",
  },
  {
    id: "demo.relationship.infrastructure",
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    fromObjectId: "demo.object.soil-moisture",
    toObjectId: "demo.object.culvert-c",
    relationshipType: "adjacent_to",
    label: "Change is adjacent to mapped exercise infrastructure",
    confidence: confidence(null, "Direct deterministic scenario geometry; no inference score applies."),
    evidenceIds: ["demo.evidence.soil-01", "demo.evidence.area-plan"],
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    classification: "UNCLASSIFIED",
  },
]

const evidence: V1EvidenceRecord[] = [
  demoEvidence({
    id: "demo.evidence.water-01",
    objectIds: ["demo.object.water-conductivity"],
    sourceId: "demo.source.water-01",
    title: "Synthetic conductivity observation 01",
    summary: "Deterministic scenario observation for the first reported conductivity departure.",
    sourceRef: "scenario://oei-alpha-7/source/water-01",
    lineage: { sourceRecordIds: ["demo.record.water-01"], parentEvidenceIds: [], transformations: [] },
    confidence: confidence(0.8, "Deterministic scenario record quality; not an operational confidence score."),
    confidenceBasis: "Synthetic fixture quality only.",
    integrityState: "verified",
    verificationState: "verified",
    integrityRef: "scenario://oei-alpha-7/integrity/water-01",
    metadata: { sanitized: true, exerciseOnly: true },
  }),
  demoEvidence({
    id: "demo.evidence.water-02",
    objectIds: ["demo.object.water-conductivity"],
    sourceId: "demo.source.water-02",
    title: "Synthetic conductivity observation 02",
    summary: "Deterministic scenario corroboration from a second synthetic observation cycle.",
    sourceRef: "scenario://oei-alpha-7/source/water-02",
    lineage: { sourceRecordIds: ["demo.record.water-02"], parentEvidenceIds: [], transformations: [] },
    confidence: confidence(0.76, "Deterministic scenario record quality; not an operational confidence score."),
    confidenceBasis: "Synthetic fixture quality only.",
    integrityState: "verified",
    verificationState: "verified",
    integrityRef: "scenario://oei-alpha-7/integrity/water-02",
    metadata: { sanitized: true, exerciseOnly: true },
  }),
  demoEvidence({
    id: "demo.evidence.soil-01",
    objectIds: ["demo.object.soil-moisture"],
    sourceId: "demo.source.soil-01",
    title: "Synthetic soil-moisture observation",
    summary: "Deterministic scenario observation for the adjacent soil-condition change.",
    sourceRef: "scenario://oei-alpha-7/source/soil-01",
    lineage: { sourceRecordIds: ["demo.record.soil-01"], parentEvidenceIds: [], transformations: [] },
    confidence: confidence(0.69, "Single synthetic source with no independent soil corroboration."),
    confidenceBasis: "Synthetic fixture quality only.",
    integrityState: "verified",
    verificationState: "pending",
    integrityRef: "scenario://oei-alpha-7/integrity/soil-01",
    metadata: { sanitized: true, exerciseOnly: true },
  }),
  demoEvidence({
    id: "demo.evidence.area-plan",
    objectIds: ["demo.object.culvert-c"],
    sourceId: "demo.source.area-plan",
    title: "Synthetic sanitized area plan",
    summary: "Deterministic exercise geometry naming corridor C and service culvert C.",
    sourceRef: "scenario://oei-alpha-7/source/area-plan",
    lineage: { sourceRecordIds: ["demo.record.area-plan"], parentEvidenceIds: [], transformations: [] },
    confidence: confidence(null, "Direct scenario geometry; no inference score applies."),
    confidenceBasis: "No scored inference.",
    integrityState: "verified",
    verificationState: "verified",
    integrityRef: "scenario://oei-alpha-7/integrity/area-plan",
    metadata: { sanitized: true, exerciseOnly: true },
  }),
]

const currentClaims: OeiClaim[] = [
  {
    id: "demo.claim.localized-change",
    text: "Two sanitized water observations report a localized conductivity departure during the exercise interval.",
    objectIds: ["demo.object.water-conductivity"],
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.water-02"],
    confidence: confidence(0.78, "Claim confidence is bounded by the two linked synthetic observations."),
    uncertainty: "The synthetic evidence does not identify a source or establish environmental effect.",
    caveats: ["Exercise-only record", "No operational coordinates", "No biological-effect evidence"],
    competingExplanations: ["Routine drainage variability", "Synthetic sensor calibration drift"],
    changedSincePrevious: false,
    authoringBasis: "sanitized_fixture",
  },
  {
    id: "demo.claim.transport-hypothesis",
    text: "The water and soil co-change may be consistent with a localized transport process near mapped exercise infrastructure.",
    objectIds: ["demo.object.water-conductivity", "demo.object.soil-moisture", "demo.object.culvert-c"],
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.soil-01", "demo.evidence.area-plan"],
    confidence: confidence(0.63, "Synthetic co-location and timing support a working hypothesis, not causation."),
    uncertainty: "Causal direction and source identity are unresolved.",
    caveats: ["Soil evidence verification remains pending"],
    competingExplanations: ["Unrelated concurrent changes", "Calibration drift plus normal drainage variability"],
    changedSincePrevious: true,
    authoringBasis: "sanitized_fixture",
  },
  {
    id: "demo.claim.biological-effect",
    text: "Living-system effects are present in the exercise area.",
    objectIds: ["demo.object.living-systems-gap"],
    evidenceIds: [],
    confidence: confidence(null, "No living-systems evidence is supplied."),
    uncertainty: "No living-systems observation is available.",
    caveats: ["Unsupported claim included intentionally to demonstrate the evidence gate"],
    competingExplanations: [],
    changedSincePrevious: true,
    authoringBasis: "sanitized_fixture",
  },
]

const versions: OeiNarrativeVersion[] = [
  {
    id: "demo.version.001",
    ordinal: 1,
    label: "Approved scenario baseline",
    createdAt: "2026-09-01T17:20:00.000Z",
    createdBy: "demo.reviewer.river",
    stage: "approved_package",
    title: "Sanitized environmental continuity brief 001",
    executiveSummary: "The scenario baseline recorded a localized water change and retained source identity as unresolved.",
    claims: [currentClaims[0]],
    immutable: true,
    synthetic: true,
  },
  {
    id: "demo.version.002",
    ordinal: 2,
    label: "Current scenario draft",
    createdAt: SCENARIO_RECEIVED,
    createdBy: "demo.analyst.fern",
    stage: "evidence_check",
    title: "Sanitized environmental continuity brief 002",
    executiveSummary: "The current exercise draft adds a soil co-change and infrastructure hypothesis while preserving a living-systems evidence gap.",
    claims: currentClaims,
    immutable: false,
    synthetic: true,
  },
]

const publicationHistory: OeiPublicationRecord[] = [
  {
    id: "demo.publication.001",
    versionId: "demo.version.001",
    packageLabel: "Scenario package preview 001",
    approvedAt: "2026-09-01T17:30:00.000Z",
    approvedBy: "demo.reviewer.river",
    releaseMarking: "UNCLASSIFIED",
    releaseScope: "PREVIEW ONLY · NO EXTERNAL DELIVERY",
    immutable: true,
    synthetic: true,
  },
]

const reviews: V1ReviewItem[] = [
  {
    id: "demo.review.evidence-002",
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    kind: "evidence",
    state: "in_review",
    objectIds: ["demo.object.soil-moisture"],
    evidenceIds: ["demo.evidence.soil-01"],
    requestedBy: "demo.analyst.fern",
    assignedTo: "demo.reviewer.river",
    judgment: "Confirm whether the synthetic soil record is sufficient for the transport-hypothesis caveat.",
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    createdAt: "2026-09-01T18:02:00.000Z",
    updatedAt: "2026-09-01T18:02:00.000Z",
    classification: "UNCLASSIFIED",
  },
  {
    id: "demo.review.judgment-002",
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    kind: "environmental_judgment",
    state: "pending",
    objectIds: ["demo.object.water-conductivity", "demo.object.soil-moisture"],
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.water-02", "demo.evidence.soil-01"],
    requestedBy: "demo.analyst.fern",
    assignedTo: "demo.reviewer.river",
    judgment: null,
    dataMode: "simulated",
    synthetic: true,
    revision: 1,
    createdAt: "2026-09-01T18:03:00.000Z",
    updatedAt: "2026-09-01T18:03:00.000Z",
    classification: "UNCLASSIFIED",
  },
]

const activity: V1ActivityRecord[] = [
  {
    id: "demo.activity.001",
    sequence: 1,
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    missionContextId: "demo.context.alpha-7",
    actorId: "demo.analyst.fern",
    actorRole: "analyst",
    occurredAt: "2026-09-01T17:45:00.000Z",
    actionType: "object_selected",
    objectIds: ["demo.object.water-conductivity"],
    evidenceIds: [],
    beforeState: null,
    afterState: { selectedObjectId: "demo.object.water-conductivity" },
    judgment: null,
    auditMetadata: { scenario: true },
    dataMode: "simulated",
    appendOnly: true,
    classification: "UNCLASSIFIED",
  },
  {
    id: "demo.activity.002",
    sequence: 2,
    namespace: "demo",
    missionId: "demo.mission.alpha-7",
    missionContextId: "demo.context.alpha-7",
    actorId: "demo.analyst.fern",
    actorRole: "analyst",
    occurredAt: "2026-09-01T18:03:00.000Z",
    actionType: "review_created",
    objectIds: ["demo.object.water-conductivity", "demo.object.soil-moisture"],
    evidenceIds: ["demo.evidence.water-01", "demo.evidence.water-02", "demo.evidence.soil-01"],
    beforeState: null,
    afterState: { reviewId: "demo.review.judgment-002", state: "pending" },
    judgment: null,
    auditMetadata: { scenario: true },
    dataMode: "simulated",
    appendOnly: true,
    classification: "UNCLASSIFIED",
  },
]

export function buildSanitizedNarrativeScenario(
  incoming: OeiContext,
  upstreamSources: readonly OeiSourceAssessment[] = [],
): OeiNarrativeSnapshot {
  const context: OeiContext = {
    ...incoming,
    missionId: "demo.mission.alpha-7",
    missionLabel: "Sanitized watershed continuity exercise",
    contextId: "demo.context.alpha-7",
    missionAreaId: "demo.area.alpha-7",
    missionAreaLabel: "Training Area ALPHA-7 · sanitized grid",
    mode: "simulated",
    selectedObjectId: incoming.selectedObjectId ?? "demo.object.water-conductivity",
    selectedEvidenceId: incoming.selectedEvidenceId ?? "demo.evidence.water-01",
    selectedSourceId: incoming.selectedSourceId ?? "demo.source.water-01",
  }
  const mission: V1Mission = {
    id: context.missionId,
    namespace: "demo",
    name: context.missionLabel,
    description: "Deterministic sanitized exercise. No operational measurement or mission is represented.",
    status: "active",
    selectedContextId: context.contextId,
    revision: 1,
    createdAt: "2026-09-01T17:00:00.000Z",
    updatedAt: SCENARIO_RECEIVED,
    classification: "UNCLASSIFIED",
  }
  const missionArea: V1MissionArea = {
    id: context.missionAreaId,
    namespace: "demo",
    name: context.missionAreaLabel,
    description: "Sanitized normalized exercise coordinates only.",
    bounds: { label: context.missionAreaLabel, boundingBox: { west: -1, south: -1, east: 1, north: 1 } },
    revision: 1,
    createdAt: "2026-09-01T17:00:00.000Z",
    updatedAt: SCENARIO_RECEIVED,
    classification: "UNCLASSIFIED",
  }
  const missionContext: V1MissionContext = {
    id: context.contextId!,
    namespace: "demo",
    missionId: context.missionId,
    missionAreaId: context.missionAreaId,
    missionAreaLabel: context.missionAreaLabel,
    timeRange: { start: "2026-09-01T12:00:00.000Z", end: SCENARIO_RECEIVED },
    timeWindow: context.timeWindow,
    dataMode: "simulated",
    selectedObjectId: context.selectedObjectId,
    selectedEvidenceId: context.selectedEvidenceId,
    selectedSourceId: context.selectedSourceId,
    sourceApplication: "oei-narrative",
    operatorId: context.operatorId,
    operatorRole: context.role,
    revision: 1,
    createdAt: "2026-09-01T17:00:00.000Z",
    updatedAt: SCENARIO_RECEIVED,
    classification: "UNCLASSIFIED",
  }
  const localSource: OeiSourceAssessment = {
    id: "oei-sanitized-fixture",
    label: "OEI sanitized scenario fixture",
    endpoint: "local://fusarium/oei-narrative/sanitized-scenario",
    transport: "not_applicable",
    httpStatus: null,
    identityMode: "scenario_fixture",
    identityVerified: false,
    schema: "valid",
    freshness: "not_applicable",
    provenance: "present",
    coverage: "partial",
    dataPresence: "present",
    receivedAt: SCENARIO_RECEIVED,
    observedAt: SCENARIO_TIME,
    recordCount: objects.length + evidence.length + relationships.length,
    synthetic: true,
    note: "Deterministic browser fixture. It is not a network endpoint and carries no operational measurement.",
  }
  return {
    schema: OEI_NARRATIVE_SCHEMA,
    context,
    condition: "simulated",
    generatedAt: SCENARIO_RECEIVED,
    identityMode: "scenario_fixture",
    identityVerified: false,
    persistence: "sanitized_fixture",
    persistenceNote: "Scenario versions and package history are fixed preview fixtures. They are not durable operational publications.",
    mission,
    missionArea,
    missionContext,
    availableMissions: [mission],
    availableMissionAreas: [missionArea],
    availableContexts: [missionContext],
    sourceRecords: [],
    objects,
    relationships,
    evidence,
    reviews,
    activity,
    handoffs: [],
    claims: currentClaims,
    versions,
    publicationHistory,
    sources: [...upstreamSources, localSource],
    gaps: [
      "Living-systems coverage is intentionally absent.",
      "No operational coordinates, people, organizations, devices, or infrastructure are represented.",
      "External delivery, export, and publication are disabled; package history is preview-only.",
      "The unsupported biological-effect claim remains blocked to exercise the evidence gate.",
    ],
    note: "SIMULATED · SANITIZED · OPT-IN. Every object, relationship, claim, review, and package record on this surface is synthetic.",
  }
}
