UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.4.3','CM.L2-3.4.3'); -- evidence in evidence/cm
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.11.1','RA.L2-3.11.1'); -- evidence in evidence/ra
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.11.2','RA.L2-3.11.2'); -- evidence in evidence/ra
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.11.3','RA.L2-3.11.3'); -- evidence in evidence/ra
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.12.1','CA.L2-3.12.1'); -- evidence in evidence/ca
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.12.2','CA.L2-3.12.2'); -- evidence in evidence/ca
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.12.3','CA.L2-3.12.3'); -- evidence in evidence/ca
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.12.4','CA.L2-3.12.4'); -- evidence in evidence/ca
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.13.15','SC.L2-3.13.15'); -- evidence in evidence/sc
UPDATE soc_ops.compliance_controls SET implementation_state='implemented', last_verified_at=NOW() WHERE control_id IN ('3.14.1','SI.L2-3.14.1'); -- evidence in evidence/si
