/**
 * CMMC L2 closure-board guidance.
 *
 * STATIC knowledge only: the 2026-07-28 baseline set of 57 Partial requirements,
 * their wave assignment, owner, and the specific action that closes each one.
 *
 * NOTHING here is state. Implementation status, points, SPRS and the §170.21
 * gates are all derived at request time from live MAS in
 * app/api/security/closure-board/route.ts. When Cursor transitions a control the
 * board reflects it on the next load — no edit to this file is required.
 *
 * Weights and POA&M eligibility carried here are the verified DoD Assessment
 * Methodology v1.2.1 Annex A values from lib/security/reference/cmmc-l2-controls.json;
 * the route re-reads them from that file and treats it as authoritative.
 */

export type ClosureWave = 1 | 2 | 3 | 4 | 5;

export interface ClosureGuidance {
  /** CMMC practice id, e.g. "AC.L2-3.1.12" */
  id: string;
  /** DoD Annex A weight (1 / 3 / 5) */
  weight: number;
  /** false = cannot sit on a POA&M under 32 CFR §170.21 */
  poamEligible: boolean;
  wave: ClosureWave;
  waveKey: string;
  waveLabel: string;
  owner: string;
  title: string;
  /** HTML-bearing guidance string; rendered via dangerouslySetInnerHTML in the panel. */
  action: string;
}

export const CLOSURE_WAVES: Record<ClosureWave, { key: string; label: string; owner: string; blurb: string }> = {
  1: { key: 'determinations', label: 'Signed determinations', owner: 'SAO',
       blurb: 'Turned on a scoping or applicability decision only the SAO could make. Technical facts were already captured; what was missing was a signed document stating the decision and its basis.' },
  2: { key: 'repoint', label: 'Re-point to filed evidence', owner: 'Cursor',
       blurb: 'Evidence already sat in a registered, hash-addressed artifact while the requirement still pointed at policy:XX. Objective-mapping and re-registration, not collection.' },
  3: { key: 'technical', label: 'Technical work + capture', owner: 'Cursor / endpoint window',
       blurb: 'Needs a genuine configuration change or a capture that does not exist yet. Several share a single run across the three VMs and two endpoints.' },
  4: { key: 'programme', label: 'Programme and external', owner: 'SAO / Cursor',
       blurb: 'Depends on something outside the estate: a provider setting, an export, a screening decision, or a cryptographic determination.' },
  5: { key: 'operating', label: 'Operating history', owner: 'SAO — performed reviews',
       blurb: 'Satisfied by a dated, performed review, assessment, or handled incident. Retention is source material; the performed review is the evidence. Never a fabricated series.' },
};

/** The 2026-07-28 baseline: 57 requirements that were Partial, worth 147 points. */
export const CLOSURE_BASELINE: ClosureGuidance[] = [
  { id: "AC.L2-3.1.16", weight: 5, poamEligible: false, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Authorize wireless access prior to allowing connections", action: "<b>SIGNED 2026-07-28</b> — <code>EV-AC-3.1.16-WIRELESS-AUTH</code>, SHA-256 <code>62CCAA93…</code>. The gate was closed by real collection, not waived: an authenticated UniFi session returned <b>4 adopted online APs</b> with model, MAC, firmware and adoption state, UniFi Network <code>10.4.57</code> on a Dream Machine Pro Max, and <code>MYCO-ENCLAVE</code> confirmed broadcasting. No credential or PSK reproduced. <b>Awaiting Cursor transition.</b> One thing to pre-empt: the controller reports security as <code>wpapsk</code> while the endpoint captures evidence WPA3-Personal (H2E) — the record cites both, and the register entry should carry that reconciliation." },
  { id: "AC.L2-3.1.18", weight: 5, poamEligible: false, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Control connection of mobile devices", action: "<b>SIGNED 2026-07-28</b> — <code>EV-AC-3.1.18-MOBILE-SCOPE</code>, SHA-256 <code>BB9F0E3F…</code>. Handheld devices determined out of boundary; the two enclave laptops stay in as authorized portable platforms under <code>AC.L2-3.1.19</code>. The policy correction is now <b>self-executing on signature</b> rather than a separate re-issue. <b>Read before transitioning:</b> the signed document states it <i>\"does not state or imply that AC.L2-3.1.18 is Met\"</i>, and its objective [c] was written as Partial pending the wireless evidence — which now exists. Decide deliberately and record the reasoning; do not transition silently past a document that declines the claim." },
  { id: "MP.L2-3.8.3", weight: 5, poamEligible: false, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Sanitize or destroy media containing CUI before disposal", action: "Adopt a NIST SP 800-88 sanitization procedure and sign a determination that <b>no media has been disposed of or released to date</b>. Five points for one adopted procedure plus a factual statement. Currently the single largest document-only win on the board." },
  { id: "MP.L2-3.8.8", weight: 3, poamEligible: false, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Prohibit portable storage devices with no identifiable owner", action: "The technical control already exists and is registered — removable-disk deny on class <code>{53f5630d}</code>, carrying MP.L2-3.8.7. This needs the matching policy statement plus that same capture cited as the enforcing mechanism." },
  { id: "AC.L2-3.1.20", weight: 1, poamEligible: false, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Verify and control connections to external systems", action: "PreVeil device-bound enrollment is the enforcing control — an unenrolled machine cannot authenticate. Needs a determination naming the permitted external systems and citing the PreVeil device list." },
  { id: "AC.L2-3.1.21", weight: 1, poamEligible: true, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Limit use of portable storage on external systems", action: "Same removable-storage capture plus a one-paragraph determination. Pairs naturally with MP.L2-3.8.8 — write them together." },
  { id: "MP.L2-3.8.4", weight: 1, poamEligible: true, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Mark media with necessary CUI markings", action: "A marking procedure plus the determination already signed as <code>EV-SAO-CUI-DET-001</code>: no CUI exists in the environment, so no media requires marking. The procedure must exist for when that changes." },
  { id: "PE.L2-3.10.6", weight: 1, poamEligible: true, wave: 1, waveKey: "determinations", waveLabel: "Signed determinations", owner: "SAO", title: "Safeguarding measures for CUI at alternate work sites", action: "Determination: are there alternate work sites? If the enclave laptops leave the Chula Vista facility, the safeguards travelling with them — BitLocker TPM+PIN, PreVeil device binding, the safe — are the answer, and they are already evidenced." },
  { id: "SC.L2-3.13.2", weight: 5, poamEligible: false, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Architectural designs and engineering principles for security", action: "The signed 119-page SSP (<code>EV-CA-SSP-001</code>) documents exactly this and is already filed and hash-verified. Re-point from <code>policy:SC</code> to the SSP section that carries the architecture narrative. <b>Five points for a registration change.</b>" },
  { id: "SI.L2-3.14.1", weight: 5, poamEligible: false, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Identify, report, and correct system flaws in a timely manner", action: "Both endpoints now have dated hotfix captures registered today — MYCO-ENCL-02 and MYCO-ENCL-01, hostname in frame — plus apt upgrade on all three VMs. The remaining objective is the <b>defined remediation window</b>: adopt the SI advisory-triage procedure draft, which is written but unadopted." },
  { id: "MP.L2-3.8.1", weight: 3, poamEligible: false, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Protect system media containing CUI", action: "Assemble one media-protection packet from artifacts already filed: safe custody, BitLocker To Go on both sticks, removable-disk deny, key-protector IDs. All of it exists; none of it is mapped to this requirement." },
  { id: "MP.L2-3.8.2", weight: 3, poamEligible: false, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Limit access to CUI on media to authorized users", action: "Same packet. Access is limited to two named individuals with sole safe access — already asserted in the identity inventory that flipped six requirements tonight." },
  { id: "AC.L2-3.1.10", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Session lock with pattern-hiding display", action: "The endpoint capture already records the 900-second machine inactivity lock, and <code>standby-timeout-ac 15</code> was confirmed applied on both endpoints today. Re-point from <code>policy:AC</code>. Optionally set <code>ScreenSaverIsSecure</code>, which is currently unset on both, though the 900s lock carries the requirement without it." },
  { id: "IA.L2-3.5.7", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Minimum password complexity and change of characters", action: "<code>minLen 14</code> on the Windows endpoints and <code>minlen=14</code> in the Linux PAM capture. Both are filed. Re-point." },
  { id: "IA.L2-3.5.8", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Prohibit password reuse for a specified number of generations", action: "Password history 24 in the endpoint capture. Filed. Re-point." },
  { id: "IA.L2-3.5.11", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Obscure feedback of authentication information", action: "Standard behaviour on all five in-scope systems and visible in the captures. Re-point with a one-line basis statement." },
  { id: "MP.L2-3.8.5", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Control access to media during transport outside controlled areas", action: "The sealed-envelope and safe-custody arrangement is the transport control. Fold into the same media packet as 3.8.1/3.8.2." },
  { id: "MP.L2-3.8.6", weight: 1, poamEligible: true, wave: 2, waveKey: "repoint", waveLabel: "Re-point to filed evidence", owner: "Cursor", title: "Cryptographic mechanisms to protect CUI on digital media", action: "Both USB sticks confirmed BitLocker To Go encrypted, registered today. Re-point." },
  { id: "CM.L2-3.4.8", weight: 5, poamEligible: false, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Deny-by-exception (blacklisting) or permit-by-exception policy", action: "<b>Two of three objectives signed.</b> <code>EV-CM-3.4.8-ALLOWLIST-POLICY-JUL30</code> supplies [a] the approach specified &mdash; allowlisting &mdash; and [b] the authorized software set. <b>[c] needs the endpoint window:</b> AppLocker or WDAC in <b>audit mode first</b>, because enforce on a two-person estate with no test ring can lock out both users at once. Capture <code>Get-AppLockerPolicy -Effective -Xml</code>, <code>AppIDSvc</code> state, and the AppLocker event log. Register the partial objective mapping now." },
  { id: "IA.L2-3.5.10", weight: 5, poamEligible: false, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Store and transmit only cryptographically-protected passwords", action: "Verify and capture: Linux <code>/etc/shadow</code> hash algorithm across all three VMs, Windows credential storage, and PreVeil transport. Likely already true everywhere — it needs proving, not fixing." },
  { id: "SI.L2-3.14.5", weight: 3, poamEligible: false, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Periodic and real-time scans of files from external sources", action: "<b>CLOSED.</b> All five systems completed full scans &mdash; Windows 2026-07-28, all three Linux hosts 2026-07-29 with zero infections, banked as <code>EV-SI-3.14.5-CLAMAV-FULLSCANS-JUL29</code>, then registered once periodic scheduling and real-time coverage were also evidenced. Cursor held it Partial through two passes for the right reason before closing it on complete evidence. Original detail: Windows 2026-07-28; all three Linux hosts completed ClamAV full scans 2026-07-29 with <b>zero infections</b>, banked as <code>EV-SI-3.14.5-CLAMAV-FULLSCANS-JUL29</code>. Cursor held it Partial for the right reason: one completed scan evidences neither <i>periodic</i> scheduling nor <i>real-time</i> scanning of files from external sources. Close path: enable <code>clamav-freshclam</code> + a scheduled scan timer on the VMs (capture <code>systemctl list-timers</code>), cite Defender real-time protection on the endpoints, register the combined packet." },
  { id: "SI.L2-3.14.7", weight: 3, poamEligible: false, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Identify unauthorized use of organizational systems", action: "<b>[a] signed.</b> <code>EV-SI-3.14.7-AUTHORIZED-USE-JUL30</code> defines authorized use across the five in-scope systems. <b>[b] needs the ENCL Wazuh agents enrolled and reporting</b> &mdash; the UniFi 1514-1515 rule is approved and is <i>not</i> the blocker. Evidence is enrolment, not service state: require <code>client.keys</code> present and <code>ossec-agent.state</code> reading <code>status=connected</code>. Verify the MSI hash before installing and stage to local disk; do not weaken the removable-storage policy to work around 1619." },
  { id: "AC.L2-3.1.8", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Limit unsuccessful logon attempts", action: "Windows is done — lockout 5/30 in the capture. <b>The three VMs have no <code>pam_faillock</code></b>, so the requirement is evidenced on two of five systems. Cursor configures, then re-captures." },
  { id: "AC.L2-3.1.11", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Terminate user sessions after defined conditions", action: "Set an idle <code>TMOUT</code> on the three VMs and confirm endpoint session termination, then capture." },
  { id: "AU.L2-3.3.6", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Audit record reduction and report generation", action: "<b>CLOSED — and the dispute resolved the right way.</b> The capability-based reading prevailed: <code>EV-AU-3.3.6-WAZUH-CAPABILITY-JUL29</code> demonstrates the live manager providing record reduction and on-demand reporting — 347 retained alerts, 61 audit-related, agents 000/001/002 active. Registered explicitly as a capability decision, not a cadence claim. The earlier demotion for manufacturing cadence stands as the counter-example of how not to close it." },
  { id: "CM.L2-3.4.9", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Control and monitor user-installed software", action: "Pairs with CM.L2-3.4.8 — the same AppLocker/WDAC work and the same capture run." },
  { id: "IA.L2-3.5.5", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Prevent reuse of identifiers for a defined period", action: "Needs the period defined in policy plus an account capture showing no reuse. Small." },
  { id: "IA.L2-3.5.6", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Disable identifiers after a defined period of inactivity", action: "Define the period and configure it, then capture. Two humans and a handful of NPEs make this trivially demonstrable." },
  { id: "IA.L2-3.5.9", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Allow temporary password use only with immediate change", action: "Policy statement plus configuration evidence." },
  { id: "MP.L2-3.8.9", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Protect confidentiality of backup CUI at storage locations", action: "Requires backup evidence that does not currently exist. Determine the backup arrangement first, then evidence it." },
  { id: "SC.L2-3.13.3", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Separate user functionality from system management functionality", action: "Capture the separation on the VMs and endpoints." },
  { id: "SC.L2-3.13.4", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Prevent unauthorized information transfer via shared resources", action: "Configuration capture." },
  { id: "SC.L2-3.13.7", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Prevent split tunnelling on remote devices", action: "UniFi plus endpoint capture. Fast if bundled with the SC capture run." },
  { id: "SC.L2-3.13.9", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Terminate network connections associated with communications sessions", action: "Idle-timeout configuration and capture. Pairs with AC.L2-3.1.11." },
  { id: "SC.L2-3.13.10", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Establish and manage cryptographic keys", action: "Write the key-management procedure covering BitLocker recovery keys, the key-protector IDs captured today, PreVeil, and SSH. Mostly documentation of practice already in place." },
  { id: "SC.L2-3.13.12", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Prohibit remote activation of collaborative computing devices", action: "Camera and microphone policy plus endpoint configuration capture." },
  { id: "SC.L2-3.13.13", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Control and monitor use of mobile code", action: "Browser and endpoint configuration capture plus a policy statement." },
  { id: "SC.L2-3.13.14", weight: 1, poamEligible: true, wave: 3, waveKey: "technical", waveLabel: "Technical work + capture", owner: "Cursor / endpoint window", title: "Control and monitor use of Voice over Internet Protocol", action: "Most likely a determination that VoIP is not used in the boundary. Confirm before writing." },
  { id: "AC.L2-3.1.12", weight: 5, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Monitor and control remote access sessions", action: "<b>Scope settled: remote access EXISTS.</b> The SAO confirmed external reach, so this is required — not N/A. The enumeration found a remote-user VPN network <code>phone</code> and a Cloudflare Tunnel on Sandbox&nbsp;.187; no destination-NAT rules. <b>Objective [d] is where this fails if it fails:</b> proving sessions are <i>monitored</i> needs a log that exists, is retained, and is reviewed — not a firewall rule. UniFi connection logs plus auditd are the candidate; Wazuh on .188 is the aggregation point once endpoint agents enrol. Last of the four to close." },
  { id: "AC.L2-3.1.13", weight: 5, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Cryptographic mechanisms to protect remote access sessions", action: "<b>Strongest of the four and likely the first to close.</b> <code>EV-SSH-KEYONLY-AFTERSTATE-JUL28</code> already establishes <code>passwordauthentication no</code> on all three VMs as effective running config. Add the <code>sshd -T</code> ciphers/MACs/KEX capture, plus the negotiated cipher suite for the <code>phone</code> VPN and the documented transport for the Cloudflare tunnel." },
  { id: "AT.L2-3.2.1", weight: 5, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Security awareness for managers, administrators, and users", action: "The filed JUL21 artifact is a partial leg. Needs an organization-wide programme with role-based content and completion records for both people." },
  { id: "AT.L2-3.2.2", weight: 5, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Personnel trained to carry out assigned security duties", action: "Same programme. Ten points sit in AT and three of its requirements are POA&M-ineligible — the largest recoverable block outside the elapsed-time band." },
  { id: "IA.L2-3.5.3", weight: 5, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Multifactor authentication for local and network access", action: "Google Workspace and GitHub are enforced and phishing-resistant. The blocker is the documented <code>apps@mycosoft.org</code> 2SV gap plus source-stamped administrator exports. Note the dual-value rule: partial MFA deducts 3, absent MFA deducts 5." },
  { id: "SC.L2-3.13.11", weight: 5, poamEligible: true, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "FIPS-validated cryptography", action: "<b>The only five-point requirement on this board that is POA&amp;M-eligible</b> — it can be deferred without blocking Conditional status. Needs a determination on FIPS mode across BitLocker, PreVeil, and TLS." },
  { id: "CA.L2-3.12.2", weight: 3, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Plans of action to correct deficiencies", action: "The registered POA&amp;M source is stale. Regenerate from live posture so it reflects 52/57/1 and tonight's transitions, then file and register the new one." },
  { id: "PS.L2-3.9.1", weight: 3, poamEligible: false, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Screen individuals prior to authorizing CUI access", action: "A Tier-1 background check PDF is filed but is not a complete screening decision record. Needs the decision, the authorizing official, and the date for both individuals." },
  { id: "AC.L2-3.1.14", weight: 1, poamEligible: true, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Route remote access through managed access control points", action: "<b>Currently NOT satisfiable, and the reason is concrete.</b> The UDM at <code>192.168.0.1</code> is meant to be the single managed ingress, but the Cloudflare Tunnel on Sandbox&nbsp;.187 dials outbound to create inbound reachability — it never traverses the UDM. Map the tunnel and either bring it under the managed point or shut it down. Until then this requirement is false as written." },
  { id: "AC.L2-3.1.15", weight: 1, poamEligible: true, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Authorize remote execution of privileged commands", action: "Key-only SSH supports it, <b>but the privilege model must be corrected first.</b> <code>mycosoft</code> holds root-equivalent access through <code>docker</code> and <code>lxd</code> group membership, outside the sudo model the current evidence describes. If either is reachable over a remote path, privileged remote execution exists through a route nothing documents. Do not sign this objective until the superseding privilege artifact is filed." },
  { id: "AT.L2-3.2.3", weight: 1, poamEligible: true, wave: 4, waveKey: "programme", waveLabel: "Programme and external", owner: "SAO / Cursor", title: "Security awareness training on recognizing insider threat", action: "Part of the same training programme build." },
  { id: "AU.L2-3.3.3", weight: 1, poamEligible: true, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Review and update logged events", action: "Requires a performed review series at the defined cadence." },
  { id: "AU.L2-3.3.4", weight: 1, poamEligible: true, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Alert in the event of an audit logging process failure", action: "<code>EV-WAZUH-007</code> records a real agent-stop alert test, which strengthens but does not close this." },
  { id: "AU.L2-3.3.5", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Correlate audit review, analysis, and reporting for investigation", action: "Needs correlated review records over time." },
  { id: "CA.L2-3.12.1", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Periodically assess security controls", action: "<b>SIGNED, awaiting registration.</b> <code>EV-CA-3.12.1-ASSESSMENT-FREQUENCY-JUL30</code>. [a] quarterly frequency defined. [b] Cycle One performed 2026-07-28 to 07-30 &mdash; all 110 requirements evaluated against filed evidence, every transition artifact-gated, honest Partials retained; products are REGISTER.json and the live posture. <b>Objective [b] says <i>assessed with the defined frequency</i>, not <i>assessed repeatedly</i></b> &mdash; one assessment inside a defined quarter satisfies it. Register as cycle one, never as a series. Confirm the §3.1 counts table survived conversion first." },
  { id: "CA.L2-3.12.3", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Monitor security controls on an ongoing basis", action: "The SOC operating-history collector began 2026-07-28 and is the mechanism that will eventually satisfy this." },
  { id: "IR.L2-3.6.1", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Operational incident-handling capability", action: "<b>SIGNED, awaiting registration.</b> <code>EV-IR-3.6.1-CAPABILITY-MAPPING-JUL30</code>. Seven objectives, all capability-shaped &mdash; none requires elapsed time. [a][b] IR policy + runbook · [c] Wazuh manager, agents 000/001/002, <code>EV-WAZUH-007</code> alert test · [d] the credential-rotation analysis and non-CUI classification · [e] rotation and legacy-file removal · [f] incident <code>db0bc1a1</code> resolved · [g] runbook user-reporting section. <b>One handled incident plus a documented capability is exactly what these objectives ask for.</b>" },
  { id: "IR.L2-3.6.2", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Track, document, and report incidents", action: "<b>SIGNED, awaiting registration.</b> <code>EV-IR-3.6.2-REPORTING-AUTHORITIES-JUL30</code>. [a][b] already evidenced by MAS <code>/api/incidents</code> and the filed records · [c] the determination names DIBNet and the reporting authorities · [d] the SAO · [f] the rotation event was reported and handled. <b>[e] registers as &ldquo;no reportable incident has occurred&rdquo;</b> on <code>EV-SAO-CUI-DET-001</code> &mdash; no CUI, no covered contract, so no DIBNet obligation has arisen. That is the honest state, not a gap." },
  { id: "SI.L2-3.14.3", weight: 5, poamEligible: false, wave: 5, waveKey: "operating", waveLabel: "Operating history", owner: "SAO — performed reviews", title: "Monitor security alerts and advisories and act on them", action: "<b>SIGNED, awaiting registration.</b> <code>EV-SI-3.14.3-ADVISORY-RESPONSE-JUL30</code>. <b>[c] was already evidenced before the document existed</b> &mdash; KB5121767, KB5101650, KB5120102, KB5095189, KB5050575 across both endpoints plus apt upgrade on all three VMs, dated 07-26 to 07-28. That is action taken in response to vendor advisories. The determination supplies [a] defined response actions and [b] the monitored source list &mdash; CISA KEV, Windows Update, Defender, apt feeds, Ubiquiti/PreVeil/Wazuh advisories." },
];

export const BASELINE_COUNT = 57;
export const BASELINE_POINTS = 147;
export const BASELINE_DATE = '2026-07-28';
/** Projected SPRS at baseline: 110 − 147. Recorded so progress has a fixed origin. */
export const BASELINE_SPRS = -37;

export const GUIDANCE_BY_ID: Record<string, ClosureGuidance> =
  Object.fromEntries(CLOSURE_BASELINE.map((r) => [r.id, r]));
