import {
  DOMAIN_LABELS,
  SITUATIONAL_AWARENESS_SCHEMA,
  confidenceLabel,
  type DomainState,
  type EnvironmentalObject,
  type EvidenceRecord,
  type SituationalContext,
  type SituationalSnapshot,
  type SourceStatus,
} from "./contracts"

const isoBefore = (nowMs: number, minutes: number) => new Date(nowMs - minutes * 60_000).toISOString()
const isoAfter = (nowMs: number, minutes: number) => new Date(nowMs + minutes * 60_000).toISOString()

function evidence(
  id: string,
  title: string,
  sourceId: string,
  sourceLabel: string,
  summary: string,
  observedAt: string,
  receivedAt: string,
  confidence: number,
  lineage: string[],
): EvidenceRecord {
  return {
    id,
    title,
    sourceId,
    sourceLabel,
    sourceRef: `scenario://sanitized/${id}`,
    summary,
    observedAt,
    receivedAt,
    confidence,
    confidenceLabel: confidenceLabel(confidence),
    freshness: "simulated",
    staleAfterSeconds: null,
    freshnessBasis: "SIMULATED scenario clock; no live freshness claim.",
    lineage,
    classification: "UNCLASSIFIED",
    synthetic: true,
  }
}

function scenarioObject(
  object: Omit<EnvironmentalObject, "classification" | "receivedAt" | "freshness" | "staleAfterSeconds" | "freshnessBasis" | "synthetic">,
  receivedAt: string,
): EnvironmentalObject {
  return {
    ...object,
    receivedAt,
    freshness: "simulated",
    staleAfterSeconds: null,
    freshnessBasis: "SIMULATED scenario clock; no live freshness claim.",
    classification: "UNCLASSIFIED",
    synthetic: true,
  }
}

export function applySanitizedScenario(
  base: SituationalSnapshot,
  context: SituationalContext,
  nowMs = Date.now(),
): SituationalSnapshot {
  const now = new Date(nowMs).toISOString()
  const scenarioEvidence: EvidenceRecord[] = [
    evidence(
      "sim-evidence-weather-07",
      "Atmospheric replay frame 07",
      "sim-weather-replay",
      "Sanitized weather replay",
      "Modelled moisture convergence with an explicitly synthetic observation clock.",
      isoBefore(nowMs, 12),
      now,
      0.86,
      ["Sanitized training archive", "Replay transform v1", "Fieldboard scenario adapter"],
    ),
    evidence(
      "sim-evidence-water-12",
      "Surface-water proxy series",
      "sim-water-node",
      "Synthetic watershed node",
      "Turbidity and surface-flow proxies generated for workflow demonstration only.",
      isoBefore(nowMs, 18),
      now,
      0.72,
      ["Deterministic scenario seed", "Proxy series", "Fieldboard scenario adapter"],
    ),
    evidence(
      "sim-evidence-soil-03",
      "Soil moisture replay",
      "sim-soil-array",
      "Synthetic soil array",
      "A sanitized moisture trend replay; it is not attached to deployed hardware.",
      isoBefore(nowMs, 24),
      now,
      0.79,
      ["Sanitized training archive", "Soil replay transform", "Fieldboard scenario adapter"],
    ),
    evidence(
      "sim-evidence-living-19",
      "Living-system respiration proxy",
      "sim-bioelectric-grid",
      "Synthetic bioelectric grid",
      "A simulated living-system response correlated to moisture and runoff changes.",
      isoBefore(nowMs, 9),
      now,
      0.64,
      ["Deterministic scenario seed", "Correlation exercise", "Fieldboard scenario adapter"],
    ),
    evidence(
      "sim-evidence-culvert-04",
      "Culvert visual inspection replay",
      "sim-inspection-replay",
      "Sanitized inspection replay",
      "A training-only restriction indicator with no live camera or physical asset bind.",
      isoBefore(nowMs, 31),
      now,
      0.91,
      ["Sanitized image label", "Human-reviewed training annotation", "Fieldboard scenario adapter"],
    ),
  ]

  const scenarioObjects: EnvironmentalObject[] = [
    scenarioObject(
      {
        id: "sim-atmosphere-change-07",
        kind: "change",
        name: "Moisture convergence",
        domain: "atmosphere",
        summary: "A simulated convergence band is moving toward the west ridge watch area.",
        locationLabel: "West ridge",
        position: { x: 30, y: 27 },
        observedAt: isoBefore(nowMs, 12),
        confidence: 0.86,
        confidenceLabel: "high",
        severity: "material",
        trend: "rising",
        statusLabel: "SIMULATED CHANGE",
        sourceIds: ["sim-weather-replay"],
        evidenceIds: ["sim-evidence-weather-07"],
        relationshipIds: ["sim-rel-weather-runoff"],
        missionConsequence: "The next observation window may lose line-of-sight and comparable atmospheric conditions.",
        history: [
          { label: "−6h", value: 42, unit: "%", state: "simulated" },
          { label: "−3h", value: 51, unit: "%", state: "simulated" },
        ],
        current: { label: "Now", value: 63, unit: "%", state: "simulated" },
        forecast: [
          { label: "+3h", value: 70, unit: "%", state: "simulated" },
          { label: "+6h", value: 66, unit: "%", state: "simulated" },
        ],
      },
      now,
    ),
    scenarioObject(
      {
        id: "sim-water-change-12",
        kind: "change",
        name: "Surface-flow turbidity shift",
        domain: "water",
        summary: "Synthetic surface-water proxies cross the training watch band downstream of the ridge.",
        locationLabel: "Arroyo crossing",
        position: { x: 51, y: 57 },
        observedAt: isoBefore(nowMs, 18),
        confidence: 0.72,
        confidenceLabel: "moderate",
        severity: "watch",
        trend: "rising",
        statusLabel: "WATCH",
        sourceIds: ["sim-water-node"],
        evidenceIds: ["sim-evidence-water-12"],
        relationshipIds: ["sim-rel-weather-runoff", "sim-rel-runoff-culvert"],
        missionConsequence: "Sampling comparability is reduced until the simulated runoff pulse clears.",
        history: [
          { label: "−6h", value: 8, unit: "NTU", state: "simulated" },
          { label: "−3h", value: 11, unit: "NTU", state: "simulated" },
        ],
        current: { label: "Now", value: 16, unit: "NTU", state: "simulated" },
        forecast: [
          { label: "+3h", value: 21, unit: "NTU", state: "simulated" },
          { label: "+6h", value: 14, unit: "NTU", state: "simulated" },
        ],
      },
      now,
    ),
    scenarioObject(
      {
        id: "sim-land-change-03",
        kind: "change",
        name: "Soil moisture divergence",
        domain: "land",
        summary: "The simulated north plot is drying faster than its sanitized comparison baseline.",
        locationLabel: "North plot",
        position: { x: 69, y: 35 },
        observedAt: isoBefore(nowMs, 24),
        confidence: 0.79,
        confidenceLabel: "moderate",
        severity: "watch",
        trend: "falling",
        statusLabel: "DIVERGENCE",
        sourceIds: ["sim-soil-array"],
        evidenceIds: ["sim-evidence-soil-03"],
        relationshipIds: ["sim-rel-soil-living"],
        missionConsequence: "The north and south plot observations should not be treated as equivalent in the exercise.",
        history: [
          { label: "−6h", value: 34, unit: "%", state: "simulated" },
          { label: "−3h", value: 30, unit: "%", state: "simulated" },
        ],
        current: { label: "Now", value: 24, unit: "%", state: "simulated" },
        forecast: [{ label: "+6h", value: 21, unit: "%", state: "simulated" }],
      },
      now,
    ),
    scenarioObject(
      {
        id: "sim-living-change-19",
        kind: "change",
        name: "Respiration response",
        domain: "living",
        summary: "A simulated living-system response follows the soil divergence with moderate confidence.",
        locationLabel: "North plot colony",
        position: { x: 76, y: 43 },
        observedAt: isoBefore(nowMs, 9),
        confidence: 0.64,
        confidenceLabel: "moderate",
        severity: "material",
        trend: "falling",
        statusLabel: "CORRELATED RESPONSE",
        sourceIds: ["sim-bioelectric-grid"],
        evidenceIds: ["sim-evidence-living-19"],
        relationshipIds: ["sim-rel-soil-living"],
        missionConsequence: "Biological observations require a fresh field check before the exercise narrative is promoted.",
        history: [
          { label: "−6h", value: 1, unit: "index", state: "simulated" },
          { label: "−3h", value: 0.88, unit: "index", state: "simulated" },
        ],
        current: { label: "Now", value: 0.71, unit: "index", state: "simulated" },
        forecast: [{ label: "+6h", value: null, unit: "index", state: "unavailable" }],
      },
      now,
    ),
    scenarioObject(
      {
        id: "sim-infrastructure-change-04",
        kind: "change",
        name: "Culvert restriction indicator",
        domain: "infrastructure",
        summary: "The sanitized inspection replay marks a restriction in the exercise drainage path.",
        locationLabel: "Culvert 04",
        position: { x: 58, y: 72 },
        observedAt: isoBefore(nowMs, 31),
        confidence: 0.91,
        confidenceLabel: "high",
        severity: "urgent",
        trend: "steady",
        statusLabel: "REVIEW REQUIRED",
        sourceIds: ["sim-inspection-replay"],
        evidenceIds: ["sim-evidence-culvert-04"],
        relationshipIds: ["sim-rel-runoff-culvert"],
        missionConsequence: "The downstream access route remains a simulated watch item; no dispatch or external task was created.",
        history: [{ label: "−24h", value: 0.44, unit: "occlusion", state: "simulated" }],
        current: { label: "Now", value: 0.68, unit: "occlusion", state: "simulated" },
        forecast: [{ label: "+6h", value: null, unit: "occlusion", state: "unavailable" }],
      },
      now,
    ),
    scenarioObject(
      {
        id: "sim-process-runoff-01",
        kind: "process",
        name: "Runoff consequence chain",
        domain: "process",
        summary: "A simulated causal chain links moisture convergence, surface flow, and the drainage restriction.",
        locationLabel: "West ridge → arroyo → culvert",
        position: { x: 48, y: 45 },
        observedAt: isoBefore(nowMs, 6),
        confidence: 0.67,
        confidenceLabel: "moderate",
        severity: "material",
        trend: "rising",
        statusLabel: "CAUSAL HYPOTHESIS",
        sourceIds: ["sim-weather-replay", "sim-water-node", "sim-inspection-replay"],
        evidenceIds: ["sim-evidence-weather-07", "sim-evidence-water-12", "sim-evidence-culvert-04"],
        relationshipIds: ["sim-rel-weather-runoff", "sim-rel-runoff-culvert"],
        missionConsequence: "Treat the chain as a hypothesis until independent evidence corroborates each transition.",
        history: [],
        current: { label: "Now", value: 0.67, unit: "confidence", state: "simulated" },
        forecast: [{ label: isoAfter(nowMs, 180), value: 0.73, unit: "confidence", state: "simulated" }],
      },
      now,
    ),
  ]

  const scenarioSources: SourceStatus[] = [
    ["sim-weather-replay", "Sanitized weather replay", 1],
    ["sim-water-node", "Synthetic watershed node", 1],
    ["sim-soil-array", "Synthetic soil array", 1],
    ["sim-bioelectric-grid", "Synthetic bioelectric grid", 1],
    ["sim-inspection-replay", "Sanitized inspection replay", 1],
  ].map(([id, label, count]) => ({
    id: String(id),
    label: String(label),
    endpoint: `scenario://sanitized/${id}`,
    state: "simulated",
    httpStatus: null,
    receivedAt: now,
    observedAt: isoBefore(nowMs, 12),
    recordCount: Number(count),
    schemaValid: null,
    classificationAccepted: true,
    responseAccepted: false,
    synthetic: true,
    note: "SIMULATED · deterministic sanitized scenario source; no live bind.",
  }))

  const samples: Record<string, number[]> = {
    atmosphere: [42, 45, 51, 56, 63],
    water: [8, 8, 11, 13, 16],
    land: [36, 34, 30, 27, 24],
    living: [100, 96, 88, 79, 71],
    infrastructure: [44, 44, 52, 61, 68],
    process: [38, 45, 52, 61, 67],
  }
  const domainTrends: Record<string, DomainState["trend"]> = {
    atmosphere: "rising",
    water: "rising",
    land: "falling",
    living: "falling",
    infrastructure: "steady",
    process: "rising",
  }
  const scenarioDomains: DomainState[] = Object.keys(DOMAIN_LABELS).map((id) => ({
    id: id as DomainState["id"],
    label: DOMAIN_LABELS[id as DomainState["id"]],
    observedObjectCount: scenarioObjects.filter((object) => object.domain === id).length,
    coverage: "simulated",
    trend: domainTrends[id],
    samples: samples[id],
    note: "SIMULATED · sanitized scenario values only.",
  }))

  return {
    schema: SITUATIONAL_AWARENESS_SCHEMA,
    context,
    generatedAt: now,
    condition: "simulated",
    classification: "UNCLASSIFIED",
    sources: [...base.sources, ...scenarioSources],
    objects: [...base.objects, ...scenarioObjects],
    evidence: [...base.evidence, ...scenarioEvidence],
    relationships: [
      ...base.relationships,
      {
        id: "sim-rel-weather-runoff",
        fromId: "sim-atmosphere-change-07",
        toId: "sim-water-change-12",
        type: "may_drive",
        label: "may increase runoff",
        confidence: 0.68,
        evidenceIds: ["sim-evidence-weather-07", "sim-evidence-water-12"],
        synthetic: true,
      },
      {
        id: "sim-rel-runoff-culvert",
        fromId: "sim-water-change-12",
        toId: "sim-infrastructure-change-04",
        type: "constrained_by",
        label: "flow constrained by",
        confidence: 0.74,
        evidenceIds: ["sim-evidence-water-12", "sim-evidence-culvert-04"],
        synthetic: true,
      },
      {
        id: "sim-rel-soil-living",
        fromId: "sim-land-change-03",
        toId: "sim-living-change-19",
        type: "correlates_with",
        label: "correlates with response",
        confidence: 0.64,
        evidenceIds: ["sim-evidence-soil-03", "sim-evidence-living-19"],
        synthetic: true,
      },
    ],
    domains: scenarioDomains,
    watchAreas: [
      {
        id: "sim-watch-west-ridge",
        name: "West ridge watershed",
        description: "Training-only watch area; polygon is schematic and not a real operational boundary.",
        polygon: [
          { x: 17, y: 17 },
          { x: 76, y: 13 },
          { x: 86, y: 76 },
          { x: 42, y: 88 },
          { x: 14, y: 58 },
        ],
        status: "simulated",
        synthetic: true,
      },
    ],
    watchConditions: [
      {
        id: "sim-watch-condition-runoff",
        label: "Runoff corroboration",
        status: "simulated",
        rule: "Two independent sources confirm rising surface flow inside the exercise window.",
        consequence: "Escalate for human review in Threat Assessment; no automatic tasking or external send.",
        objectIds: ["sim-atmosphere-change-07", "sim-water-change-12"],
        synthetic: true,
      },
      {
        id: "sim-watch-condition-lineage",
        label: "Living-system lineage",
        status: "simulated",
        rule: "Respiration response remains below the sanitized baseline and receives field corroboration.",
        consequence: "Hold OEI narrative promotion until provenance is complete.",
        objectIds: ["sim-land-change-03", "sim-living-change-19"],
        synthetic: true,
      },
    ],
    gaps: [
      ...base.gaps,
      "SIMULATED scenario does not create backend records, tasks, watch areas, or external messages.",
      "Scenario geometry is schematic and must not be interpreted as a real coordinate boundary.",
    ],
    note: "SIMULATED · deterministic sanitized workflow scenario overlaid on the honest runtime state.",
  }
}
