import { metersPerPixel, getCellId, getViewportFromCenter } from './earth-grid.js';

const $ = (s,root=document)=>root.querySelector(s);
const esc = v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=3)=>n==null?'—':typeof n==='number'?n.toLocaleString(undefined,{maximumFractionDigits:d}):esc(n);
const pct=n=>n==null?'—':(n*100).toFixed(1)+'%';
const date=s=>new Date(s).toLocaleString();
const short=s=>s?String(s).slice(0,12)+'…':'—';
const state={boot:null,run:null,suite:null,page:location.hash.slice(1)||'overview',seed:11,scenario:'clean',dataset:'demo-11',job:null,guide:0,query:'',hits:[],datasetPreview:null,mapTime:100,mapObserved:false,mapHideStale:false,mapSelected:null,selectedSource:'all',constraints:null,probes:{},testFilter:'all'};
const navigation=[['overview','Overview','◫'],['walkthrough','Guided walkthrough','▷'],['data','Data & documents','▤'],['patterns','Pattern analysis','12'],['links','Link analysis','13'],['options','Courses of action','08'],['earth','Earth Simulator','14'],['formspace','Form Space','◎'],['tests','Test laboratory','✓'],['evidence','Evidence & export','⬡'],['integrations','System connections','⌘']];
const colors={native:'#c5a35b',baseline:'#a7b4a4',temporal:'#267253',fused:'#718eaa',classes:['#388565','#a6aa69','#7d92b1','#b78c6b']};
let toastTimer,pollTimer,searchTimer;

async function api(path,body){
  const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ITDX-Token':state.boot?.csrf_token||''},body:JSON.stringify(body)});
  const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;
}
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',6500);}
const tag=(text,kind='')=>`<span class="tag ${kind}">${esc(text)}</span>`;
const metric=(label,value,foot,icon='↗')=>`<div class="card metric-card"><div class="metric-label">${esc(label)}<span class="metric-icon">${icon}</span></div><div class="metric-value">${value}</div><div class="metric-foot">${esc(foot)}</div></div>`;
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}" class="muted">No records yet.</td></tr>`}</tbody></table></div>`;}
function header(eyebrow,title,subtitle,actions=''){return `<div class="page-header"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title='Run your first evaluation',text='Choose a dataset and scenario, then run the four tasks to generate inspectable results.'){return `<div class="card empty"><div class="empty-icon">◉</div><h3>${esc(title)}</h3><p>${esc(text)}</p><button class="primary" data-action="run">Run all four tasks</button></div>`;}
function exportButton(format='zip',label='Export evidence bundle'){return state.run?`<a class="button ${format==='zip'?'primary':''}" href="/api/export?id=${state.run.id}&format=${format}">${esc(label)} ↗</a>`:'';}
function runStrip(){if(!state.run)return '';const r=state.run;return `<div class="run-strip">${tag(r.config.data_mode,r.config.data_mode==='SYNTHETIC_TEST'?'warn':'blue')}<span class="mono">${esc(r.id)}</span><span>Seed ${r.config.seed}</span><span>${esc(r.config.scenario_id)}</span><span class="spacer"></span><span>${fmt(r.timing.total_seconds)} s measured</span><span>${r.dataset.records.toLocaleString()} records</span>${r.assessment?`<button data-action="assessment">${esc(r.assessment.status.replaceAll('_',' '))}</button>`:''}<button class="code-link" data-action="config">Inspect configuration</button></div>`;}
function controlPanel(){return `<div class="card mb"><div class="form-row"><div class="field"><label for="dataset-select">Input dataset</label><select id="dataset-select">${state.boot.datasets.map(d=>`<option value="${esc(d.id)}" ${d.id===state.dataset?'selected':''}>${esc(d.title)} · ${d.record_count} records</option>`).join('')}</select></div><div class="field"><label for="scenario-select">Scenario / fault injection</label><select id="scenario-select">${state.boot.scenarios.map(s=>`<option value="${esc(s.id)}" ${s.id===state.scenario?'selected':''}>${esc(s.id)} — ${esc(s.name)}</option>`).join('')}</select></div><div class="field compact"><label for="seed-select">Seed</label><select id="seed-select">${[11,17,23,29,31].map(s=>`<option ${s===state.seed?'selected':''}>${s}</option>`).join('')}</select></div><button data-action="constraints">Constraints</button><button class="primary" data-action="run" ${state.job?'disabled':''}>▶ Run all tasks</button></div><div class="small muted" style="margin-top:11px">${esc(state.boot.scenarios.find(s=>s.id===state.scenario)?.expected||'')} ${state.constraints?'Custom constraints are active.':''}</div></div>`;}

function lineChart(series,{height=220,labels=null,yMax=1,yLabel='score'}={}){
  const width=780,left=42,right=18,top=18,bottom=30,w=width-left-right,h=height-top-bottom;
  const longest=Math.max(1,...series.map(s=>s.values.length));let out=`<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(yLabel)} over the evaluation window">`;
  for(let i=0;i<=4;i++){const y=top+h*i/4;out+=`<line x1="${left}" x2="${width-right}" y1="${y}" y2="${y}" stroke="#e6ede3"/><text x="${left-8}" y="${y+3}" text-anchor="end">${fmt(yMax*(1-i/4),2)}</text>`;}
  series.forEach(s=>{let path='';s.values.forEach((v,i)=>{if(v==null)return;const x=left+w*i/Math.max(1,longest-1),y=top+h*(1-Math.max(0,Math.min(yMax,v))/yMax);path+=(path?' L':'M')+x.toFixed(2)+','+y.toFixed(2);});out+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2.2" stroke-linejoin="round" stroke-linecap="round"/>`;});
  for(let i=0;i<=4;i++){const index=Math.round((longest-1)*i/4);out+=`<text x="${left+w*i/4}" y="${height-9}" text-anchor="middle">${esc(labels?.[index]??index)}</text>`;}
  return out+'</svg>'+`<div class="legend">${series.map(s=>`<span><i class="legend-dot" style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div>`;
}
function patternChart(){if(!state.run)return '';const ps=state.run.task12.predictions.filter(p=>p.split==='test');const groups=new Map();ps.forEach(p=>{if(!groups.has(p.observed_at))groups.set(p.observed_at,[]);groups.get(p.observed_at).push(p);});const entries=[...groups].sort((a,b)=>a[0].localeCompare(b[0]));const avg=(ps,k)=>{const a=ps.map(p=>p[k]).filter(x=>x!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0;};return lineChart([{name:'Robust baseline',color:colors.baseline,values:entries.map(([t,ps])=>avg(ps,'baseline_score'))},{name:'Native NLM encoder',color:colors.native,values:entries.map(([t,ps])=>avg(ps,'native_score'))},{name:'Temporal readout',color:colors.temporal,values:entries.map(([t,ps])=>avg(ps,'probability'))}],{labels:entries.map(([t])=>new Date(t).toISOString().slice(11,16)),yLabel:'Mean source anomaly score'});}
function algorithmTable(group){return table(['Algorithm','N','Precision','Recall','F1','AP','Brier','Status'],Object.entries(group).map(([name,m])=>[esc(name.replaceAll('_',' ')),fmt(m.n),fmt(m.precision),fmt(m.recall),`<strong>${fmt(m.f1)}</strong>`,fmt(m.average_precision),fmt(m.brier),tag(m.status,m.status==='MEASURED'?'':'warn')]));}
function taskDetails(id){const t=state.boot.tasks.find(x=>x.id===id);return `<details><summary>Task requirements, algorithm and walkthrough details</summary><div class="divider"></div><p class="small"><strong>Question:</strong> ${esc(t.question)}</p><p class="small"><strong>Active algorithm:</strong> ${esc(t.algorithm)}</p><p class="small"><strong>Baseline:</strong> ${esc(t.baseline)}</p><ol class="bullet-list">${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p class="small muted">Internal task target: ${t.budget_s} seconds. Final Army criteria require confirmation.</p></details>`;}

function overview(){
 const r=state.run;return header('MYCOSOFT / INTELLIGENCE TECHNOLOGY DISCOVERY EXPERIMENT','Algorithm Lab','From observations to analyst products. One local, inspectable evaluation workspace.',`<button data-action="navigate" data-page="walkthrough">Guided walkthrough →</button>`)+
 `<div class="hero mb"><div class="eyebrow light">ITDX26 • Local demonstration environment</div><h2>Ground the observation.<br>Make the result inspectable.</h2><p>Run NLM pattern analysis, explore typed evidence, review MYCA options through AVANI, and carry the same state into Form Space and Earth Simulator.</p><div class="actions"><button class="primary" data-action="run" ${state.job?'disabled':''}>▶ Run the demonstration</button><button data-action="navigate" data-page="data">Explore data & documents</button>${tag('CPU • Offline by default')}${tag('Native Mycosoft modules')}</div></div>`+
 `<div class="grid four mb">${metric('Observation records',r?fmt(r.dataset.records):'960',r?'Frozen in the current run':'Built-in synthetic coastal fixture','◌')}${metric('Selected ITDX tasks','4','Patterns · Links · Options · Map','▦')}${metric('Measured runtime',r?fmt(r.timing.total_seconds)+' s':'—',r?'420 s internal integrated target':'Run to measure this machine','◷')}${metric('Evidence documents',String(state.boot.documents.length),'29 supplied sources + preparation brief','▤')}</div>`+
 controlPanel()+runStrip()+
 `<div class="grid wide-left mb"><div class="card"><div class="card-header"><div><h2>Observation to pattern</h2><p>Independent capture groups. Scores computed on held-out observations.</p></div>${tag(r?r.config.data_mode:'Ready to run','warn')}</div>${r?patternChart():`<div class="empty"><div class="empty-icon">∿</div><p>A run will plot the actual baseline, native encoder and learned readout outputs here.</p></div>`}</div><div class="card"><div class="card-header"><div><h2>Four analyst products</h2><p>One shared evidence record.</p></div></div>${state.boot.tasks.map(t=>`<div class="task-card"><div class="task-number">${t.id.padStart(2,'0')}</div><div><h3>${esc(t.name)}</h3><p>${esc(t.system)}</p></div>${tag(r?'Generated':'Ready',r?'':'gray')}</div>`).join('')}</div></div>`+
 `<div class="grid two"><div class="card"><div class="card-header"><div><h2>Evidence that travels with the result</h2><p>Versioned input, trained parameters and source-linked outputs.</p></div></div>${r?`<p class="small muted">Observation Merkle root</p><div class="hash-line mono mb">${r.proof.event_root}</div><div class="actions">${exportButton()}<button data-action="navigate" data-page="evidence">Verify an observation</button></div>`:`<p class="muted small">Every completed run generates an observation Merkle tree and a chained frame root. Exports include data, metrics, model parameters, reports and a standalone verifier.</p>`}</div><div class="card"><h2>Readiness is visible</h2><p class="small muted">The default run uses the native encoder, a small local readout, a deterministic typed graph and an advisory review loop. Full trained SSM/GNN/LLM services remain separately qualified integrations.</p><div class="actions"><button data-action="navigate" data-page="integrations">Inspect system connections</button><button data-action="navigate" data-page="tests">Open test laboratory</button></div></div></div>`;
}

const guideSteps=[['Prepare','Select the input and establish the evidence boundary.'],['Patterns','What changed, and when?'],['Links','What supports the relationship?'],['Options','Which choices satisfy the constraints?'],['Map & form','Where is the evidence, and what state does it represent?'],['Challenge','Make a failure visible.'],['Export','Hand over a reproducible result.']];
function walkthrough(){
 const [title,line]=guideSteps[state.guide];const r=state.run;const bodies=[
 `<p class="walk-brief">“We will identify what changed, inspect its relationships, compare constrained options, and show where the evidence applies. Every output will identify its data source, algorithm and uncertainty.”</p><div class="notice info">Choose a generated fixture or import your own observations. Synthetic replay is labeled throughout; source documents are reference evidence, not field measurements.</div>${controlPanel()}<div class="grid two"><div><h3>Before the run</h3><ul class="bullet-list"><li>Confirm the final slot and Army scenario.</li><li>Choose the data origin, seed and fault condition.</li><li>Review policy limits and model identity.</li></ul></div><div><h3>What the evaluator can inspect</h3><ul class="bullet-list"><li>All original source documents and extracted text.</li><li>Actual source modules and hashes.</li><li>Frozen train/validation/test capture boundaries.</li><li>Measured execution and untested requirements.</li></ul></div></div>`,
 r?`<p class="walk-brief">“This is the baseline, this is the native encoder, and this is the fitted temporal readout on the same held-out observations.”</p>${patternChart()}${algorithmTable(r.task12.metrics)}<button data-action="navigate" data-page="patterns">Inspect patterns and evidence →</button>`:empty(),
 r?`<p class="walk-brief">“These source edges are recorded. Corroboration links are inferred from concurrent, independent observations. We can remove a source and see what support disappears.”</p>${graphSVG()}${algorithmTable(r.task13.metrics)}<button data-action="navigate" data-page="links">Inspect the graph →</button>`:empty(),
 r?`<p class="walk-brief">“These are distinct options under an explicit goal and resource budget. AVANI’s verdict and each hard constraint are visible. A passing check still leaves the decision with the analyst.”</p>${table(['Option','Disposition','Native AVANI','Reason'],r.task8.options.map(o=>[esc(o.title),tag(o.status,o.status==='PASS'?'':o.status==='VETO'?'bad':'warn'),esc(o.native_avani.action),esc(o.reasons.join('; ')||'Declared checks satisfied')]))}<button data-action="navigate" data-page="options">Inspect proposals and review trace →</button>`:empty(),
 r?`<p class="walk-brief">“The map projects the same evidence. Form Space records a versioned partition of the native encoding, its uncertainty and distance from the declared reference state.”</p>${mapSVG()}<div class="actions" style="margin-top:15px"><button data-action="navigate" data-page="earth">Explore Earth Simulator →</button><button data-action="navigate" data-page="formspace">Explore Form Space →</button></div>`:empty(),
 `<p class="walk-brief">“Now we remove support or introduce a contradiction. The system should expose the changed evidence, gate an option, or report failure.”</p><div class="grid three mb">${[['S13-2','Remove a supporting source'],['S8-1','Make constraints impossible'],['D-3','Modify an authenticated record']].map(([id,name])=>`<div class="card"><h3>${esc(name)}</h3><p class="small muted">${esc(state.boot.scenarios.find(s=>s.id===id).expected)}</p><button data-action="run-scenario" data-scenario="${id}">Run ${id}</button></div>`).join('')}</div><div class="notice">Functional invariant checks, algorithm quality metrics and SME judgments are separate outcomes. A simulated network test is not a physical radio test.</div><button data-action="navigate" data-page="tests">Inspect all 41 cases →</button>`,
 r?`<p class="walk-brief">“Here are the exact inputs, model parameters, results, limitations and verification instructions. Our next evaluation should use an agreed Army scenario, rubric and independent replay.”</p><div class="grid two"><div class="card"><h3>Current run</h3><p class="mono small">${r.id}</p><div class="hash-line mono mb">${r.proof.frame_root}</div><div class="actions">${exportButton()}${exportButton('pdf','Download PDF report')}</div></div><div class="card"><h3>Independent verification</h3><pre class="code">python verify_bundle.py ${r.id}-evaluation.zip</pre><p class="small muted">For identity trust, pin the signing-key fingerprint separately. Hashes and signatures do not establish measurement truth.</p><button data-action="navigate" data-page="evidence">Review readiness and SME ratings →</button></div></div>`:empty()
 ];
 return header('PRESENTER MODE','Your guided demonstration','A deliberate walkthrough of inputs, algorithms, evidence, failure and export.')+`<div class="stepper">${guideSteps.map(([name],i)=>`<button class="step ${state.guide===i?'active':i<state.guide?'completed':''}" data-action="guide" data-step="${i}"><span>${String(i+1).padStart(2,'0')}</span>${name}</button>`).join('')}</div>${runStrip()}<div class="card"><div class="card-header"><div><div class="eyebrow">Step ${state.guide+1} of ${guideSteps.length}</div><h2>${esc(title)} / ${esc(line)}</h2></div>${tag('Suggested 25-minute format','gray')}</div>${bodies[state.guide]}<div class="divider"></div><div class="actions"><button data-action="guide" data-step="${Math.max(0,state.guide-1)}" ${state.guide===0?'disabled':''}>← Previous</button><button class="primary" data-action="guide" data-step="${Math.min(6,state.guide+1)}" ${state.guide===6?'disabled':''}>Next step →</button></div></div>`;
}

function patternsPage(){
 const r=state.run;if(!r)return header('TASK 12 / NLM','Pattern analysis','Inspect the actual input, baseline and temporal model result.')+empty();
 const t=r.task12,m=t.metrics.temporal_readout,test=t.predictions.filter(p=>p.split==='test');const sources=[...new Set(test.map(p=>p.source_id))];const selected=test.filter(p=>state.selectedSource==='all'||p.source_id===state.selectedSource).sort((a,b)=>(b.probability??-1)-(a.probability??-1));
 return header('TASK 12 / NATURE LEARNING MODEL','What changed, and when?','Native sensor encoding, a fitted temporal readout, and matched held-out comparisons.',exportButton('csv','Export metrics'))+runStrip()+
 `<div class="grid four mb">${metric('Held-out F1',fmt(m.f1),'Eligible held-out observations')}${metric('Precision / recall',`${fmt(m.precision,2)} / ${fmt(m.recall,2)}`,'Threshold fixed on validation captures')}${metric('Calibration error',fmt(m.ece),'10-bin expected calibration error')}${metric('Task execution',fmt(t.seconds)+' s','Model setup is reported separately','◷')}</div>`+
 `<div class="card mb"><div class="card-header"><div><h2>Model scores across the replay</h2><p>Mean score across available sources at each observation time.</p></div>${tag(t.abstained?t.abstained+' abstentions':'All schema-supported',t.abstained?'warn':'')}</div>${patternChart()}</div>`+
 `<div class="card mb"><div class="card-header"><div><h2>Baseline comparison</h2><p>All rows use the same eligible held-out observations and their separate scoring labels.</p></div>${tag(r.config.data_mode,'warn')}</div>${algorithmTable(t.metrics)}<p class="small muted" style="margin-top:12px">The native encoder anomaly score is a rule-based score. The small temporal readout was fitted in this app. Neither is represented as a trained SSM/Mamba foundation model.</p>${taskDetails('12')}</div>`+
 `<div class="grid two mb"><div class="card"><h2>Training trace</h2><p class="small muted">${r.model.training_records} training records · ${r.model.validation_records} validation records · ${r.model.trained_parameters} fitted parameters</p>${lineChart([{name:'Training log loss',color:colors.temporal,values:r.model.loss.map(x=>x.training_log_loss)}],{height:170,yMax:Math.max(.1,...r.model.loss.map(x=>x.training_log_loss)),labels:r.model.loss.map(x=>x.epoch),yLabel:'Training log loss'})}<button class="code-link" data-action="source" data-key="encoder">Inspect native NatureEmbeddingEncoder source</button></div><div class="card"><h2>Evidence and uncertainty</h2><p class="small muted">Unknown ontology produces abstention. Missing fields and quality flags remain visible.</p>${table(['Measure','Value'],[['Test observations',fmt(t.test_records)],['Abstentions',fmt(t.abstained)],['Prediction coverage',t.operational?fmt(t.operational.coverage*100,1)+'%':'Not recorded'],['Recall including abstentions',fmt(t.operational?.recall_including_abstentions)],['False alerts',fmt(t.operational?.false_alerts)],['Missed positive records',fmt(t.operational?.missed_positive_records)],['Labeled events scored',fmt(t.detection.events)],['Missed labeled events',fmt(t.detection.missed)],['Median detection delay',t.detection.median_seconds==null?'Not measured':fmt(t.detection.median_seconds)+' s'],['Training source',esc(r.model.training_origin)]])}<p class="small muted" style="margin-top:12px">Time-to-detection is meaningful only for the supplied labels and event definitions.</p></div></div>`+
 `<div class="card"><div class="card-header"><div><h2>Ranked observations</h2><p>Select an observation to see its raw input and Merkle inclusion proof.</p></div><select id="source-filter" aria-label="Filter observations by source"><option value="all">All sources</option>${sources.map(s=>`<option value="${esc(s)}" ${state.selectedSource===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${table(['Observation','Source','Probability','Form class','Uncertainty','Disposition','Evidence'],selected.slice(0,40).map(p=>[`<span class="mono">${esc(p.id)}</span>`,esc(p.source_id),fmt(p.probability),esc(p.form_class),fmt(p.uncertainty),tag(p.decision,p.decision==='ABSTAIN'?'warn':p.decision==='CANDIDATE'?'':'gray'),`<button data-action="observation" data-id="${esc(p.id)}">Inspect ↗</button>`]))}</div>`;
}

function graphSVG(){
 if(!state.run)return '';const g=state.run.task13;const sources=g.nodes.filter(n=>n.type==='source'),obs=g.nodes.filter(n=>n.type==='observation');const coords={};const w=800,h=330;
 sources.forEach((n,i)=>coords[n.id]={x:80+i*(640/Math.max(1,sources.length-1)),y:80});
 const bysource={};obs.forEach(n=>(bysource[n.source_id]??=[]).push(n));
 sources.forEach((s,i)=>(bysource[s.id]||[]).forEach((n,j)=>{coords[n.id]={x:coords[s.id].x+(j%3-1)*37,y:195+Math.floor(j/3)*57};}));
 let svg=`<div class="graph-canvas"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Typed evidence graph with source and observation nodes"><defs><pattern id="graphdots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#54705a" opacity=".3"/></pattern></defs><rect width="800" height="330" fill="url(#graphdots)"/>`;
 g.edges.forEach(e=>{const a=coords[e.source],b=coords[e.target];if(!a||!b)return;if(e.status==='inferred'){svg+=`<path d="M${a.x},${a.y} Q${(a.x+b.x)/2},${a.y-65} ${b.x},${b.y}" fill="none" stroke="${e.confidence>=.5?'#b5bf74':'#637967'}" stroke-width="${1+e.confidence*2}" stroke-dasharray="5 4" opacity=".7"><title>${esc(e.type)} · ${fmt(e.confidence)}</title></path>`;}else svg+=`<path d="M${a.x},${a.y+20} C${a.x},145 ${b.x},145 ${b.x},${b.y}" fill="none" stroke="#568263" opacity=".5"/>`;});
 sources.forEach(n=>{const p=coords[n.id];svg+=`<g><rect x="${p.x-51}" y="${p.y-19}" width="102" height="38" rx="7" fill="#264c36" stroke="#749977"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle">${esc(n.label)}</text><text x="${p.x}" y="${p.y+34}" text-anchor="middle" style="font-size:8px;fill:#83a183">${esc(n.modality)}</text></g>`;});
 obs.forEach(n=>{const p=coords[n.id];if(!p)return;svg+=`<g class="map-marker" role="button" tabindex="0" aria-label="Inspect ${esc(n.id)}" data-action="observation" data-id="${esc(n.id)}"><circle cx="${p.x}" cy="${p.y}" r="12" fill="#122d24" stroke="${colors.classes[Number(n.label.slice(-1))]||'#98b37b'}" stroke-width="2"/><text x="${p.x}" y="${p.y+26}" text-anchor="middle" style="font-size:8px">${esc(n.label)}</text><title>${esc(n.id)} · ${fmt(n.confidence)}</title></g>`;});
 return svg+'</svg></div><div class="legend"><span><i class="legend-dot" style="background:#568263"></i>Recorded source edge</span><span><i class="legend-dot" style="background:#b5bf74"></i>Inferred corroboration · dashed</span><span>Top 20 scored observations shown</span></div>';
}
function linksPage(){
 const r=state.run;if(!r)return header('TASK 13 / FUSARIUM','Link analysis','Follow observed and inferred relationships back to their evidence.')+empty();const g=r.task13;
 return header('TASK 13 / FUSARIUM','What connects the observations?','Typed evidence with independent-source checks and explicit inferred relationships.',`<button data-action="run-scenario" data-scenario="S13-2">Test source removal</button>`)+runStrip()+
 (!g.leakage_audit.passed?`<div class="notice"><strong>Evaluation invalidated:</strong> ${esc(g.leakage_audit.reason)}. Contaminated benchmark scores are withheld.</div>`:'')+
 `<div class="grid four mb">${metric('Sources',fmt(g.source_count),'Stable source identifiers')}${metric('Candidate pairs',fmt(g.pairs.length),'Same pairs for both scorers')}${metric('Link F1',fmt(g.metrics.temporal_corroboration.f1),'Held-out pair labels')}${metric('Graph execution',fmt(g.seconds)+' s','Typed deterministic scorer','◷')}</div>`+
 `<div class="card mb"><div class="card-header"><div><h2>Evidence graph</h2><p>Relationships expose their source records. Source removal preserves the prior run.</p></div>${tag('Observed / inferred')}</div>${graphSVG()}${taskDetails('13')}</div>`+
 `<div class="card mb"><h2>Matched link-score comparison</h2><p class="small muted">This local scorer uses concurrent observations and source independence. No relational GNN checkpoint is loaded.</p>${algorithmTable(g.metrics)}</div>`+
 `<div class="grid two mb"><div class="card"><h2>Algorithm interaction</h2><p class="small muted">Same held-out observation IDs across sequence, graph context, fusion and shuffled control.</p>${algorithmTable(r.interaction.metrics)}<div class="divider"></div><p class="small">Paired F1 change, fused minus sequence: <strong>${fmt(r.interaction.paired_f1_delta)}</strong></p><p class="small muted">${esc(r.interaction.method)}. A zero or negative gain is retained as a result.</p></div><div class="card"><h2>Graph audit</h2>${table(['Check','Result'],[['Source identity','Stable ID, not display-name matching'],['Relation counts',esc(JSON.stringify(g.relation_counts))],['Edge leakage',tag(g.leakage_audit.passed?'No fixture overlap':'Invalidated',g.leakage_audit.passed?'':'bad')],['Type-invalid pairs rejected',fmt(g.type_invalid_pairs_rejected)],['Causal claim','None. Removal is a sensitivity test.']])}<div class="notice info" style="margin-top:15px">An edge’s evidence references support inspection. They do not prove that an inferred relationship is causal.</div></div></div>`+
 `<div class="card"><h2>Strongest candidate pairs</h2>${table(['Source pair','Score','Spatial baseline','Relation','Evidence'],[...g.pairs].sort((a,b)=>b.score-a.score).slice(0,25).map(p=>[`${esc(p.source_a)} ↔ ${esc(p.source_b)}`,fmt(p.score),fmt(p.baseline_score),tag('Inferred','blue'),`<button data-action="observation" data-id="${esc(p.a)}">First source</button> <button data-action="observation" data-id="${esc(p.b)}">Second source</button>`]))}</div>`;
}

function optionsPage(){
 const r=state.run;if(!r)return header('TASK 8 / MYCA + AVANI','Courses of action','Review distinct options, constraints and evidence before a human decision.')+empty();const t=r.task8;
 return header('TASK 8 / MYCA + AVANI','Options with inspectable constraints','A bounded advisory review. Native AVANI verdicts and hard envelope checks remain visible.',`<button data-action="constraints">Edit constraints</button><button data-action="run-scenario" data-scenario="S8-1">Test a contradiction</button>`)+runStrip()+
 `<div class="notice info"><strong>Active mode:</strong> deterministic seven-role review using native AVANI. This run made ${t.metrics.model_calls} LLM calls and issued no actuator commands. Semantic unsupported-assertion scoring requires SME adjudication.</div>`+
 `<div class="grid three mb">${t.options.map(o=>`<div class="card"><div class="option-status"><div class="eyebrow">${o.id}</div>${tag(o.status,o.status==='PASS'?'':o.status==='VETO'?'bad':'warn')}</div><h2 class="option-title">${esc(o.title)}</h2><div class="option-stats"><span><strong>${fmt(o.cost,0)}</strong>cost units</span><span><strong>${o.duration_minutes}</strong>minutes</span><span><strong>${fmt(o.uncertainty,2)}</strong>uncertainty</span></div><div class="divider"></div><p class="small muted">Native AVANI: <strong>${esc(o.native_avani.action)}</strong><br>Required resource: ${esc(o.resource)}</p><ul class="checklist">${Object.entries(o.checks).map(([k,v])=>`<li><span class="check-icon ${v?'':'bad'}">${v?'✓':'×'}</span>${esc(k.replaceAll('_',' '))}</li>`).join('')}</ul><div class="divider"></div><p class="small muted">${esc(o.reasons.join('; ')||'All declared checks satisfied. Human review remains required.')}</p><button data-action="option" data-id="${o.id}">Inspect action envelope</button></div>`).join('')}</div>`+
 `<div class="grid two mb"><div class="card"><h2>Proposal and review trace</h2><p class="small muted">Roles are deterministic functions in this local mode, not simulated independent language models.</p><div class="timeline">${t.trace.map(x=>`<div class="timeline-item"><h3>${esc(x.role)}</h3><p>${esc(x.result)}</p></div>`).join('')}</div></div><div class="stack"><div class="card"><h2>Goal contract</h2><p class="small">${esc(t.constraints.goal||'No goal supplied')}</p>${table(['Constraint','Value'],[['Maximum cost',fmt(t.constraints.max_cost)],['Maximum duration',fmt(t.constraints.max_duration_minutes)+' min'],['Independent sources',fmt(t.constraints.min_sources)],['Independent modalities',fmt(t.constraints.min_modalities)],['Uncertainty ceiling',fmt(t.constraints.uncertainty_limit)],['Maximum evidence age',fmt(t.constraints.max_evidence_age_seconds??300)+' s'],['Excluded stale/unresolved candidates',fmt(t.evidence_window?.stale_or_unresolved_excluded)],['Decision authority',esc(t.constraints.human_authority)]])}<div class="hash-line mono" style="margin-top:12px">Policy: ${t.policy_sha256}</div></div><div class="card"><h2>Evaluator adjudication</h2><p class="small muted">Record the quality of the option set against an explicit rubric. A citation’s presence is not an entailment score.</p><button data-action="rating" data-task="8">Record SME rating</button>${taskDetails('8')}</div></div></div>`;
}

function mapFeatures(){
 if(!state.run)return [];let fs=state.run.task14.geojson.features;const times=[...new Set(fs.map(f=>f.properties.occurred_at))].sort();const max=times[Math.min(times.length-1,Math.floor((times.length-1)*state.mapTime/100))];
 fs=fs.filter(f=>f.properties.occurred_at<=max&&(!state.mapHideStale||!f.properties.stale));return fs;
}
function mapSVG(){
 const fs=mapFeatures();if(!fs.length)return '<div class="empty"><p>No georeferenced observations match these filters.</p></div>';
 const w=810,h=390,pad=40;const lons=fs.map(f=>f.geometry.coordinates[0]),lats=fs.map(f=>f.geometry.coordinates[1]);let west=Math.min(...lons),east=Math.max(...lons),south=Math.min(...lats),north=Math.max(...lats);const dx=Math.max(.006,east-west)*.3,dy=Math.max(.006,north-south)*.3;west-=dx;east+=dx;south-=dy;north+=dy;
 const xy=f=>({x:pad+(f.geometry.coordinates[0]-west)/(east-west)*(w-2*pad),y:pad+(north-f.geometry.coordinates[1])/(north-south)*(h-2*pad)});
 const groups=new Map();fs.forEach(f=>{const key=f.geometry.coordinates.map(x=>x.toFixed(6)).join(',');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f);});let s=`<div class="map-canvas"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Offline EPSG 4326 observation map"><rect width="810" height="390" fill="#edf2e7"/>`;
 for(let i=0;i<=6;i++){const x=pad+(w-2*pad)*i/6;const y=pad+(h-2*pad)*i/6;s+=`<line x1="${x}" x2="${x}" y1="20" y2="370" stroke="#d7e1ce"/><line x1="20" x2="790" y1="${y}" y2="${y}" stroke="#d7e1ce"/><text x="${x}" y="383" text-anchor="middle">${(west+(east-west)*i/6).toFixed(4)}°</text><text x="12" y="${y-5}">${(north-(north-south)*i/6).toFixed(4)}°</text>`;}
 s+='<text x="771" y="30" style="font-size:12px">N ↑</text><text x="55" y="28" style="font-size:9px;fill:#97aa8a">OFFLINE COORDINATE VIEW / NO BASEMAP</text>';
 for(const points of groups.values()){
   const f=[...points].sort((a,b)=>b.properties.occurred_at.localeCompare(a.properties.occurred_at))[0];const p=xy(f),u=f.properties.uncertainty??1;const color=state.mapObserved?'#719680':f.properties.stale?'#a8a899':f.properties.decision==='CANDIDATE'?'#b49354':'#4f8766';const selected=state.mapSelected===f.properties.id;const labelX=p.x>w-180?p.x-157:p.x+14;
   if(!state.mapObserved)s+=`<circle cx="${p.x}" cy="${p.y}" r="${25+u*35}" fill="${color}" opacity=".09" stroke="${color}" stroke-dasharray="3 5"/>`;
   s+=`<g role="button" tabindex="0" class="map-marker" aria-label="Inspect map observation ${esc(f.properties.id)}" data-action="map-marker" data-id="${esc(f.properties.id)}"><circle cx="${p.x}" cy="${p.y}" r="${selected?11:8}" fill="${color}" stroke="white" stroke-width="3"/><rect x="${labelX}" y="${p.y-13}" width="139" height="36" rx="5" fill="#ffffffec" stroke="#d3dfca"/><text x="${labelX+8}" y="${p.y+1}" style="fill:#3b6041;font-size:10px">${esc(f.properties.source_id)}</text><text x="${labelX+8}" y="${p.y+15}" style="font-size:8px">${points.length} observations · ${f.properties.stale?'stale':state.mapObserved?'observed':fmt(f.properties.confidence)+' score'}</text><title>${esc(f.properties.id)} · ${esc(f.properties.occurred_at)}</title></g>`;
 }
 const center=(north+south)/2;const mpp=metersPerPixel(center,18);s+=`<rect x="58" y="335" width="145" height="27" rx="4" fill="#ffffffdc"/><text x="67" y="353" style="font-size:9px">${groups.size} locations / ${fs.length} observations</text></svg><div class="map-caption"><span>EPSG:4326 · north up · angular coordinate projection</span><span>Earth grid at z18: ${fmt(mpp,3)} m/pixel (Web Mercator)</span></div></div>`;return s;
}
function earthPage(){
 const r=state.run;if(!r)return header('TASK 14 / EARTH SIMULATOR + CREP','Evidence in its spatial context','Offline coordinates and native CREP products with source and time labels.')+empty();const m=r.task14;
 return header('TASK 14 / EARTH SIMULATOR + CREP','The same evidence, on the map','Deterministic projection with explicit source freshness and uncertainty.',exportButton('geojson','Export GeoJSON'))+runStrip()+
 `<div class="grid four mb">${metric('Mapped observations',fmt(m.metrics.mapped_records),'Native CREPMapBridge output','◌')}${metric('Unknown positions',fmt(m.metrics.missing_geometry),'Omitted from precise projection','⊘')}${metric('Stale observations',fmt(m.metrics.stale_records),'Age relative to replay cutoff','◷')}${metric('Product generation',fmt(m.seconds,4)+' s','CPU product time; browser drawing excluded','↗')}</div>`+
 `<div class="card mb"><div class="card-header"><div><h2>Environmental observation layer</h2><p>Markers group identical coordinates. Click a location to inspect the latest record shown.</p></div>${tag(state.mapObserved?'Observed-only view':'Inferred score overlay',state.mapObserved?'gray':'blue')}</div><div class="toolbar"><label class="check"><input type="checkbox" id="map-observed" ${state.mapObserved?'checked':''}>Observed-only projection</label><label class="check"><input type="checkbox" id="map-stale" ${state.mapHideStale?'checked':''}>Hide stale records</label><span class="small muted">Circle size depicts model uncertainty, not a validated positional interval.</span></div><div id="map-view">${mapSVG()}</div><div class="field" style="margin-top:14px"><label for="map-time">Replay cutoff · ${state.mapTime}% of the displayed interval</label><input type="range" id="map-time" min="0" max="100" value="${state.mapTime}"></div>${taskDetails('14')}</div>`+
 `<div class="grid two"><div class="card"><h2>Selected observation</h2><div id="map-detail">${mapDetail()}</div></div><div class="card"><h2>Projection provenance</h2>${table(['Field','Value'],[['Coordinate system','EPSG:4326'],['Map origin','Native NLM CREPMapBridge'],['Grid calculations','Native Earth Simulator grid-calculator.ts'],['Basemap','None loaded; no network dependency'],['Inference','Local readout; source records remain inspectable'],['Freshness clock','Relative to the replay cutoff']])}<div class="actions" style="margin-top:15px"><button class="code-link" data-action="source" data-key="earth_grid">Inspect grid source</button><button class="code-link" data-action="source" data-key="crep">Inspect CREP source</button></div></div></div>`;
}
function mapDetail(){
 const fs=mapFeatures();const f=fs.find(f=>f.properties.id===state.mapSelected)||fs[fs.length-1];if(!f)return '<p class="muted small">No marker selected.</p>';const [lon,lat]=f.geometry.coordinates;const p=f.properties;
 return `<p><strong>${esc(p.source_id)}</strong> ${tag(p.stale?'STALE':'RECORDED',p.stale?'warn':'')}</p><p class="mono small">${esc(p.id)}</p>${table(['Field','Value'],[['Latitude / longitude',fmt(lat,6)+' / '+fmt(lon,6)],['Observed at',esc(p.occurred_at)],['Age at replay cutoff',fmt(p.age_seconds)+' s'],['Model score',fmt(p.confidence)],['Form class',esc(p.form_class)],['Grid address at z18',`<span class="mono">${esc(getCellId(lat,lon,18))}</span>`]])}<p class="small muted" style="margin-top:12px">A fine grid address does not imply equivalent sensor-location accuracy.</p><button data-action="observation" data-id="${esc(p.id)}">Inspect raw input and proof ↗</button>`;
}

function formSpacePage(){
 const r=state.run;if(!r)return header('FORM SPACE / LOCAL ATLAS','Organized states with a traceable identity','A versioned partition of the native sensor representation.')+empty();const ps=r.task12.predictions.filter(p=>p.split==='test');const counts={};ps.forEach(p=>counts[p.form_class]=(counts[p.form_class]||0)+1);let svg='<svg class="chart" viewBox="0 0 750 410" role="img" aria-label="Form Space scatter plot of native temperature and humidity coordinates">';
 for(let i=0;i<=5;i++){const x=50+i*128,y=20+i*68;svg+=`<line x1="${x}" y1="20" x2="${x}" y2="360" stroke="#e1e9da"/><line x1="50" y1="${y}" x2="690" y2="${y}" stroke="#e1e9da"/><text x="${x}" y="380" text-anchor="middle">${(i/5).toFixed(1)}</text><text x="36" y="${y+4}">${(1-i/5).toFixed(1)}</text>`;}
 ps.forEach(p=>{const x=50+p.coordinates[0]*640,y=20+(1-p.coordinates[1])*340;svg+=`<circle cx="${x}" cy="${y}" r="4" opacity=".55" fill="${colors.classes[Number(p.form_class.slice(-1))]}" role="button" tabindex="0" aria-label="Inspect state ${esc(p.id)}" data-action="observation" data-id="${esc(p.id)}"><title>${esc(p.id)} · ${p.form_class}</title></circle>`;});
 r.model.centroids.forEach((c,i)=>{const x=50+c[0]*640,y=20+(1-c[1])*340;svg+=`<circle cx="${x}" cy="${y}" r="10" fill="white" stroke="${colors.classes[i]}" stroke-width="3"/><text x="${x+14}" y="${y+4}" style="fill:#556d4b">form-${i}</text>`;});svg+='<text x="350" y="404" text-anchor="middle">Native coordinate 0 / normalized temperature</text><text x="55" y="13">Native coordinate 1 / normalized humidity</text></svg>';
 return header('FORM SPACE / MINDEX LOCAL ATLAS','A state is more than a score','Inspect chart versions, class membership, reference distance, uncertainty and evidence.',`<button data-action="form-model">Inspect atlas model</button>`)+runStrip()+
 `<div class="notice info">This application implements a local, frozen four-class partition of the native 16-dimensional encoder. It does not claim discovered natural goals, validated attractors or cross-substrate equivalence. The reference target is the mean training background state.</div>`+
 `<div class="grid wide-left mb"><div class="card"><div class="card-header"><div><h2>State atlas</h2><p>Two named native coordinates are displayed. Classification uses all sixteen.</p></div>${tag('coastal-native16-v1')}</div>${svg}<div class="legend">${Object.entries(counts).map(([k,v])=>`<span><i class="legend-dot" style="background:${colors.classes[Number(k.slice(-1))]}"></i>${k}: ${v}</span>`).join('')}</div></div><div class="stack"><div class="card"><h2>Scientific contract</h2>${table(['Field','Meaning'],[['Space','Local coastal sensor representation'],['Chart','Versioned native 16D coordinates'],['Equivalence','Identical frozen partition membership'],['Target','Declared training background reference'],['Trajectory','Observed sequence of state estimates'],['Uncertainty','Readout uncertainty plus visible quality/missingness'],['Evidence','Observation ID and Merkle root']])}</div><div class="card"><h2>Persistence</h2><p class="small muted">Each run writes its Form States to the local SQLite atlas, linked to model identity and observation evidence. The supplied production SQL remains available as a source reference and is not automatically applied.</p><button data-action="navigate" data-page="data">Open Form Space source documents</button></div></div></div>`+
 `<div class="card"><h2>Latest state estimates</h2>${table(['Observation','Class','Distance to reference','Change in distance','Uncertainty','Evidence'],ps.slice(-24).map(p=>[`<span class="mono">${esc(p.id)}</span>`,esc(p.form_class),fmt(p.distance_to_target),fmt(p.form_velocity),fmt(p.uncertainty),`<button data-action="observation" data-id="${esc(p.id)}">Inspect</button>`]))}<p class="small muted" style="margin-top:12px">Distance change is per observation step. It is not a physical velocity or proof of recovery dynamics.</p></div>`;
}

function dataPage(){
 const docs=state.boot.documents,ds=state.boot.datasets.find(d=>d.id===state.dataset);return header('INPUTS / SOURCE RECORDS','Data & documents','All supplied documents are searchable. Imported measurements retain their own provenance.',`<button data-action="import">+ Import a file</button>`)+
 `<div class="grid four mb">${metric('Source documents',docs.length,'Original files, extracted text and hashes')}${metric('Available datasets',state.boot.datasets.length,'Synthetic and imported inputs stay labeled')}${metric('Structured tables',docs.reduce((n,d)=>n+d.tables,0),'DOCX tables available as CSV')}${metric('Current input',fmt(ds?.record_count),'Observations, separate from document prose')}</div>`+
 `<div class="card mb"><div class="card-header"><div><h2>Ask the source packet</h2><p>Native MYCA query interface with local retrieval. Answers are attributed excerpts.</p></div>${tag('Offline retrieval')}</div><form id="search-form" class="search-row"><input id="document-query" value="${esc(state.query)}" placeholder="Search tasks, Form Space, DIRTNet, constraints…" aria-label="Search source documents" required minlength="2"><button type="submit" class="primary">Search documents</button><button type="button" data-action="ask">Ask MYCA</button></form>${state.hits.length?`<div class="divider"></div>${state.hits.map(h=>`<div class="search-hit"><button class="code-link" data-action="document" data-id="${h.id}">${esc(h.name)} · page/section ${h.page} ↗</button><p class="small">${esc(h.snippet)}</p><span class="small muted mono">SHA256 ${short(h.sha256)}</span></div>`).join('')}`:state.query?'<p class="small muted">Search results will appear here.</p>':''}</div>`+
 `<div class="grid wide-left mb"><div class="card"><div class="card-header"><div><h2>Source collection</h2><p>Planning documents are requirements evidence; they are not measured run results.</p></div></div>${table(['Document','Pages / sections','Tables','Inspect'],docs.map(d=>[esc(d.name),d.pages,d.tables,`<button data-action="document" data-id="${d.id}">Open ↗</button>`]))}</div><div class="stack"><div class="card"><h2>Measurement datasets</h2>${state.boot.datasets.map(d=>`<div class="task-card"><div><h3>${esc(d.title)}</h3><p>${fmt(d.record_count)} records · ${esc(d.mode)}</p><button data-action="preview-data" data-id="${d.id}">Preview records</button></div></div>`).join('')}</div><div class="card"><h2>Import contract</h2><p class="small muted">Import CSV, JSON or GeoJSON observations. A document can also be imported for search and text/table export. Numbers in prose are never silently converted into sensor measurements.</p><button data-action="schema">View schema & sample CSV</button><p class="small muted" style="margin-top:12px">PDF, DOCX, MD, TXT, SQL and images are preserved. Image-only pages require an external OCR workflow.</p></div></div></div>`;
}
function testsPage(){
 const s=state.suite,bench=s?.kind==='benchmark',rows=state.boot.scenarios.filter(s=>state.testFilter==='all'||s.family===state.testFilter);
 const input=state.boot.datasets.find(d=>d.id===state.dataset);
 return header('EVALUATION / ADVERSARIAL CASES','Test laboratory','Measure scenario impact, inspect failures and export the evidence.',`<button data-action="benchmark" ${state.job?'disabled':''}>Five-seed component comparison</button><button data-action="stress" ${state.job?'disabled':''}>205 synthetic stress trials</button>`)+
 `<div class="notice info">Functional PASS means a named software check held. Quality findings show coverage, missed detections and degradation independently. Five-seed buttons use the synthetic generator. No Army acceptance decision is implied.</div>`+
 `<div class="card mb"><div class="form-row"><div class="field"><label for="dataset-select">Dataset for scenario sweep</label><select id="dataset-select">${state.boot.datasets.map(d=>`<option value="${esc(d.id)}" ${d.id===state.dataset?'selected':''}>${esc(d.title)} · ${d.record_count} records</option>`).join('')}</select></div><div class="field compact"><label for="seed-select">Seed</label><select id="seed-select">${[11,17,23,29,31].map(n=>`<option ${n===state.seed?'selected':''}>${n}</option>`).join('')}</select></div><button data-action="constraints">Constraints</button><button class="primary" data-action="suite" ${state.job?'disabled':''}>Run 41 cases on selected data</button></div><p class="small muted">${esc(input?.mode||'Choose input')} · Imports retain their origin. Fault overlays are labeled; cases without required fields are skipped with reasons.</p></div>`+
 `<div class="grid four mb">${metric('Scenario cases','41','40 planned cases + clean replay')}${metric('Functional passes',s&&!bench?String(s.passed):'—','Selected test session')}${metric('Failures / errors',s&&!bench?String(s.failed)+' / '+String(s.errors):'—','Quality degradation appears below')}${metric('Skipped prerequisites',s&&!bench?String(s.skipped||0):'—','Never counted as passes')}</div>`+
 (s?`<div class="card mb"><div class="card-header"><div><h2>${bench?'Paired component comparison':s.kind==='stress'?'Five-seed scenario stress results':'Scenario sweep results'}</h2><p>${esc(s.id)} · ${date(s.created_at)} · ${esc(s.dataset?.title||'Controlled synthetic generator')}</p></div><div class="actions">${['html','csv','json'].map(f=>`<a class="button" href="/api/export-suite?id=${s.id}&format=${f}">Export ${f.toUpperCase()} ↗</a>`).join('')}</div></div>${bench?`<div class="notice info">Mean fused − sequence F1: <strong>${fmt(s.paired_f1_delta_mean)}</strong>. 95% t interval across seeds: [${s.paired_f1_delta_95_t_interval.map(x=>fmt(x)).join(', ')}]. ${esc(s.interval_scope)}</div>${table(['Seed','Native F1','Temporal F1','Graph F1','Fused F1','Shuffled F1','Seconds'],s.rows.map(r=>[r.seed,fmt(r.task12.native_encoder.f1),fmt(r.task12.temporal_readout.f1),fmt(r.interaction.graph_context.f1),fmt(r.interaction.fused.f1),fmt(r.interaction.shuffled_control.f1),fmt(r.seconds)]))}`:table(['Case / seed','Functional','Quality finding','Coverage','F1 / Δ','Recall¹','False alerts','Inspect'],s.rows.map((r,i)=>{const a=r.assessment,m=a?.measured,d=a?.delta_from_clean;return [esc(r.scenario.id)+' / '+esc(r.seed??s.seed??'—'),tag(r.status,r.status==='PASS'?'':r.status==='SKIP'?'gray':'red'),a?tag(a.status,a.status==='MEASURED'?'':'warn'):esc(r.reason||r.error||'Not measured'),m?fmt(m.coverage*100,1)+'%':'—',fmt(m?.f1)+' / '+fmt(d?.f1),fmt(m?.recall),fmt(m?.false_alerts),`<button data-action="suite-row" data-index="${i}">Details</button>${r.run_id?` <button data-action="open-case" data-id="${r.run_id}">Open run</button>`:''}`]}))}<p class="small muted">¹ Recall counts abstained positives as missed. F1 uses eligible predictions. Deltas compare the same capture and frozen model; controlled injects can change truth/populations. Details include graph impact, event timing and advisory changes.</p></div>`:'')+
 `<div class="card mb"><div class="card-header"><div><h2>Scenario catalog</h2><p>Open a single case for all four products, observation proofs and a signed export.</p></div><select id="test-filter" aria-label="Filter scenario group"><option value="all">All groups</option>${[...new Set(state.boot.scenarios.map(s=>s.family))].map(g=>`<option value="${esc(g)}" ${state.testFilter===g?'selected':''}>${esc(g)}</option>`).join('')}</select></div>${table(['ID / group','Scenario','Expected behavior','Run'],rows.map(s=>[esc(s.id)+'<br><span class="small muted">'+esc(s.family)+'</span>',esc(s.name),esc(s.expected),`<button data-action="run-scenario" data-scenario="${s.id}" ${state.job?'disabled':''}>Run case</button>`]))}</div>`+
 `<div class="card"><h2>Saved test sessions</h2>${table(['Session','Created','Type','Open'],state.boot.suites.map(s=>[esc(s.id),date(s.created_at),esc(s.kind),`<button data-action="load-suite" data-id="${s.id}">Open</button>`]))}</div>`;
}
function requirementStatus(check){const r=state.run;return ({tasks:r?'Four products generated':'Ready to run',metrics:r?'Measured on labeled held-out inputs':'Run required',interaction:r?'Matched unit comparison recorded':'Run required',splits:r?'Capture group boundaries validated':'Run required',benchmark:state.boot.suites.some(x=>x.kind==='benchmark')?'Five-seed results available':'Run five-seed comparison',proof:r?(state.boot.signing_available?'Merkle roots ready; Ed25519 signing on export':'Merkle roots ready; signing dependency absent'):'Run required',suite:state.boot.suites.some(x=>x.kind==='suite')?'Scenario results available':'Run scenario sweep',timing:r?(r.timing.within_budget?'Local runtime within integrated target; not an Army acceptance decision':'Integrated target exceeded'):'Unmeasured',offline:'Local runtime, bundled documents and offline exports',sme:r?.ratings?.length?'Reviewer entries saved; semantic adjudication still required':'SME review pending',manual:'External evidence / confirmation not supplied',integrations:'Native modules active; full trained services not qualified'})[check]||'Inspect source';}
function evidencePage(){
 const r=state.run;return header('PROVENANCE / REPLAY / EXPORT','Evidence & export','Freeze the input, inspect the computation and verify the exported product.',r?exportButton():'')+(r?runStrip()+
 `<div class="grid four mb">${metric('Observation inclusion',r.proof.sample_verified?'Verified':'Failed','Native binary Merkle proof')}${metric('Evidence leaves',fmt(r.proof.observation_count),'Canonical input records')}${metric('Export signature',state.boot.signing_available?'Ed25519':'Unsigned',state.boot.signing_available?'Local operator key · pin fingerprint':'Optional cryptography dependency absent')}${metric('SME assessments',r.ratings?.length||0,'Actual saved reviewer entries')}</div>`+
 `<div class="grid two mb"><div class="card"><h2>Chain of evidence</h2>${table(['Root','SHA256'],[['Input observations',r.proof.event_root],['Configuration',r.proof.self_root],['Stable analyst products',r.proof.world_root],['Current frame',r.proof.frame_root],['Parent frame',r.proof.parent_frame_root||'First run']].map(([k,v])=>[k,`<span class="hash">${esc(v)}</span>`]))}<div class="actions" style="margin-top:16px"><button data-action="first-proof">Verify an inclusion proof</button><button data-action="proof">Full proof metadata</button></div><p class="small muted" style="margin-top:14px">Integrity proves that artifacts match their recorded inputs and signer. It does not prove that a sensor was calibrated or that an interpretation is true.</p></div><div class="card"><h2>Take the evaluation with you</h2><p class="small muted">The ZIP includes records, separate labels, model parameters, all four products, metrics, source hashes, audit events, PDF/HTML reports and an independent verifier.</p><div class="export-grid">${exportButton('zip','Complete evaluation ZIP')}${exportButton('pdf','PDF report')}${exportButton('html','Offline HTML report')}${exportButton('csv','Metrics CSV')}${exportButton('geojson','Map GeoJSON')}${exportButton('json','Full run JSON')}</div><div class="divider"></div><h3>Independent verification</h3><pre class="code">python replay.py run-…-evaluation.zip
python verify_bundle.py run-…-evaluation.zip \
  --trusted-key-sha256 &lt;independently pinned fingerprint&gt;</pre><p class="small muted">Exit 0: valid integrity and signature. Exit 1: invalid. Exit 2: unsigned or signature dependency unavailable. An included public key alone does not establish identity.</p></div></div>`+
 `<div class="grid two mb"><div class="card"><div class="card-header"><div><h2>Reviewer assessments</h2><p>No utility score is invented by the model.</p></div><button data-action="rating">Record assessment</button></div>${table(['Reviewer','Task','Score / 5','Notes'],(r.ratings||[]).map(x=>[esc(x.reviewer),esc(x.task_id),x.score,esc(x.notes)]))}</div><div class="card"><h2>Runtime record</h2>${table(['Measurement','Value'],Object.entries(r.hardware).map(([k,v])=>[esc(k.replaceAll('_',' ')),esc(v)]))}<p class="small muted" style="margin-top:12px">CPU timings exclude browser drawing and export I/O. Peak RSS is the process lifetime high-water mark.</p></div></div>`:empty())+
 `<div class="card mb"><h2>Requirements traceability</h2><p class="small muted">Internal preparation targets and outstanding Army confirmations retain their original authority.</p>${table(['Requirement','Authority','Local coverage / remaining evidence'],state.boot.requirements.map(x=>[esc(x.id)+' · '+esc(x.name||x.requirement),esc(x.authority),esc(requirementStatus(x.check))+'<br><span class="small muted">'+esc(x.source)+'</span>']))}</div>`+
 `<div class="card"><h2>Run history</h2>${table(['Run','Created','Dataset','Case','Seconds','Open'],state.boot.runs.map(x=>[esc(x.id),date(x.created_at),esc(x.dataset.mode),esc(x.config.scenario_id),fmt(x.timing.total_seconds),`<button data-action="load-run" data-id="${x.id}">Open</button>`]))}</div>`;
}
function integrationsPage(){return header('SYSTEMS / EXECUTED CODE','System connections','See which original modules execute locally and configure optional private-network services.')+
 `<div class="notice info">Every default run uses the local implementation recorded below. A successful service health check does not change the run backend. Optional service samples are shown separately and never silently substituted into measured results.</div>`+
 `<div class="grid two mb">${Object.entries(state.boot.services).map(([key,p])=>`<div class="card"><div class="card-header"><div><h2>${{nlm:'NLM inference',mindex:'MINDEX search',myca:'MYCA brain',earth:'Earth Simulator'}[key]}</h2><p class="mono small">${esc(p.base_url)}</p></div>${tag(state.probes[key]?.status||'Not probed',state.probes[key]?.status==='CONNECTED'?'':state.probes[key]?.status==='UNAVAILABLE'?'warn':'gray')}</div><p class="small muted">Health: ${esc(p.health_path)}<br>Action: ${esc(p.action_path||'Status only in this application')}</p>${state.probes[key]?`<p class="small">${esc(state.probes[key].error||state.probes[key].boundary)}</p>`:''}<div class="actions"><button data-action="probe" data-service="${key}">Check service</button><button data-action="service-config" data-service="${key}">Configure</button>${['nlm','mindex'].includes(key)?`<button data-action="service-sample" data-service="${key}" ${key==='nlm'&&!state.run?'disabled':''}>${key==='nlm'?'Test one observation':'Search service'}</button>`:''}${key==='earth'?`<a class="button" target="_blank" rel="noopener" href="${esc(p.base_url+p.action_path)}">Open full application ↗</a>`:''}</div></div>`).join('')}</div>`+
 `<div class="card mb"><h2>Original code provenance</h2><p class="small muted">Inspect the exact local file and its upstream reference. Some reference files describe optional services and are not executed.</p>${table(['Module','Usage','Local hash','Source'],state.boot.source_manifest.map(x=>[esc(x.key),esc(x.usage||x.description||x.changes),`<span class="mono">${short(x.local_sha256)}</span>`,`<button data-action="source" data-key="${esc(x.key)}">Inspect code</button>`]))}</div>`+
 `<div class="card"><h2>Demonstration boundary</h2><p class="small muted">NLM’s native encoder and Merkle code, MYCA query and CREP bridges, AVANI scalar governance, MINDEX worldview metadata, and the Earth Simulator grid functions are used directly. The temporal readout, typed graph scorer, seven-role option review, local atlas and network experiments are implementations in this application. Full trained SSM/GNN checkpoints, multi-LLM agents, production MINDEX and physical DIRTNet hardware require separate deployment and evidence.</p></div>`;}

function modal(title,body){const el=$('#modal');el.innerHTML=`<div class="modal-backdrop"><section class="modal-panel" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-header"><h2>${esc(title)}</h2><button data-action="close-modal" aria-label="Close dialog">✕</button></div><div class="modal-body">${body}</div></section></div>`;el.style.display='block';el.querySelector('button,input,select,textarea')?.focus();}
function closeModal(){$('#modal').innerHTML='';$('#modal').style.display='none';}
function jsonModal(title,obj){modal(title,`<pre class="code">${esc(JSON.stringify(obj,null,2))}</pre>`);}
function render(){
 if(!state.boot)return;const pages={overview,walkthrough,data:dataPage,patterns:patternsPage,links:linksPage,options:optionsPage,earth:earthPage,formspace:formSpacePage,tests:testsPage,evidence:evidencePage,integrations:integrationsPage};if(!pages[state.page])state.page='overview';
 $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#overview"><span class="brand-symbol">◈</span><span>MYCOSOFT<small>ITDX26 / ALGORITHM LAB</small></span></a><div class="nav-label">EVALUATION WORKSPACE</div><nav aria-label="Main navigation">${navigation.map(([id,label,icon])=>`<a href="#${id}" aria-label="${esc(label)}" class="nav-item ${id===state.page?'active':''}" ${id===state.page?'aria-current="page"':''}><span class="nav-icon">${icon}</span><span class="nav-text">${label}</span></a>`).join('')}</nav><div class="nav-label"><a href="/workbench.html">Source reports & Borda ↗</a></div><div class="nav-label"><a href="/readiness.html">Capability audit ↗</a></div><div class="sidebar-footer"><span class="status-dot"></span> Local environment<div class="small">v${esc(state.boot.version)} · CPU / offline</div></div></aside><main class="main" id="main" tabindex="-1"><div class="topbar"><span class="breadcrumb">Workspace <span>/</span> ${esc(navigation.find(x=>x[0]===state.page)[1])}</span><div class="actions">${tag('UNCLASSIFIED • DEMONSTRATION','gray')}<span class="top-avatar">M</span></div></div><div class="page-content">${state.job?`<div class="job-banner"><div class="spinner"></div><div><strong>${esc(state.job.kind)} in progress</strong><div class="small">${esc(state.job.events?.at(-1)?.message||'Preparing execution…')}</div></div><span class="spacer"></span><button data-action="cancel">Cancel</button></div>`:''}${pages[state.page]()}</div><footer>Mycosoft ITDX26 Algorithm Lab · Measured local results · Source-attributed evidence</footer></main>`;
}
function navigate(page){if(state.page===page)render();else location.hash=page;window.scrollTo(0,0);}
async function refresh(){state.boot=await api('/api/bootstrap');}
async function start(kind='run',scenario=null){if(state.job)return toast('A job is already running.',true);if(scenario)state.scenario=scenario;const args=['run','suite'].includes(kind)?{seed:state.seed,scenario_id:state.scenario,dataset_id:state.dataset,constraints:state.constraints}:{};state.job=await api('/api/'+kind,args);render();pollJob();}
async function pollJob(){clearTimeout(pollTimer);if(!state.job)return;try{const j=await api('/api/jobs/'+state.job.id);state.job=j;if(['COMPLETED','CANCELLED','ERROR'].includes(j.status)){state.job=null;await refresh();if(j.status==='COMPLETED'){if(j.kind==='run'){state.run=await api('/api/run?id='+j.result_id);state.mapSelected=null;state.selectedSource='all';state.mapTime=100;}else{state.suite=await api('/api/suite?id='+j.result_id);navigate('tests');}toast(j.kind==='run'?'All four tasks completed. Evidence is ready.':'Evaluation completed. Measured results are ready.');}else toast(j.error||'Job cancelled. No successful result was recorded.',j.status==='ERROR');render();return;}render();pollTimer=setTimeout(pollJob,700);}catch(e){state.job=null;render();toast(e.message,true);}}
async function openObservation(id,index=null){if(!state.run)return;const p=state.run.task12.predictions.find(x=>x.id===id);const idx=index??state.run.task12.predictions.findIndex(x=>x.id===id);if(idx<0)throw new Error('Observation is not in this run');const ev=await api('/api/evidence?run_id='+state.run.id+'&index='+idx);modal('Observation & inclusion proof',`${tag(ev.verified?'Inclusion verified':'Verification failed',ev.verified?'':'red')}<p class="small muted">Index ${idx} of ${ev.total}; the record is hashed and verified against the run’s input root.</p><h3>Raw observation</h3><pre class="code">${esc(JSON.stringify(ev.observation,null,2))}</pre>${p?'<h3>Algorithm result</h3><pre class="code">'+esc(JSON.stringify(p,null,2))+'</pre>':''}<details><summary>Merkle siblings, direction bits and root</summary><pre class="code">${esc(JSON.stringify(ev.proof,null,2))}</pre></details>`);}
async function openDocument(id){const d=await api('/api/document?id='+id);modal(d.name,`<div class="actions"><a class="button" href="/api/document/download?id=${id}">Original file ↗</a><a class="button" href="/api/document/text?id=${id}">Export text ↗</a>${d.tables.length?`<a class="button" href="/api/document/tables?id=${id}">Export tables CSV ↗</a>`:''}</div><p class="small muted">${esc(d.extraction)}</p><p class="hash">SHA256 ${esc(d.sha256)}</p>${/\.(png|jpe?g)$/i.test(d.name)?`<img alt="Original figure contact sheet" style="width:100%" src="/api/document/download?id=${id}">`:''}<pre class="document-text">${esc(d.text)}</pre>`);}
function constraintsModal(){modal('Scenario constraints',`<p class="small muted">Edit the review envelope as JSON. Hard safety rules are evaluated outside the learned score. Named fault scenarios apply their injection after this envelope.</p><form id="constraints-form"><textarea id="constraints-json" rows="18" aria-label="Constraint JSON">${esc(JSON.stringify(state.constraints||state.boot.constraints,null,2))}</textarea><div class="actions" style="margin-top:16px"><button class="primary" type="submit">Save constraints</button><button type="button" data-action="reset-constraints">Reset defaults</button></div></form>`);}
function importModal(){modal('Import observations or a source document',`<form id="import-form"><div class="field"><label for="import-kind">Use this file as</label><select id="import-kind"><option value="document">Source document for search and export</option><option value="observations">Measurement observations (CSV / JSON / GeoJSON)</option></select></div><div class="field" style="margin-top:16px"><label for="import-file">Local file · maximum 16 MB</label><input id="import-file" type="file" required accept=".csv,.json,.geojson,.pdf,.docx,.md,.txt,.sql,.png,.jpg,.jpeg"></div><p class="small muted">Labels must be a separate truth mapping in JSON. Unlabeled measurements run with the synthetic-trained reference model; accuracy metrics stay unmeasured.</p><button class="primary" type="submit">Import file</button></form>`);}
const sampleCSV='id,source_id,modality,observed_at,lat,lon,temperature_c,humidity_percent,pressure_hpa,gas_resistance_ohms,iaq_index,audio_level_db,fci_strength\nfield-001,site-a,thermal,2026-09-08T12:00:00Z,32.565,-117.129,23,55,1013,80000,42,35,0.4\n';
function schemaModal(){modal('Observation import schema',`<p class="small muted">CSV sensor columns can also be nested under <code>variables</code> in JSON. Use unique stable IDs, timezone-qualified timestamps and coordinates in EPSG:4326, or declare supported EPSG:3857.</p><pre class="code">${esc(sampleCSV)}</pre><button data-action="sample-csv">Download sample CSV</button><div class="divider"></div><pre class="code">${esc(JSON.stringify({records:[{id:'field-001',source_id:'site-a',modality:'thermal',observed_at:'2026-09-08T12:00:00Z',group:'field-capture-01',split:'test',lat:32.565,lon:-117.129,crs:'EPSG:4326',variables:{temperature_c:23,humidity_percent:55,pressure_hpa:1013,gas_resistance_ohms:80000,iaq_index:42,audio_level_db:35,fci_strength:.4}}],truth:{'field-001':{label:0,event_id:null}}},null,2))}</pre><p class="small muted">Optional labels are only used after inference for evaluation. For a custom model fit, supply independent groups assigned to train, validation and test. A group may not span splits.</p>`);}
function downloadText(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ratingModal(){if(!state.run)return toast('Run an evaluation first.',true);modal('Record an SME assessment',`<form id="rating-form"><div class="form-row"><div class="field"><label for="reviewer">Reviewer name / ID</label><input id="reviewer" required maxlength="100"></div><div class="field"><label for="rating-task">Task</label><select id="rating-task">${state.boot.tasks.map(t=>`<option value="${t.id}">${t.id} · ${esc(t.name)}</option>`).join('')}</select></div><div class="field compact"><label for="rating-score">Utility score / 5</label><select id="rating-score">${[1,2,3,4,5].map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="field"><label for="rating-notes">Assessment notes</label><textarea id="rating-notes" rows="5" maxlength="4000" placeholder="What was useful? Which claim or evidence needs improvement?"></textarea></div><p class="small muted">This records your actual review. It does not convert functional tests into Army acceptance.</p><button type="submit" class="primary">Save assessment</button></form>`);}

async function action(el){const a=el.dataset.action,id=el.dataset.id;
 if(a==='navigate')return navigate(el.dataset.page);
 if(a==='run')return start();if(a==='run-scenario')return start('run',el.dataset.scenario);if(a==='suite'||a==='benchmark'||a==='stress')return start(a);
 if(a==='cancel'){await api('/api/cancel',{job_id:state.job.id});return toast('Cancellation requested.');}
 if(a==='close-modal')return closeModal();if(a==='guide'){state.guide=Number(el.dataset.step);return render();}
 if(a==='constraints')return constraintsModal();if(a==='reset-constraints'){state.constraints=null;closeModal();render();return;}
 if(a==='config')return jsonModal('Frozen run configuration',state.run.config);if(a==='proof')return jsonModal('Run proof',state.run.proof);
 if(a==='observation')return openObservation(id);if(a==='first-proof')return openObservation(state.run.task12.predictions[0].id,0);
 if(a==='document')return openDocument(id);if(a==='import')return importModal();if(a==='schema')return schemaModal();if(a==='sample-csv')return downloadText('itdx_observation_sample.csv',sampleCSV,'text/csv');
 if(a==='source'){const result=await api('/api/source?key='+encodeURIComponent(el.dataset.key));return modal('Code · '+result.manifest.key,`<pre class="code">${esc(JSON.stringify(result.manifest,null,2))}</pre><pre class="code">${esc(result.content)}</pre>`);}
 if(a==='form-model')return jsonModal('Frozen Form Space atlas & learned readout',state.run.model);
 if(a==='preview-data'){const d=await api('/api/dataset?id='+id);return modal(d.dataset.title,`<p class="small muted">First ${d.records.length} of ${d.total} source records.</p><pre class="code">${esc(JSON.stringify(d,null,2))}</pre>`);}
 if(a==='ask'){state.query=$('#document-query').value;const r=await api('/api/ask',{query:state.query});return modal('MYCA · source-attributed answer',`<div class="notice info">${esc(r.boundary)}</div><pre class="document-text">${esc(r.answer.summary||r.answer.answer||JSON.stringify(r.answer,null,2))}</pre>${r.citations.map(c=>`<div class="search-hit"><button data-action="document" data-id="${c.id}">${esc(c.name)} · section ${c.page} ↗</button><p class="small">${esc(c.snippet)}</p></div>`).join('')}`);}
 if(a==='assessment')return jsonModal('Measured scenario impact',state.run.assessment);
 if(a==='suite-row')return jsonModal('Scenario evaluation detail',state.suite.rows[Number(el.dataset.index)]);
 if(a==='load-suite'){state.suite=await api('/api/suite?id='+id);return render();}
 if(a==='open-case'){state.run=await api('/api/run?id='+id);state.scenario=state.run.config.scenario_id;state.seed=state.run.config.seed;state.dataset=state.boot.datasets.some(d=>d.id===state.run.dataset.id)?state.run.dataset.id:state.dataset;state.mapSelected=null;return navigate('patterns');}
 if(a==='load-run'){state.run=await api('/api/run?id='+id);state.scenario=state.run.config.scenario_id;state.seed=state.run.config.seed;state.mapSelected=null;return render();}
 if(a==='option')return jsonModal('Advisory action envelope',state.run.task8.options.find(o=>o.id===id));
 if(a==='map-marker'){state.mapSelected=id;return render();}
 if(a==='rating')return ratingModal();
 if(a==='probe'){el.disabled=true;state.probes[el.dataset.service]=await api('/api/probe',{service:el.dataset.service});render();return;}
 if(a==='service-config'){const key=el.dataset.service,p=state.boot.services[key];modal('Configure '+key.toUpperCase(),`<form id="service-form" data-service="${key}">${Object.entries(p).map(([k,v])=>`<div class="field" style="margin-bottom:14px"><label for="service-${k}">${esc(k.replaceAll('_',' '))}</label><input id="service-${k}" name="${k}" value="${esc(v)}"></div>`).join('')}<p class="small muted">Use localhost or a private network. Credentials are read from the named environment variable; enter its name, never a secret value.</p><button type="submit" class="primary">Save configuration</button></form>`);return;}
 if(a==='service-sample'){el.disabled=true;try{const r=await api('/api/service-sample',{service:el.dataset.service,run_id:state.run?.id,query:'environment'});jsonModal('External service sample · separate from run metrics',r);}finally{el.disabled=false;}return;}
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(el){e.preventDefault();try{await action(el);}catch(error){toast(error.message,true);}}const marker=e.target.closest('[data-map-marker]');if(marker){state.mapSelected=marker.dataset.mapMarker;render();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Enter'&&e.target.matches('svg [role="button"]'))e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));if(e.key==='Tab'&&$('#modal').style.display==='block'){const els=[...$('#modal').querySelectorAll('button,a,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='dataset-select'){state.dataset=el.value;render();}if(el.id==='seed-select')state.seed=Number(el.value);if(el.id==='scenario-select'){state.scenario=el.value;render();}if(el.id==='source-filter'){state.selectedSource=el.value;render();}if(el.id==='test-filter'){state.testFilter=el.value;render();}if(el.id==='map-observed'){state.mapObserved=el.checked;render();}if(el.id==='map-stale'){state.mapHideStale=el.checked;render();}if(el.id==='map-time'){state.mapTime=Number(el.value);render();}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,submit=f.querySelector('[type="submit"]');if(submit)submit.disabled=true;try{
 if(f.id==='search-form'){state.query=$('#document-query').value;state.hits=(await api('/api/search?q='+encodeURIComponent(state.query))).hits;render();}
 if(f.id==='constraints-form'){const c=JSON.parse($('#constraints-json').value);if(!c||Array.isArray(c)||typeof c!=='object')throw new Error('Enter a JSON object');state.constraints=c;closeModal();render();toast('Constraints saved for the next run.');}
 if(f.id==='import-form'){const file=$('#import-file').files[0];if(!file)throw new Error('Choose a file');if(file.size>16000000)throw new Error('File exceeds 16 MB');const kind=$('#import-kind').value;const raw=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<raw.length;i+=32768)binary+=String.fromCharCode(...raw.subarray(i,i+32768));const result=await api('/api/import',{kind,name:file.name,data_base64:btoa(binary)});await refresh();if(result.dataset)state.dataset=result.dataset.id;closeModal();render();toast('File imported and indexed.');}
 if(f.id==='rating-form'){await api('/api/rating',{run_id:state.run.id,task_id:$('#rating-task').value,reviewer:$('#reviewer').value,score:Number($('#rating-score').value),notes:$('#rating-notes').value});state.run=await api('/api/run?id='+state.run.id);closeModal();render();toast('Reviewer assessment saved.');}
 if(f.id==='service-form'){const p={};for(const input of f.querySelectorAll('input'))p[input.name]=input.value;const profiles={...state.boot.services,[f.dataset.service]:p};await api('/api/services',{services:profiles});await refresh();closeModal();render();toast('Service profile saved.');}
 }catch(err){toast(err.message,true);}finally{if(submit)submit.disabled=false;}});
window.addEventListener('hashchange',()=>{if(location.hash==='#main'){$('#main')?.focus();return;}state.page=location.hash.slice(1)||'overview';render();window.scrollTo(0,0);});
async function init(){try{await refresh();if(state.boot.runs.length)state.run=await api('/api/run?id='+state.boot.runs[0].id);if(state.boot.suites.length)state.suite=await api('/api/suite?id='+state.boot.suites[0].id);if(state.boot.active_jobs.length)state.job=state.boot.active_jobs[0];render();if(state.job)pollJob();}catch(e){$('#app').innerHTML=`<div class="fatal"><h1>Unable to load the local workspace</h1><p>${esc(e.message)}</p><p>Keep the launch terminal open, then reload this page.</p><button data-action="reload">Reload</button></div>`;document.querySelector('[data-action="reload"]').onclick=()=>location.reload();}}
init();
